### ISSUE TITLE
Improve support for code blocks that have long code statements

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1017]
Current: code blocks require horizontal scrolling if the lines are longer than the boxes.
Suggested: give an easy way to see the code without scrolling e.g., auto expand to full width when you click on the code block.
Also, we might want to auto-wrap longer lines to make such code blocks printer friendly.

**Comment by yamgent** [comment]
> Also, we might want to auto-wrap longer lines to make such code blocks printer friendly.

Auto wrap can be enabled by adding this css style:

```css
pre {
    white-space: pre-wrap;
}
```

**Comment by alyip98** [comment]
I tested with Google Chrome's print preview and the current implementation looks like this:

![image](https://user-images.githubusercontent.com/2277141/73720501-0d5dc080-475d-11ea-984e-b7784acbcc72.png)

The effect is the same as adding 
```css
pre {
    white-space: pre-wrap;
}
```
The wrapped line does not start where we expect it to.

Furthermore, I've done a bit of research on how others implement line numbers and most of them (Github, hljs line number [plugin](https://github.com/wcoder/highlightjs-line-numbers.js/)) use a `<table>` to style their line numbers. There is a line number [plugin](https://prismjs.com/plugins/line-numbers/#examples) for prismjs that uses spans but they generate them in JS with dynamically resized dimensions.

This means that we effectively can't use auto wrap. The simplest solution (and my preferred) would be to change our implementation to use `<table>` instead of `<span>`. Another solution could be inspired by the prismjs plugin and use client side JS.

In terms of "expanding" the code, we could add double-click to toggle wrapping.

**Comment by nbriannl** [comment]
> This means that we effectively can't use auto wrap. The simplest solution (and my preferred) would be to change our implementation to use <table> instead of <span>. Another solution could be inspired by the prismjs plugin and use client side JS.

If that's the case @openorclose should consider trying this method since he's doing #991 now.

**Comment by openorclose** [comment]
I changed some css and now it looks like:

![image](https://user-images.githubusercontent.com/3646725/73730655-186f1b80-4772-11ea-8fee-d919e18a82d0.png)

**Comment by marvinchin** [comment]
I personally found the auto line wrap on hover makes the code block harder to read. What do you think of making line wrapping a fixed user defined attribute (wrap or no-wrap) instead of having it done on hover?

**Comment by acjh** [comment]
How about:
- wrap on click/tap on the code block, and
- unwrap on click/tap outside the code block?

**Comment by marvinchin** [comment]
Toggling the wrap on click/tap might make selecting for copying less user friendly. It also feels like one of those "hidden" behaviours where it's not very intuitive to the reader. Having some sort of button to toggle it would make this more explicit but it would also add more UI clutter.

This is just my 2c thought - I'm happy to keep it as it is if everyone else prefers the current behaviour.

**Comment by damithc** [comment]
I don't mind having a small icon-like button for this purpose. We can even make it appear on hover/tap?

**Comment by tlylt** [comment]
Given that the [codeBlockWrapButtons plugin](https://markbind.org/userGuide/usingPlugins.html#plugin-codeblockwrapbuttons) has been added, will close this issue as completed if no objections.
