### ISSUE TITLE
Better documentation and contribution guide

### ISSUE THREAD

**Issue by le0tan** [MarkBind/markbind#1027]
**Is your request related to a problem?**

Currently not all functions in MarkBind are well-documented, and in the devguide there's no overview of how the generation works - which may make it difficulty for a newcomer to get started with contributing to MarkBind.

**Describe the solution you'd like**

- [ ]  JSDoc for all functions
- [x] Introduction to the architecture of MarkBind
- [x] Contribution guide to components (adding new components or adding features to existing components)

**Describe alternatives you've considered**

na

**Additional context**

na

**Comment by nbriannl** [comment]
I agree, it would be really good to end off the semester with good documentation for future MarkBind devs.

**Comment by nbriannl** [comment]
Related to #816 #1139

**Comment by jovyntls** [comment]
> * [ ]   JSDoc for all functions

Could I check what the scope of this would be (do we want _all_ functions to have JSDoc)? 
Some cases to consider:
- for groups of functions (such as [processXXXAttributes](https://github.com/MarkBind/markbind/blob/1bd81ff03b9eecf142deed8832e4fe35ec2af823/packages/core/src/html/MdAttributeRenderer.js#L103-L145)) that perform a similar job - may be better to have one overarching JSDoc comment for the group since a JSDoc for each function may be repetitive and not provide additional value to the reader
- simpler functions that might be self-explanatory, e.g. [`isMarkdownFileExt`](https://github.com/MarkBind/markbind/blob/1bd81ff03b9eecf142deed8832e4fe35ec2af823/packages/core/src/utils/fsUtil.js#L18-L20), might not need JSDocs?

**Comment by tlylt** [comment]
> > * [ ]    JSDoc for all functions
> 
> Could I check what the scope of this would be (do we want _all_ functions to have JSDoc)? Some cases to consider:

I feel that this scope is too broad and perhaps a little impractical.

Also given that we are moving to TypeScript in the future, JSDocs could be less useful in general (the input, output return type part).

**Comment by kaixin-hc** [comment]
I think the most confusing part of the js section is the Site Generation file, and the confusion mainly comes from how large it is rather than the functions being undocumented. Perhaps if #1756 can be achieved we can close this issue?

**Comment by ang-zeyu** [comment]
@jovyntls @tlylt agreed. Jsdocs could still be useful for providing high level descriptions of classes / functions.

To provide some context, at this point https://github.com/MarkBind/markbind/pull/1039 we haven't really been considering typescript yet (was suggested in the thread briefly). 

> Perhaps if https://github.com/MarkBind/markbind/issues/1756 can be achieved we can close this issue?

👍
