### ISSUE TITLE
<box>: use fixed icon width for seamless style boxes

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1041]
Current:
![image](https://user-images.githubusercontent.com/1673303/74342921-39281880-4de5-11ea-8be2-218fb7a82d5c.png)

It's better if the vertical bar appears at the same position in all variations?

**Comment by yash-chowdhary** [comment]
I tried applying a fixed width to the `icon-wrapper` class. That way, even the non-seamless style boxes will have their content aligned. 
I used `em` units because we allow sizing of icons. 
This is what it looks like using a width of `1em` with different icon sizes -
<img width="891" alt="Screenshot 2020-02-14 at 2 05 49 PM" src="https://user-images.githubusercontent.com/21968718/74505834-1d328d00-4f33-11ea-918c-ef3f5b1723c9.png">

When the size of the icon gets larger in the non-seamless box, the width is quite apparent. 
However, a smaller width (e.g. `.7em`) distorts the `vertical-bar` for large-sized icons as seen here - 
<img width="840" alt="Screenshot 2020-02-14 at 2 28 09 PM" src="https://user-images.githubusercontent.com/21968718/74507018-3be65300-4f36-11ea-9742-00ceda1cdc0d.png">

`width: 1em` gives the best results, without any distortion of the vertical divider. I feel that we can compromise on the width being quite obvious if we want to maintain alignment, as it enhances readability.

Can I get some feedback on this?

**Comment by damithc** [comment]
> Can I get some feedback on this?

I'm OK with it. Let's wait to hear from some others though.

**Comment by nbriannl** [comment]
![image](https://user-images.githubusercontent.com/27397021/74583390-9d272880-5001-11ea-9b61-80013a2364c1.png)

Would it be possible to center align the icon relative to the wrapper?

**Comment by yash-chowdhary** [comment]
> Would it be possible to center align the icon relative to the wrapper?

Yup. Here's how it'll look like -
<img width="781" alt="Screenshot 2020-02-23 at 9 24 58 AM" src="https://user-images.githubusercontent.com/21968718/75103266-5e572b00-561e-11ea-9791-e9826c600ab4.png">

**Comment by damithc** [comment]
Looks like this PR affected another feature https://github.com/MarkBind/markbind/pull/1123#issuecomment-605742079

**Comment by yash-chowdhary** [comment]
Looking into it 👍
