### ISSUE TITLE
Improper linking of headings that have part of text enclosed within "<>" 

### ISSUE THREAD

**Issue by yash-chowdhary** [MarkBind/markbind#1076]
**Tell us about your environment**

* **MarkBind Version:** 2.11.0

**What did you do? Please include the actual source code causing the issue.**
There are instances where part of the header text that is enclosed within "<>". 
Referring to such headings using hrefs is not straightforward.
For example, the heading - 
# Specifying Variables in an `<include>`
will have to be linked using the following href - `#specifying-variables-in-an-and-lt-include-and-gt`

**What did you expect to happen?**
The href should be `#specifying-variables-in-an-include`

**What actually happened? Please include the actual, raw output.**
The href was `#specifying-variables-in-an-and-lt-include-and-gt`, as the string passed as input to slugify is `Specifying variables in an &lt; include &gt;`

There are a couple of instances in the user guide where linking [such headers](https://markbind.org/userGuide/reusingContents.html#specifying-variables-in-an-include) is broken ([this](https://markbind.org/userGuide/reusingContents.html#specifying-variables-in-an-and-lt-include-and-gt) is the correct link).

**Suggested Fix(es)**
For this particular case, I have tried removing the "[-]?and-lt"  and "[-]?and-gt" substrings from the slugified text like so - 
```js
headerId = headerId.replace(/[-]?and-lt/g, '');
headerId = headerId.replace(/[-]?and-gt/g, '');
```

**Comment by ang-zeyu** [comment]
We can use the custom replacements option here https://www.npmjs.com/package/@sindresorhus/slugify for a slightly easier fix.
e.g. `['and lt', ''], ['and gt', '']` for `customReplacements`

The slugify package actually erases `<` and `>` by default.
The issue here is that markdown-it escapes `<` and `>` into `&lt/gt;` before it is passed to htmlparser2, which slugify converts to `and-lt/and-gt`.

The first h1 here is from a markdown heading, the second from a normal `<h1>` tag
![mdvsnormal](https://user-images.githubusercontent.com/3306138/75665676-80504d80-5caf-11ea-90a3-0280d09d1353.png)
