### ISSUE TITLE
Non-hovered code block affects width of main content wrapper

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#1077]
**Tell us about your environment**

* **MarkBind Version:** Latest master

**What did you do? Please include the actual source code causing the issue.**

![codeblockwidth](https://user-images.githubusercontent.com/3306138/75685557-b43e6980-5cd5-11ea-9625-fcee54c8301b.gif)

**What did you expect to happen?**
The width of the main container should not be affected by a code fence with a line longer than the content wrapper width, and the page nav should not go "out of the page" due to this

**Comment by nbriannl** [comment]
Preliminary examination:
Bug appears on some pages and not on others.
https://deploy-preview-1075--markbind-master.netlify.com/userguide/usingplugins
https://deploy-preview-1075--markbind-master.netlify.com/userguide/usingcomponents

**Comment by acjh** [comment]
The difference is that:
- `usingplugins` has only 1 code block that overflows, while
- `usingcomponents` has more than 1 code block that overflows.

The fix is to define a `min-width` for `#content-wrapper` so that `flex: 1` can shrink correctly.
Let's add `min-width: 0`. We can remove `width: 100%`, which is ignored since we use `flex`.

https://github.com/MarkBind/markbind/blob/3a4177373ea41f8ad66ffa7f70266d3c8d0c37b7/asset/css/markbind.css#L142-L150
