### ISSUE TITLE
Support a tag to identify markdown text

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#109]
See discussion [here](https://github.com/MarkBind/markbind/issues/53#issuecomment-300356995)

**Comment by rachx** [comment]
Hi Prof Damith,
In lecture and in the documentation, it is mentioned that we need an extra new line between html and markdown for markdown to be rendered properly.
E.g.
```
<div id="def-client-code">

**Client component/method/object**: The component/method/object that is interacting with a given code.

</div>
```

After looking at the code and testing, I realized it will work if we just use
```
<div id="def-client-code">
<markdown> **Client component/method/object**: The component/method/object that is interacting with a given code. </markdown>
</div>
```

**Comment by damithc** [comment]
I didn't realize it already exists :-p Thanks for finding it out @rachx 
1. We need to document it if it is not mentioned already in user docs.
2.  The output still adds a blank line (paragraph break?). Ideally, I would like to be able to write code like this and get the output without a line break after `some text`.
```
some text <span id="def-client-code"><markdown>**Client component/method/object**: The component/method/object that is interacting with a given code. 
</markdown></span>
```
3. @danielbrzn May be this tag can be used to solve the angle bracket problem in an easier way? i.e., if we ask users to wrap offending code inside `<markdown>` tags

**Comment by danielbrzn** [comment]
Seems like number 2 may be caused somewhere in the rendering process. Trying out that piece of HTML on markdown-it yields the intended result. 

![image](https://user-images.githubusercontent.com/251231/35426479-66facd00-029e-11e8-8f1f-17574b075e5f.png)

I tried wrapping the angle bracket in markdown tags but it still has the same problem of htmlparser2 treating <y as a valid open tag.

![image](https://user-images.githubusercontent.com/251231/35426525-a7700260-029e-11e8-8b75-781a206c293f.png)

Would it be perhaps more ideal to treat anything within markdown tags (inside htmlparser2) as text rather than just backticks? It seems more robust in my opinion.

**Comment by acjh** [comment]
> Would it be perhaps more ideal to treat anything within markdown tags (inside htmlparser2) as text rather than just backticks? It seems more robust in my opinion.

Hmm, the author should still be able to use HTML-in-Markdown but not in inline code (backticks).

As a guide, we can consider whatever we enter in the GitHub comment box to be in `<markdown>`.

**Comment by damithc** [comment]
Added a new issue #132 for items 1 and 2
