### ISSUE TITLE
code blocks: support inline markdown for heading

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1119]
Current: `{heading="Heading title"}`
Suggested: support cases such as `{heading="**Heading** title"}`

Not sure what the cost is, but if it is not too high, it's nice to support inline markdown formatting as we support it in other places.

**Comment by nbriannl** [comment]
Cost is just a one line change, can support almost everything except for C
- inline code text style (because it would break markdown-it attrs)
- Dim does not really work.
- lists, paragraphs, footnotes, embeds

Preview all possible inline-markdown here.
https://nbriannl.github.io/markbind-plain-site/

**Comment by damithc** [comment]
Seems good enough. Can go ahead.
