### ISSUE TITLE
Hide line numbers if no language specified?

### ISSUE THREAD

**Issue by openorclose** [MarkBind/markbind#1157]
All code blocks show line numbers by default.

To hide them, add the class `no-line-numbers`:

![image](https://user-images.githubusercontent.com/3646725/77838425-72a2c080-71a6-11ea-8e51-d993f0f5be8d.png)

It seems like no language is specified, line numbers are unwanted (like the example syntax on top).

**Should we make no line numbers the default for such code blocks with no language specified?**

Pros:
- Probably what the author intends

Cons:
- potentially confusing syntax (we would need a `show-line-numbers` and `no-line-numbers` toggle to differ from the 2 defaults)

**Comment by nbriannl** [comment]
Personally, I think that way is quite confusing because now we would have two different attributes that only works conditionally.

- No language specified
  - `show-line-numbers` works but `no-line-numbers` doesn't
- Language specified
  - `no-line-numbers` works but `show-line-numbers` doesn't 

Better to just leave line numbers by defaults and force to toggle it off. Inconvenient to the single use case (of having a code block without language specified for syntax highlighting), but generally more clearer.

**Comment by damithc** [comment]
> Better to just leave line numbers by defaults and force users to toggle it off. Inconvenient to the single use case (of having a code block without language specified for syntax highlighting), but generally more clearer.

It's a _single_ use case but given that there are only two use cases (i.e., code, and non-code), it could be about 30% of the cases as we often show code and output together. The difference is the author not even having to know about these line number annotations (because 'it just works') vs having to add an annotation 30% of the time. But this argument depends on the assumption that the authors almost always want to show line numbers for code blocks and almost always don't want to show line numbers for output, which may not be the case.

**Comment by nbriannl** [comment]
I see. Similarly, hiding numbers when no language is specified, which is what this issue is suggesting, relies on the assumption that "most authors who do not specify language do not want line numbers.". 

Actually, if you look at master, we do specify a language for the example syntax code blocks in some User Guide pages. For example `markdown` is specified in the examples for `blockquotes.mbdf`(in fact, for almost all Markbind syntax, except for code blocks) and `html` is specified in the examples for `boxes.mbdf` (in fact, for almost all components)

In my ongoing PR, I thought of standardizing all the **Code** examples to have no line numbers. Despite that, I still want line highlighting of the respective languages.

**Comment by tlylt** [comment]
Currently, line numbers are disabled by default. A user is also able to choose to enable/disable it over the entire site easily.
> https://markbind-master.netlify.app/userguide/formattingcontents#line-numbering

Given the latest update, perhaps this issue is no longer relevant until:
- the existing mechanism is proven to still be lacking in terms of convenience/usability
- the assumption that having a code block without language specified for syntax highlighting => show no line numbers have been shown to be true to a large extent

Perhaps we can either close this issue or change the label to OnHold/Wontfix

**Comment by damithc** [comment]
Yes, we can put on hold for now, and close after a while later if no longer relevant.

**Comment by tlylt** [comment]
Closing it for now (can be reopened if relevant in the future)
