### ISSUE TITLE
Remove duplicate codes in syntax documentation

### ISSUE THREAD

**Issue by le0tan** [MarkBind/markbind#1159]
**Is your request related to a problem?**

Currently we need to write two parts for syntax documentation: "code" and "output". However this duplication should've been avoided.

**Describe the solution you'd like**

Refactor `outputBox.md` to render both the code box and output box using one input variable.

**Comment by nbriannl** [comment]
I'm interested in doing this. 👀

**Comment by le0tan** [comment]
> I'm interested in taking this issue. 👀

👍 it's a bit more tricky than I imagined though =)

**Comment by nbriannl** [comment]
> 👍 it's a bit more tricky than I imagined though =)

💀 Yeah.

**Comment by damithc** [comment]
> Currently we need to write two parts for syntax documentation: "code" and "output". However this duplication should've been avoided.

Can give an example?

**Comment by nbriannl** [comment]
For example, when explaining syntax coloring in our user guide, we have

`````
<include src="outputBox.md" boilerplate >
<span id="code">

```` {.no-line-numbers}
```xml
<foo>
  <bar type="name">goo</bar>
</foo>
```
````
</span>
<span id="output">

```xml
<foo>
  <bar type="name">goo</bar>
</foo>
```
</span>
</include>
`````

We noted that
``````
```xml
<foo>
  <bar type="name">goo</bar>
</foo>
```
``````
is repeated twice.

What we suggest, is a way to just declare it once, and let the boilerplate `outputBox.md` render it once as "code", and another time as "output".

However, the solution wasn't as straightforward as thought, hence raising #1162

**Comment by damithc** [comment]
I see. Also, this is limited to fenced code block feature only, right? Because other features do not output code.

**Comment by nbriannl** [comment]
This would be related to all features in https://markbind.org/userGuide/formattingContents.html
and https://markbind.org/userGuide/usingComponents.html

**Comment by damithc** [comment]
> This would be related to all features in https://markbind.org/userGuide/formattingContents.html
> and https://markbind.org/userGuide/usingComponents.html

Got it.

**Comment by nbriannl** [comment]
Hi @damithc, would like your input, I started a [PR](https://github.com/MarkBind/markbind/pull/1168/files) that shortens the code for documenting markbind syntax (and the corresponding output example) from

This
``````
<include src="outputBox.md" boilerplate >
<span id="code">

```markdown
### Heading level 3
###### Heading level 6
```
</span>
<span id="output">

### Heading level 3
...
###### Heading level 6
</span>
</include>
``````

To this
``````
<include src="codeAndOutput.md" boilerplate >
<variable name="code">### Heading level 3
...
###### Heading level 6</variable>
</include>
</span>
``````

However, due to the current, and expected, behavior of our code, i.e. `extractPageVariables`, we require the `<variable>` tag to be on the same line as the first line, as well as `</variable>` tag to be on the same line of the last, as seen in `<variable name="code">### Heading level 3` and `###### Heading level 6</variable>`. (See #1162)

On one hand, we have shorter documentation, but on the other hand this syntax does not meet [CommonMark spec](https://commonmark.org/). 

I could tweak the function to deal with subtle new lines and process accordingly, meeting the specs, but I think doing do might break functionality of other pages that use page variables.

What is your opinion?

**Comment by damithc** [comment]
Would this work? `{{ code | trim }}` i.e., have the additional line break in the variable definition but trim it at the point of use.

**Comment by nbriannl** [comment]
Yes it works. Thank you, today I learned about using `trim`.
