### ISSUE TITLE
JSON variables: elaborate on scoping

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1202]
The following statement appears in the [user guide](https://markbind.org/userGuide/reusingContents.html#defining-variables-with-json).
>Variables defined in JSON file will be scoped according to where it is being referenced.

Suggestion: explain this further, possibly with examples.

**Comment by damithc** [comment]
@crphang any more info about this _scoping_?

**Comment by crphang** [comment]
To make it more concrete to an author, it could be reworded as:

```
Variables defined in JSON file will be accessible as page or global variable according to where it was defined.
```

**Comment by damithc** [comment]
Probably we need to give examples of various use cases. I'm not clear about it myself. Can we put those json files in any folder insider the site? Do they have to be all included in the variables.md can they be be included into any page?

**Comment by crphang** [comment]
Yes, examples will help to explain better. To quickly answer some doubts:

1. They could be added in any page in any directory as long as it is referenced appropriately.
2. If the json variables are referenced as part of variables.md, then it would be global. Otherwise if they are defined and referenced from any other page, it would be a page variable.
