### ISSUE TITLE
siteNav: no padding on the left

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1241]
The siteNav seems to have lost the left padding after a recent change. Comparison between v2.14.1 vs latest master 6fd40815f89bbad7fc09955e22e4715921ef36ba

![image](https://user-images.githubusercontent.com/1673303/84362184-6b188280-abff-11ea-97e2-8ca403b221eb.png)

**Comment by ang-zeyu** [comment]
this was intentional actually, I figured it'd be easier for an author to insert padding through `&nbsp;` or bootstrap classes or `style=...` than insert _negative_ padding if the author wants the contrary, hence the extra `padding-left` in the user guide.

I could add negative padding to the things inside `<navigation>` instead though; wonder which would be better 😮

**Comment by damithc** [comment]
I think it's best to have some reasonable level of padding by default. No-padding-needed is a rare case given the content is always a sitNav menu.
But yes, can be added for the `<navigation>` instead.
