### ISSUE TITLE
SiteNav: formatting difference for linked and unlinked items

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1249]
Version: current master

![image](https://user-images.githubusercontent.com/1673303/84589463-30158980-ae61-11ea-8d12-363fdb2c1df5.png)

See above. One item is linked to a page while the other is not (it serves as a section heading). Can they be formatted the same way? At least indentation and font weight?

**Comment by ang-zeyu** [comment]
Is this the same code used in #1246? The netlify preview looks fine

**Comment by damithc** [comment]
> Is this the same code used in #1246? The netlify preview looks fine

No, it's from RepoSense. The difference is that item is not hyperlinked.
https://raw.githubusercontent.com/reposense/RepoSense/master/docs/_markbind/navigation/dgSiteNav.md

**Comment by ang-zeyu** [comment]
In doing https://github.com/MarkBind/markbind/pull/1222#issuecomment-642676679 I removed all formatting in order to let `<hr>`s span the entire width of the site nav, resulting in the indentation changes.

![Untitled](https://user-images.githubusercontent.com/3306138/84589937-e038c180-ae64-11ea-9205-07074ee9e00a.png)
(note the beginning of `hr` would be the same as "Design", it follows at deeper list levels)

I could reintroduce the font-weight formatting though, what do you think?

**Comment by damithc** [comment]
> (note the beginning of `hr` would be the same as "Design", it follows at deeper list levels)
> 
> I could reintroduce the font-weight formatting though, what do you think?

I can live with what's shown in your screenshot. If `<hr>` is used, it's likely to be at the highest level and a bit of indentation might not be such a bad thing. In fact, it's nicer if the `<hr>` doesn't touch the right-edge either. A divider doesn't need to be edge-to-edge.
