### ISSUE TITLE
Dot in variable names cause problem inside <frontmatter>

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1258]
See build error https://travis-ci.org/github/reposense/RepoSense/jobs/700289052

Caused by this code: 
```html
<variable name="title">`run.sh` format</variable>
<frontmatter>
  title: "{{ title }}"
</frontmatter>
```

Specifically, it's the `.` in `run.sh` that's causing the problem. `@` is similarly problematic but not `:`.
This problem is present in v2.14.1 but no longer present in the current master.

Sharing here in case it is useful.

**Comment by damithc** [comment]
@ang-zeyu do you know who this got fixed?

**Comment by ang-zeyu** [comment]
not sure, wasn't even aware of this.
the logs seem to indicate that the content was "cut off" abruptly by a newline though

```
title: "Using 
, position=18, line=2, column=0, stack=YAMLException: unexpected end of the stream within a double quoted scalar at line 3, column 1:
```

not sure how a `.` or `@` translates to that

let's leave this open and document it in code if someone figures it out 😃

**Comment by damithc** [comment]
A git bisect tells me this is the commit that fixed it d6a00b080d6c446c4b1b1fd067ddd42efd3d9781

**Comment by ang-zeyu** [comment]
Seems to be due to the `>` character indicating a yaml block, removing/adding a `@` or `.` didn't work for me

https://yaml-multiline.info/

The previous implementation rendered the variables as inline markdown into `<code>...</code> ...` before storing the variables, which isn't necessary as we do a full pass later on.

shouldn't be necessary to document in code since it was a removal =X

**Comment by damithc** [comment]
> Seems to be due to the `>` character indicating a yaml block, removing/adding a `@` or `.` didn't work for me

I forgot to mention that it only worked when I removed _both_ back-tick and the dot. Removing the back-tick wasn't enough. I assumed dot was the problem as it was the last thing I removed but it's possible that back-tick is problematic too.

**Comment by ang-zeyu** [comment]
> I forgot to mention that it only worked when I removed _both_ back-tick and the dot. Removing the back-tick wasn't enough. I assumed dot was the problem as it was the last thing I removed but it's possible that back-tick is problematic too.

Noticed I removed the `.` from the backticks which caused it to be treated as `<code>` still, which is why it didn't cause:

- `run.sh` would turn into `<a href="http://run.sh">run.sh</a>` which contains `>` otherwise
- `@` together with `.` does cause it to be treated as an email anchor which contains `>` as well (`@` dosen't cause issues alone for me though)

We should probably add a note to the ug that the frontmatter follows yaml spec
