### ISSUE TITLE
Minimal panels: don't dim the heading

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1273]
Current: 
![image](https://user-images.githubusercontent.com/1673303/87282611-0797b280-c527-11ea-8793-79598731ff22.png)

Suggestion: Do not dim the heading, as the user can always use `%%` to dim the heading if so desired.

**Comment by ryoarmanda** [comment]
@damithc The way the minimal panels are designed is that it is dimmed by default (opacity 0.5), but when we hover on it, it transitions into "full" (opacity 1.0) color. If we change the default heading styling to not be dimmed, we could just remove the opacity 0.5 styling, which makes the transition essentially redundant and can be removed for conciseness. However, I am not sure whether we should keep our current "dim to full" behavior when the user specifies dim headings.

If we want to keep the transition, we have to let the Vue component know whether to put opacity 0.5 on the heading or not. As the control for the dim is on the Vue component rather than user-defined, then users might need to specify extra attribute to enable dim headings (maybe like `<panel type="minimal" dim>` instead of using `%%`  at the header.

**Comment by damithc** [comment]
> @damithc The way the minimal panels are designed is that it is dimmed by default (opacity 0.5), but when we hover on it, it transitions into "full" (opacity 1.0) color. If we change the default heading styling to not be dimmed, we could just remove the opacity 0.5 styling, which makes the transition essentially redundant and can be removed for conciseness. However, I am not sure whether we should keep our current "dim to full" behavior when the user explicitly specifies dim headings.

@ryoarmanda We can try removing the dim-to-full transition entirely (even if when `%%` is in use) and see if that affects the user experience?

**Comment by ryoarmanda** [comment]
Okay, I will adopt this approach first, and see how the experience would be affected :+1:
