### ISSUE TITLE
Code highlighting: don't highlighting leading/trailing empty space

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1311]
Current:
![image](https://user-images.githubusercontent.com/1673303/89124084-d4818700-d506-11ea-942a-a25c2a68e217.png)

Problem: The block-wide highlighted box interferes with the visual structure of the code (as driven by indentations).

I wonder if we can/should omit the highlighting from the leading/trailing empty area, like so:
![image](https://user-images.githubusercontent.com/1673303/89124144-3b9f3b80-d507-11ea-889b-4111510d01b8.png)

**Comment by ang-zeyu** [comment]
likely possible, but I think it may look awkward if you highlight multiple consecutive lines. 🤔 
e.g. if you highlight `system.out.println` above as well you'd have a "ladder" background highlight pattern

**Comment by damithc** [comment]
> e.g. if you highlight `system.out.println` above as well you'd have a "ladder" background highlight pattern

Probably should be OK. That's how we usually highlight text. Ideally, we should make it configurable. Possibly related to our other ambition to allow highlighting only certain words e.g., `highlight-lines="2[5:10]"` to highlight characters 5-10 in line 2, `2[:]` to highlight all text, and `2`  to highlight the full-width.

**Comment by ryoarmanda** [comment]
Hi, I'm currently working this issue and unfortunately I'm stuck on how to be able to highlight part of the line (the `"2[5:10]"` case). The problem is, at the time when the highlighting is about to be added, the code in question is already marked up by `highlight.js`. It's not the "raw" text anymore.

Consider this code fence, which will highlight the second line:
~~~
```js {highlight-lines="2"}
function f(x) {
  return x * x;
}
```
~~~

During highlight processing, the line in question already looks like this just before the highlight is added (I added a log for the `line` variable at `core/src/lib/markdown-it/index.js`, line 127):

![image](https://user-images.githubusercontent.com/24468110/91474377-b708c880-e8cc-11ea-9afd-e3aa7a555a74.png)

The current approach (highlighting the whole line) simply just wraps a highlight `<span>` around the marked up line, but as we're trying to highlight just a part of it, it becomes hard to determine where to definitively put the highlight `<span>`. Say I want to highlight just a part of line 2, then depending on the start and end of the highlight, the `<span>` can be outside the `<span class="hljs-keyword">`, within it, or going over it. And there might be a possibility for nested `hljs` spans, which then creates another complication.

With this in mind, I'm not sure whether I can do highlighting a specific part of the line like the `"2[5:10]"` case. But, I'm currently thinking of other ideas as well to make it possible. Do you have any advice regarding this?

Meanwhile, I'll try implementing the `2[:]` case. I think it's more straightforward than the specific range one.

**Comment by ang-zeyu** [comment]
a sure solution would be to reparse the hljs output and then manipulate it. But its _likely_ going to be far too complex and heavy to be worth it for a minor use case. (or better yet just do it in `componentParser`)

I came across this https://github.com/highlightjs/highlight.js/issues/2064 in a quick search, maybe you could investigate if its possible to get `highlightBlock` to work with the pseudo dom output from htmlparser.

But just implementing the original part of this issue is sufficient to me as well : )
