### ISSUE TITLE
Invalid Contribution Guide link in README.md

### ISSUE THREAD

**Issue by KendrickAng** [MarkBind/markbind#1316]
**Tell us about your environment**
Windows 10

* **MarkBind Version:** ---

**What did you do? Please include the actual source code causing the issue.**
I tried to see the contribution guide through README.md's link

**What did you expect to happen?**
To be redirected to the contribution guide

**What actually happened? Please include the actual, raw output.**
A 404 not found page was displayed instead

**Comment by ang-zeyu** [comment]
Thanks for the report @KendrickAng! Also note that the dev guide also currently displays weirdly due to not updating the travis dev guide deploy script to match netlify's after https://github.com/MarkBind/markbind/pull/1265. (will fix shortly)

For the above though, was the removal of `contributing.md` / `code-of-conduct.md` in #1246 intentional? @damithc

**Comment by damithc** [comment]
> For the above though, was the removal of `contributing.md` / `code-of-conduct.md` in #1246 intentional? @damithc

Yes. Should point to https://se-education.org/guides/guidelines/codeOfConduct.html instead.

**Comment by ang-zeyu** [comment]
I went with redirecting the link to the dg landing page instead, as that's where the link you provided is linked from.

I took a look through https://se-education.org/guides/guidelines/ though, and couldn't really find some of the details that were previously in `contributing.md` though. Would these be added sometime later?

e.g. this section, which is pretty useful

```
All contributions are welcome. You can contribute to MarkBind by:	
- Reporting bugs	
- Requesting features	
- Making changes (with a corresponding Pull Request), by:	
   - Updating documentation	
   - Fixing bugs	
   - Implementing features 
```

**Comment by damithc** [comment]
https://se-education.org/guides/guidelines/codeOfConduct.html is a boilerplate code of conduct.



> e.g. this section, which is pretty useful
> 
> ```
> All contributions are welcome. You can contribute to MarkBind by:	
> - Reporting bugs	
> - Requesting features	
> - Making changes (with a corresponding Pull Request), by:	
>    - Updating documentation	
>    - Fixing bugs	
>    - Implementing features 
> ```

It would be good to add a general version of this to se-edu so that all our projects can refer to it and only need to mention any additional project-specific details. I don't think I'll have time to do that anytime soon though.

**Comment by ang-zeyu** [comment]
ok thanks @damithc! its not a high priority thing in any case
