### ISSUE TITLE
Stop adding a line break for output when rendering <markdown> content

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#132]
For example, this,
`some text <span id="def-client-code"><markdown>**bold** other text 
</markdown></span>`

should render as,

>some text **bold** other text 

and not like this:

>some text
>**bold** other text  

Also document the use of  `<markdown>` tag in the user guide.

**Comment by danielbrzn** [comment]
This is caused by the content within markdown tags being rendered as block elements. It is possible to fix this by changing from using the `render` method in `markdown-it` to the `renderInline` method. However, this causes anything within markdown tags to be rendered inline, and as such headers using markdown syntax does not work as intended. 

Would a good compromise be as follows?

- <markdown> can be used for rendering markdown as block elements
- <md> shorthand tag can be used for rendering markdown as in-line elements

This is proposed as the markdown tag is currently used by our parser to indicate the parts of the HTML files that have to be rendered as markdown.

**Comment by damithc** [comment]
> Would a good compromise be as follows?
> 
> `<markdown>` can be used for rendering markdown as block elements
> `<md>` shorthand tag can be used for rendering markdown as in-line elements

yes, that should be fine too.
