### ISSUE TITLE
Move all CI / CD to github actions

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1386]
There is a change to Travis pricing model https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
We should explore alternatives e.g., GitHub Actions

**Comment by ang-zeyu** [comment]
Remaining:
- appveyor
- docs deployment (see travis.yml)

**Comment by tlylt** [comment]
> Remaining:
> 
> * appveyor

Currently we run tests on every PR via Appveyor and Github Actions, do you mean we should remove the Appveyor check since Github Actions script now runs the test as well.
![image](https://user-images.githubusercontent.com/41845017/153100067-c680d1e0-4018-4b02-9133-874079ced66c.png)

If that's the case, I guess the course of action:
- [ ] remove [appveyor.yml](https://github.com/MarkBind/markbind/blob/master/appveyor.yml) in root directory
- [ ] terminate the CI on Appveyor platform

**Comment by jonahtanjz** [comment]
> Currently we run tests on every PR via Appveyor and Github Actions, do you mean we should remove the Appveyor check since Github Actions script now runs the test as well.

@tlylt I believe they are running the same tests but the difference is that Appveyor is running the tests on a Windows environment and the current Github Actions is using an Ubuntu environment. Since Github Actions also supports Windows environment, we should also include the Windows environment tests on our Github Actions and remove the one on Appveyor.

**Comment by tlylt** [comment]
> Since Github Actions also supports Windows environment, we should also include the > > Windows environment tests on our Github Actions and remove the one on Appveyor.

Yup sure, I have updated the tasks in my above comment, I think in the same vein we should take this opportunity to cover macOS as well for running the tests
