### ISSUE TITLE
PlantUML diagrams cause false-positive invalid intra-link warnings

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1416]
v2.17.0

Steps: Generate the CS2103 website

Problem: 
![image](https://user-images.githubusercontent.com/1673303/101919472-90fdfe80-3c05-11eb-932e-23af093e4e9f.png)

**Comment by ang-zeyu** [comment]
race condition as the image link was being checked instead of the puml source file link, fixed in #1403's restructure

I'll could get a hotfix out (2.7.1), by disabling the link checks for `pic` (so no link checks for these as well); a proper fix would require quite substantial changes

would it be worth it? @damithc 
Could include the inline dark mode fix in #1404 as well

**Comment by damithc** [comment]
> I'll could get a hotfix out (2.7.1), by disabling the link checks for `pic` (so no link checks for these as well); a proper fix would require quite substantial changes
> 
> would it be worth it? @damithc
> Could include the inline dark mode fix in #1404 as well

Go ahead @ang-zeyu :+1:

**Comment by ang-zeyu** [comment]
All done : )

Also included hljs update #1396 which went without a hitch

release notes shortly
