### ISSUE TITLE
TopNav: Drop-downs are not shown when using themes

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1444]
Without a theme:
![image](https://user-images.githubusercontent.com/1673303/104553113-07fb3c80-5675-11eb-9c5a-005081a30f91.png)

With a theme:
![image](https://user-images.githubusercontent.com/1673303/104553131-121d3b00-5675-11eb-909c-38716ad82359.png)

**Comment by raysonkoh** [comment]
I think there was some changes made to bootswatch at this specific [commit](https://github.com/thomaspark/bootswatch/commit/72d5823512113516cc9f6d88d4bb0ed7d8bbfb7f), the relevant changes which I think caused this issue is shown below.

![image](https://user-images.githubusercontent.com/16506539/104711443-59322b80-575c-11eb-9776-f27a4187f5d1.png), 

Upon inspection using the dev tools, I noticed that the same changes were being reflected in the bootstrap.css.

![image](https://user-images.githubusercontent.com/16506539/104711899-e70e1680-575c-11eb-9ef8-d95628702f77.png)

It is showing that the bootswatch version in the released markbind is v4.5.3.

![image](https://user-images.githubusercontent.com/16506539/104712527-9e0a9200-575d-11eb-845c-097070a48e62.png)

We can either downgrade to v4.5.0, before that commit or work on a fix for this. @ang-zeyu any thoughts on this?

**Comment by ang-zeyu** [comment]
thanks for investigating it! @raysonkoh 

since it looks simple and generic, let's fix it 🙂 

fyi: there are a few theme-specific issues (especially with the searchbar) we have decided not to fix previously, as its too much work working on and tracking 15 separate bootswatch themes.
The solution in the long run would be to move to our own style system #903, shifting the burden of customization to the user

But likely something for v4.0 maybe =P
