### ISSUE TITLE
Explore different services for previewing PR

### ISSUE THREAD

**Issue by raysonkoh** [MarkBind/markbind#1466]
**Is your request related to a problem?**
If a PR has updated the docs, such as the userGuide, there is currently no convenient for a PR reviewer to review the changes made unless he/she pulls the PR and reviews the changes locally.

**Describe the solution you'd like**
Some initial work done to evaluate different PR preview services based on cost and ease of setup.

Can reference how Reposense used [Surge](https://surge.sh/) for their deployments in reposense/Reposense#1099

**Describe alternatives you've considered**

None

**Additional context**
I believe that previously, Netlify PR preview was used for Markbind and we stopped using it because it was too expensive. Please correct me if I'm wrong.

**Comment by ang-zeyu** [comment]
@raysonkoh thanks, @yamgent got us on the open source plan a while back ( https://github.com/MarkBind/markbind/pull/956 ) 😄

**Comment by ang-zeyu** [comment]
there's 1000 build minutes per month; it should be more than enough as well since we're only using it for the pr previews (deploys are done with travis - pending switch to gh actions)

**Comment by ang-zeyu** [comment]
I may have jumped the gun a little here though - do let me know if there's anything you're suggesting here that netlify dosen't support currently.

On the same lines there's #1212 which we can explore for visual UI review / testing (though not too sure about the pricing, etc. there)

**Comment by damithc** [comment]
It would be good to provide instructions for _other ways of doing PR previews_, for other potential users of MarkBind? Netlify may not be an option for them due to various reasons. RepoSense is an example. They ran out of free minutes too fast and had to look for an alternative.

**Comment by raysonkoh** [comment]
Some updates on this issue:

After referencing Reposense's configs for doing PR previews with Surge.sh, I am able to come up with a Github-Actions workflow that works for a PR that is sent from **a branch of the same repo**.

I see from the discussions in reposense/Reposense#1105 that there were some concerns when a PR is sent from **a branch of a forked repo**, as Github Actions may not expose the repo secrets. I will investigate this further.

Side note: [Surge also supports deploying to a custom domain](https://surge.sh/help/adding-a-custom-domain). Should we explore this as a possible method of deploying a Markbind site? 

Some alternative services that I have found that may support PR Previews (need to do more research into whether they actually work with Markbind):
- [AWS Amplify](https://aws.amazon.com/amplify/)
- [Heroku Review App](https://devcenter.heroku.com/articles/github-integration-review-apps)
- [Gitlab Review App](https://docs.gitlab.com/ee/ci/review_apps/)

**Comment by damithc** [comment]
Good progress @raysonkoh 

> Side note: [Surge also supports deploying to a custom domain](https://surge.sh/help/adding-a-custom-domain). Should we explore this as a possible method of deploying a Markbind site?

GitHub pages can do that as well. So, I think we can let the platform handle that part i.e., if the user want to deploy to a custom domain, they can refer to the documentation provided by the platform

**Comment by ang-zeyu** [comment]
For reference, the usage as of 24th feb for this month

![Untitled](https://user-images.githubusercontent.com/3306138/108982506-d8564000-76c8-11eb-90bc-7736234b7c9a.png)

We're really no where near exceeding the limit. Reposense has a relatively long ~10min ci deploy run due to its tool chain (ours just takes about ~1min 30s)

**Comment by raysonkoh** [comment]
Some updates while I was exploring using Heroku for PR previews / deployment:
In terms of deploying a Markbind site via Heroku, it may not be very feasible. On a free heroku account, there are a limited number of minutes per month which the website can be actively serving users (at most 1000 hours). Also the website will go to sleep if it has been inactive for more than 30minutes. 

For PR previews, I think it is possible with the use of Heroku review apps, but it is quite restrictive and inconvenient. On a free heroku account, there can be at most 5 apps created (i.e. at most 4 pull requests can have PR previews). Even with a paid account, there is an upper limit of 100 apps created (i.e. at most 99 pull requests can have PR previews). Also, [heroku does not automatically create review apps for pull requests from forks](https://devcenter.heroku.com/articles/github-integration-review-apps#creating-review-apps). So someone with access to the heroku account has to manually create a review app manually every time a PR is sent from a fork, which can be quite inconvenient.

**Comment by damithc** [comment]
Thanks for investigating the Heroku option @raysonkoh 
We can put that on hold for the time being.

**Comment by damithc** [comment]
Increasing the priority a bit because it would be quite useful to have a PR preview mechanism for MarkBind users.

**Comment by tlylt** [comment]
A quick in-progress update.

I intend to simplify the setup required to enable PR Preview with Surge, based on the documentation provided [here](https://markbind.org/userGuide/deployingTheSite.html#previewing-prs-using-surge) by @raysonkoh (Thanks!)

Indeed as mentioned earlier in this thread, due to security concerns, the need to separate 1. the markbind build step from 2. deployment on Surge is somewhat a necessary compromise to ensure that user secrets(Surge token) will not be exposed when actions are triggered from PRs of a forked repo (Even with the PULL_REQUEST_TARGET event, it is still somewhat risky to check out a potentially harmful forked repo).

So given that constraints, I am proposing the following improvements:
There are two kinds of users who might want PR Preview:
1. Users who are doing a branching workflow
	-  i.e. PRs come from the same repo, but different branch. The user could just be the sole owner of the repo, or others who have write access to the repo.
2. Users who are doing a forking workflow
	- i.e PRs can come from the same repo or a forked repo. The PR initiator may not have write access to the repo.

For group 1
1. Create a GitHub Action "markbind-pr-preview" that simplifies the build process
2. The user will simply need to 1. create and setup a SURGE_TOKEN, 2. create a workflow with custom parameters(markbind versions etc). Example below
```yml
on:
  pull_request:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test MarkBind PR Preview Action
    steps:
      - uses: actions/checkout@v2
      - id: markbind-pr-preview
        uses: MarkBind/markbind-pr-preview
        with:
          baseUrl: 'tlylt'
          token: ${{ secrets.SURGE_TOKEN }}
```

This works fine because actions triggered by group 1 users have access to the secrets.

For group 2
1. Create 2 GitHub reusable workflows can be used by the user (similar to GitHub Actions)
2. The user will simply need to 1. create and setup a SURGE_TOKEN, 2. create two workflows with custom parameters(markbind versions, etc). Example below:
(a) fork-build.yml
```yml
name: Build Fork PR

# read-only
# no access to secrets
on:
  pull_request:

jobs:
  build:
    name: Build Fork PR
    uses: tlylt/markbind-reusable-workflows/.github/workflows/fork-build.yml@main
```
(b) fork-preview.yml
```yml
name: Preview Fork PR

on:
  workflow_run:
    workflows: ["Build Fork PR"]
    types:
      - completed

jobs:
  build:
    name: Deploying to surge
    uses: tlylt/markbind-reusable-workflows/.github/workflows/fork-preview.yml@main
    secrets:
      token: ${{ secrets.SURGE_TOKEN }}
```

The steps within the workflow is extracted out into our reusable workflows and hence the 2 workflows that the user needs to create are in fact a lot simpler than what we documented in our UG.

wrt the choice of GitHub Action VS GitHub reusable workflows, I don't think there is a significant difference in our use case. The GitHub Action could be done as a reusable workflow as well. [Reusable workflows](https://github.blog/2021-11-29-github-actions-reusable-workflows-is-generally-available/) are relatively new and there are indeed some limitations if anyone is interested. The choice is up for discussion.

After I have tied up the loose ends, will create a PR to update the UG and get permissions to create these workflows within MarkBind instead of my personal account, for better organization.

**Comment by damithc** [comment]
Dropping this here, in case relevant https://vercel.com/

**Comment by tlylt** [comment]
> Dropping this here, in case relevant [vercel.com](https://vercel.com/)

Vercel does support PR Previews similar to Netlify. I think there's a limitation if the repo is from an organization, then it may not work without creating a team (has a [cost](https://vercel.com/pricing))
![image](https://user-images.githubusercontent.com/41845017/159850673-b9c4a60e-9c6a-4582-95d1-64bc82e2c372.png)

For repos in a personal account, it works fine.
