### ISSUE TITLE
Last dropdown header not processed

### ISSUE THREAD

**Issue by jonahtanjz** [MarkBind/markbind#1472]
**Tell us about your environment**

* **MarkBind Version:** 2.17.0

**What did you do? Please include the actual source code causing the issue.**
Created three dropdowns wrapped in a `div`.

```html
<div>
  <!-- First dropdown -->
  <dropdown header="*Dropdown 1*" type="primary">
    <li><a href="#dropdown" class="dropdown-item">Action</a></li>
  </dropdown>
  <!-- Second dropdown -->
  <dropdown header="Dropdown 2" type="primary" menu-align-right>
    <li><a href="#dropdown" class="dropdown-item">Something else here</a></li>
  </dropdown>
  <!-- Third dropdown -->
  <dropdown header="Dropdown 3" type="primary" menu-align-right>
    <li><a href="#dropdown" class="dropdown-item">Something else here</a></li>
  </dropdown>
</div>
```

I noticed that this issue only occurs when the dropdowns are in a wrapper like `div` or `box`. This issue can be seen on the user guide https://markbind-master.netlify.app/userguide/usingcomponents#dropdowns, where the `Right aligned list` header is missing.

**What did you expect to happen?**
Three dropdowns with their respective header shown
![image](https://user-images.githubusercontent.com/47470981/107372580-8639ea00-6b20-11eb-90e9-e479c1d6bf03.png)

**What actually happened? Please include the actual, raw output.**
However, the last dropdown header is missing. 
![image](https://user-images.githubusercontent.com/47470981/107372354-496df300-6b20-11eb-957f-f630f3e3676c.png)

Upon further inspection, it seems the header attribute for the last dropdown is not processed.
![image](https://user-images.githubusercontent.com/47470981/107372495-70c4c000-6b20-11eb-962a-5ecb8f45e9c5.png)

**Comment by ang-zeyu** [comment]
Thanks for the catch! @jonahtanjz 

Could this be related to #1467? @wxwxwxwx9
The version in markbind.org seems fine

**Comment by wxwxwxwx9** [comment]
@jonahtanjz thanks for highlighting this :-) 

I did some investigation. It doesn't seem like a recent problem. In fact, the change in #1467 unexpectedly alleviated this issue. Like @jonahtanjz mentioned, this issue happens when multiple `<dropdown>` are wrapped in a div or box. From my investigation, it seems like this issue happens when we have more than 2 `<dropdown>` nodes (e.g. if we have 3 nodes and more, the last dropdown node will always be unprocessed, for some reason). 

Before the change in #1467, only the first dropdown node will be processed. But after the change, all the dropdown nodes will be processed except the last one. I'm guessing that by introducing cheerio's sibling operations of .before() or .after() will somehow messes up the processing of the nodes (side effects?). I have confirmed that the problem stems from the use of .before() or .after() but I'm still not entirely sure how it causes the problem. Have to do some deeper investigation and tracing of the processing.

**Comment by ang-zeyu** [comment]
as discussed, let's remove the the dropdown header fouc hotfix completely if a proper solution for is too complex:
- fouc hotfix works just fine without the header (if not better, as the header can contain unrendered markdown)
- we should move toward fixing the root cause of fouc #1406
