### ISSUE TITLE
Special characters not rendered correctly in search results

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1486]
This is from the current UG
![image](https://user-images.githubusercontent.com/1673303/108808694-1cbae080-75e2-11eb-9ab4-52b92fa2fcdb.png)

**Comment by wxwxwxwx9** [comment]
![Screen Shot 2021-02-23 at 2 39 31 PM](https://user-images.githubusercontent.com/37920115/108809959-f34f8400-75e4-11eb-9c71-86751b403189.png)

Just investigated this quickly and it seems like it can be fixed by rendering it as html by using `v-html`. 

![Screen Shot 2021-02-23 at 2 41 24 PM](https://user-images.githubusercontent.com/37920115/108810055-36a9f280-75e5-11eb-9a9e-3c0044ee6d94.png)

But there seems to be some concern about using `v-html` generally. Let me take a deeper look into this potential fix while others chip in :-)

**Comment by wxwxwxwx9** [comment]
@ang-zeyu is the proposed solution alright? If so, do you think we should make a PR to the hotfix branch? :O

**Comment by ang-zeyu** [comment]
how about unescaping what's indexed? (`"include-inside-an-included-file": "&lt;include&gt; Inside an Included File",`)
No need for a `eslint-disable` that way.

> hotfix branch

no need, this isn't game-breaking

**Comment by wxwxwxwx9** [comment]
Hmm just to clarify, do you mean we'll keep a dictionary of what characters are escaped in html and then we will unescape it accordingly?

**Comment by ang-zeyu** [comment]
> how about ~unescaping~ not escaping what's indexed?

sorry, meant ^.

**Comment by wxwxwxwx9** [comment]
Hmm can I check what ideas you have in mind to not escape the indexed characters? Other than `v-html`, I'm not sure what other alternatives there are to not escape what's indexed. It seems like `v-html` is the mainstream way to do it.

**Comment by ang-zeyu** [comment]
> Hmm can I check what ideas you have in mind to not escape the indexed characters? Other than `v-html`, I'm not sure what other alternatives there are to not escape what's indexed. It seems like `v-html` is the mainstream way to do it.

sorry, disregard the earlier again.

I was under the impression cheerio / jquery has a convenient function for outputting unescaped text (so we don't index the `<` as `&lt;`'s here `&lt;include&gt; Inside an Included File`), seems like that isn't the case on closer look. Let's go with `v-html` then
