### ISSUE TITLE
Tab selection "jumpy" render

### ISSUE THREAD

**Issue by wxwxwxwx9** [MarkBind/markbind#1499]
**Tell us about your environment**
MacOS 10.15.4, Google Chrome Version 88.0.4324.182 (Official Build) (x86_64)

* **MarkBind Version:**
v2.17.0

**What did you do? Please include the actual source code causing the issue.**

```html
<tabs>
  <tab header="First tab">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ullamcorper ultrices lobortis.
  </tab>
  <tab header="Second tab">
    Some content of the second tab...
  </tab>
  <tab header="Third tab">
    Additional content from third tab...
  </tab>
  <tab-group header="Example Tab Group">
    <tab header="Tab Group 1">
      Some content in a tab group 1...
    </tab>
    <tab header="Tab Group 2">
      Some content in a tab group 2...
    </tab>
  </tab-group>
</tabs>

<box>

some content here

</box>

```

Suppose we have the above source code, when we actually select among the tabs consecutively, you would observe some "jumpy" rendering that happens intermittently. Not exactly sure what causes that to happen. 

https://user-images.githubusercontent.com/37920115/109919350-79f61680-7cf3-11eb-8ecd-535fa1372939.mov

Although the functionality overall is not affected in anyway, we may want to improve the user experience by fixing this "jumpy" rendering issue. But it's not a priority.

**Comment by jonahtanjz** [comment]
Took a quick look at this since I was working on a PR related to tabs. It seems this is caused by the [`<transition>` wrapper](https://github.com/MarkBind/markbind/blob/master/packages/vue-components/src/Tab.vue#L2) in `Tab.vue`. I'm not sure if the tabs were supposed to have transition effect but I don't think it is working at the moment. I tried removing it and it seems to resolve the "jumpy" render.
