### ISSUE TITLE
markdown-it-attrs not parsing properly in user guide

### ISSUE THREAD

**Issue by wxwxwxwx9** [MarkBind/markbind#1500]
![Screen Shot 2021-03-04 at 4 38 15 PM](https://user-images.githubusercontent.com/37920115/109935064-2510cb00-7d08-11eb-93b7-cdaaeaddce15.png)

As shown in the image above, `markdown-it-attr` is not parsing the `{.alert-info}` properly and it appears as text in the output. It should have been applied as a class on the topmost list. 

The specific example we are looking at is actually adapted from the documentation of `markdown-it-attrs` library. 

![Screen Shot 2021-03-04 at 4 41 37 PM](https://user-images.githubusercontent.com/37920115/109935378-7faa2700-7d08-11eb-844e-d5bd76db1444.png)

I took a look into the issue to find out where the bug occured and it seemed to have came from the V3 baseline implementation. 

<img width="333" alt="Screen Shot 2021-03-04 at 4 43 07 PM" src="https://user-images.githubusercontent.com/37920115/109935577-b54f1000-7d08-11eb-8001-d93b3d4eceea.png">

The last working version that I identified was at the commit "Extend navbar highlighting to standard links and dropdowns". 

I faced some difficulty in narrowing down the scope further as the commits seem to have some interdependence (e.g. commit A requires commit B, reverting to commit A and running markbind will result in errors when serving). 

It will take some time and a bit of effort to isolate the bug and fix it. We probably want to sieve through the commits and look at where the markdown parser was modified. It could also have been due to the [content processing flow changes](https://markbind.org/devdocs/devGuide/design/architecture.html). 

I'll put this issue here first and revisit this when I'm done with other PRs. But feel free to take up this issue if you feel like it :-)

**Comment by ang-zeyu** [comment]
This is spec compliant to some level actually.

It worked before because we did nunjucks -> html (just to process `<include/>`) -> markdown -> html (misc).
So the things inside `<include />` are exceptionally (wouldn't work with any other tag) rendered into the included file before being touched by markdown.

Now it's nunjucks -> markdown -> html recursively which means all tags get the same treatment. It would need an empty line before the `<variable name="code">` tag in the docs for markdown to avoid rendering it, much like things inside `<script/style/pre>` tags (patch / support for that [here](https://github.com/MarkBind/markbind/blob/master/packages/core/src/lib/markdown-it/patches/markdown-it-escape-special-tags.js)).

I missed out quite a few lapses in the docs in that PR though. I fixed a few in https://github.com/MarkBind/markbind/pull/1479 but seems like missed a few more (also one more under the katex section) =\

**Comment by ang-zeyu** [comment]
An simple alternative to this is to also treat `<include>` tags as "special" tags (`<script/pre/style>` according to commonmark) just for the _markdown_ side.

It's also "spec compliant", and would remove the need to pad `<variable>` tags before with an empty line.
