### ISSUE TITLE
Modal content disppearing after reopening

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#1519]
**Tell us about your environment**

* **MarkBind Version:** since https://github.com/MarkBind/markbind/commit/c417d681f3744ad92db6fb21faa0a731d1523eb3

**What did you do? Please include the actual source code causing the issue.**

![slot-disappearing](https://user-images.githubusercontent.com/3306138/112428353-fe2d3e00-8d75-11eb-8d6e-78b3bba73498.gif)

**What did you expect to happen?**

The slot (`Rainbow`) inside the panel should re-render when reopening as well.

**Comment by ang-zeyu** [comment]
@wxwxwxwx9 I missed this out while reviewing. Any idea what's causing this? 🤔

**Comment by wxwxwxwx9** [comment]
@ang-zeyu my bad! I missed out on this as well. This is rather weird. Let me look into this!

**Comment by wxwxwxwx9** [comment]
After investigating, I discovered that the problem lies with our usage of $slots instead of $scopedSlots. 

Using the example that you have provided in the post, it appears that any **named** slots passed into panel would disappear upon the second expansion of the modal. Here's a screenshot of the testing that I've done. 

![Screen Shot 2021-04-03 at 1 23 34 PM](https://user-images.githubusercontent.com/37920115/113469458-2b69a280-9480-11eb-8688-63b86a917a52.png)

As you can see for the first expansion, the named slots `header` and `alt` exist in both `this.$slots` and `this.$scopedSlots`.
However, for the second expansion, the named slots `header` and `alt` disappears from `this.$slots` but still remains in `this.$scopedSlots`. 

So it does seems like we can fix this by using `$scopedSlots` in place of `$slots`, as shown below. 

![Screen Shot 2021-04-03 at 1 24 10 PM](https://user-images.githubusercontent.com/37920115/113469421-e2195300-947f-11eb-8f06-fb3b333690ad.png)

I tried researching around this issue to understand what may cause this problem but I couldn't find a convincing answer. Here are some of what I have looked at:
[Slot wrapped in v-if disappears after re-render #11084](https://github.com/vuejs/vue/issues/11084#issuecomment-582801325)
[template slot content disappears on subsequent visit #2837](https://github.com/vuejs/vue/issues/2837)
[Why Vue regular slots also available in this.$scopedSlots?](https://stackoverflow.com/questions/63756681/why-vue-regular-slots-also-available-in-this-scopedslots)
[Scoped slot always present in $scopedSlots even when v-if'd away #8305](https://github.com/vuejs/vue/issues/8305)
[Vue API -- $slots](https://vuejs.org/v2/api/#vm-slots)

@ang-zeyu It seems to me like the problem stems from Vue's new syntax / new way of doing things (internal implementation) rather than our implementation. What do you think?

**Comment by ang-zeyu** [comment]
Thanks for the thorough investigation! @wxwxwxwx9 

Let's go with `$scopedSlots` then, per your testing.

Also related (let's make a note / open a new issue) - we'd have to change it back then, and hopefully it dosen't break =P.
https://v3.vuejs.org/guide/migration/slots-unification.html
