### ISSUE TITLE
Navbar blocks the target element

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#152]
Example:
1. Go to https://nus-te3201.github.io/website/admin/index.html
2. Click on any of these links
![image](https://user-images.githubusercontent.com/1673303/36472550-2082328e-172d-11e8-96bc-195f3f7b1426.png)

Expected: Scroll to target heading
Actual: Target heading is hidden behind the navbar

**Comment by yunpengn** [comment]
Hi, this is Yunpeng. 

I think this one is a problem with Bootstrap `navbar`. The problem will occur as long as you use a `navbar` fixed at the top. I encountered such problems when I wrote my own projects before as well. See the [discussion](https://github.com/twbs/bootstrap/issues/1768) on Bootstrap's official repo.

I wrote two example HTML files to show the fix. See http://navbar-demo.bitballoon.com/, including a correct one and a wrong one by adding the following javascript
```javascript
window.addEventListener("hashchange", function() { scrollBy(0, -50) })
```
where 50 is the height of the `navbar`.

Tell me if this works and if I can further help.

**Comment by Gisonrg** [comment]
Thanks @yunpengn for sharing your findings 😃 

Since not all site will use fixed navbar, I would suggest:
1. Add the code snippet suggested on a site by site basis, or
2. Add a check in Vue-strap's [NavBar](https://github.com/MarkBind/vue-strap/blob/master/src/Navbar.vue), if fixed navbar is used, we add the suggested listener to the page.

Personally I prefer option 2 as it should be a long term fix.

**Comment by yunpengn** [comment]
I agree with the 2nd approach as well. I tried to do so here https://github.com/yunpengn/vue-strap/commit/ab84fbee60013bea8913cb53c9423317374cffd9

Do you want me to create a PR?

**Comment by Gisonrg** [comment]
Sure, feel free to send a PR and go through the code review process :)
