### ISSUE TITLE
Site-nav: current page indication doesn't work if the link is *.md

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1566]
Current: The link currently loaded is highlighted in the site-nav
![image](https://user-images.githubusercontent.com/1673303/119359256-048b5800-bcdc-11eb-81de-eab1e8305348.png)

Problem: This highlighting works for *.html links but doesn't work if the link is given as a *.md file

**Comment by jonahtanjz** [comment]
It seems like this issue is affecting the current release version. I've tried out the current master branch and the highlighting works for *.md links. I believe this is because the site nav in master branch is now checking whether to add the `current` class after the links have been processed by Markbind (done in vue component of [site nav](https://github.com/MarkBind/markbind/blob/master/packages/vue-components/src/SiteNav.vue#L15)).

**Comment by damithc** [comment]
> I've tried out the current master branch and the highlighting works for *.md links.

Thanks for checking @jonahtanjz Should be fine if fixed already in the master branch. Closing.
