### ISSUE TITLE
Unable to use markbind commands

### ISSUE THREAD

**Issue by jonahtanjz** [MarkBind/markbind#1578]
* **MarkBind Version:** v3.0.1

**What did you do? Please include the actual source code causing the issue.**
After running `npm run setup`, `markbind` commands are not working. This seems to be affecting the development version (Released version seems fine). 

![image](https://user-images.githubusercontent.com/47470981/120917869-22958700-c6e4-11eb-9882-33fdfd03a35c.png)

**Comment by ryoarmanda** [comment]
The trace tells that it's unable to get a module that is one of the dependency of the `live-server` patch. Strange it doesn't work on development as it was just fine when I developed it. Might be a case of dependencies not properly stated. I'll investigate this quickly.

**Comment by ryoarmanda** [comment]
I synced with `master`, run `npm run setup`, and tried to do `markbind init` and `markbind serve -o` and everything seems to be working fine on my end. Can anyone verify?

![image](https://user-images.githubusercontent.com/24468110/120918951-b453c300-c6e9-11eb-81af-39972ee0f710.png)

**Comment by jonahtanjz** [comment]
Thanks for checking this out @ryoarmanda . Hmm strange I tried this out on my other computer as a fresh install and ran into the same issue. Perhaps someone else can check this out?

**Comment by ang-zeyu** [comment]
My bad @ryoarmanda @jonahtanjz, hadn't expected you guys to be testing this quickly.

You'll need to bump your npm versions to v7 for development due to the lock file format changes. Could have a look [here](https://nitayneeman.com/posts/catching-up-with-package-lockfile-changes-in-npm-v7/) you're interested.

Note this dosen't affect the release version (v6 still fine for end users) as the lock file isn't published.

@raysonkoh @wxwxwxwx9 fyi as well
