### ISSUE TITLE
Box components: support applying built-in color schemes

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1581]
v3.0.1

Box components follow a different color scheme based on the type of box. Example:
![image](https://user-images.githubusercontent.com/1673303/121799767-795d0c80-cc60-11eb-9d1c-63ca2015fb14.png)

In some cases, the default color scheme might not go well with the overall style of the page. In the example above, blue/black/grey would fit better with the page.

Perhaps we can let the user override? e.g., `<box type="tip dark" ...`

Yes, we do support fine-grained color changes for boxes but it's easier for the user if s/he can take advantage of predefined styles such as `primary, success, warning etc.` more easily.

**Comment by kimberlyohq** [comment]
Hi Prof, I would like to try working on this for my first issue. 
Other than supporting the **dark** predefined style, are the other styles supported `primary` and `light` to follow the behaviour of `navbar`?

**Comment by damithc** [comment]
@kimberlyohq I was thinking of these bootstrap color schemes 
* primary
* secondary
* warning
* info
* success
* danger
* light
* dark

https://getbootstrap.com/docs/4.0/utilities/colors/

**Comment by kimberlyohq** [comment]
Ah ok, I misunderstood, i thought it was meant to match the themes. Thanks for clarifying! I would like to work on this issue if possible😊

**Comment by damithc** [comment]
@MarkBind/active-devs is this suitable as a first-timer issue? Also, is the feature suitable for implementation, cost-benefit wise?

**Comment by wxwxwxwx9** [comment]
I think this is a good first-timer issue. Just to get a more senior opinion, @ang-zeyu what do you think?

**Comment by ang-zeyu** [comment]
@damithc 
Maybe we could keep all the current icon mappings then support this with a separate `color-type="... bootstrap colors ..."` attribute of sorts?

A "compound" `type="tip dark"` attribute would be more convenient but would conflict against the `info / success / warning` 
colors. E.g. for `type="success definition`", its ambiguous as to which icon (tick / book) or alert background (green / blue) color to show.

Bootstrap colors for reference: https://getbootstrap.com/docs/4.0/utilities/colors/, of note:

- There's already a few conflicting attributes: `info / success / warning` (to be supported again via `color-type`)
- And then a whole bunch we don't have currently: `danger / primary / secondary / light  / dark` (to be supported via `color-type`)
- And then our icon ones: `important / wrong / tip / definition` that also imply `color-type` if unspecified

@kimberlyohq 
I think this is good for a first timer issue once we've settled on the specs here. Your input is welcome too.
https://github.com/MarkBind/markbind/issues/1558 is a good alternative if you want to get started on something right away though.

Also note we currently don't have `light / dark` alert backgrounds used so that can come in a later follow up as well (`color-type` for just the existing alert colors would be fine first). As its likely going to take quite a bit of work integrating these with `light` + `seamless` types.

**Comment by damithc** [comment]
> Maybe we could keep all the current icon mappings then support this with a separate `color-type="... bootstrap colors ..."` attribute of sorts?

Yes, I'm OK with using a separate attribute too. `theme="..."`?

**Comment by ang-zeyu** [comment]
>theme
sounds good 👍

**Comment by kimberlyohq** [comment]
theme sounds good and would be clearer.

@ang-zeyu Thank you. I will look into #1558
