### ISSUE TITLE
Live preview shows spinner instead of new content

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1583]
v3.0.1

When I change the content of a page, the live preview triggers a refresh but the spinner doesn't goes away. The new content appears only after I do a manual refresh.
The same applies when I click on a link in the previewed page. The browser goes to the new page, but get stuck at the spinner. It shows the content only after a manual refresh of the page.

I was using `markbind serve -o` but I don't think the flag matters. I think it depends on the site size though. Didn't notice it in smaller sites but happens in big sites such as the se-book.

**Comment by ang-zeyu** [comment]
> When I change the content of a page, the live preview triggers a refresh but the spinner doesn't goes away.

I've never actually experienced this (stuck at spinner) so far, but have a couple of times the long standing issue with needing a manual refresh (but not with a spinner page).

My guess is that `live-server`'s file watching is debounced in some way by the os. (as I observed this most notably when making repeated successive changes and saves to source files).


We might explore plucking over (removing `live-server` as a dependency) entirely and using our own implementation that uses websockets (instead of filesystem events) to request manual refresh of pages (under the hood this is what `live-server` is doing anyway). This also seems like a natural solution to the second item here https://github.com/MarkBind/markbind/pull/1534#issuecomment-827530954.



@ryoarmanda / @wxwxwxwx9 could you take a shot at this when you have the time? 🙇

**Comment by ang-zeyu** [comment]
> My guess is that live-server's file watching is debounced in some way by the os. (as I observed this most notably when making repeated successive changes and saves to source files).

I fiddled around with your site a little more, and realised this is not the same problem. (although I think its still something we should do eventually)

For now the new `markbind s -o` features are simply missing baseUrl handling logic. @ryoarmanda -- if you have the time to fix this 🙇 

As a workaround you can temporarily remove the baseUrl during development.

**Comment by damithc** [comment]
> As a workaround you can temporarily remove the baseUrl during development.

Yup, that works. Thanks for the workaround @ang-zeyu

**Comment by ryoarmanda** [comment]
> For now the new `markbind s -o` features are simply missing baseUrl handling logic. @ryoarmanda -- if you have the time to fix this 🙇

Alright, I'm on it :+1:

**Comment by wxwxwxwx9** [comment]
> > When I change the content of a page, the live preview triggers a refresh but the spinner doesn't goes away.
> 
> I've never actually experienced this (stuck at spinner) so far, but have a couple of times the long standing issue with needing a manual refresh (but not with a spinner page).
> 
> My guess is that `live-server`'s file watching is debounced in some way by the os. (as I observed this most notably when making repeated successive changes and saves to source files).
> 
> We might explore plucking over (removing `live-server` as a dependency) entirely and using our own implementation that uses websockets (instead of filesystem events) to request manual refresh of pages (under the hood this is what `live-server` is doing anyway). This also seems like a natural solution to the second item here [#1534 (comment)](https://github.com/MarkBind/markbind/pull/1534#issuecomment-827530954).
> 
> @ryoarmanda / @wxwxwxwx9 could you take a shot at this when you have the time? 🙇

Got it! Will try to explore how we can implement our inhouse version :-)

**Comment by damithc** [comment]
BTW, any of you able to reproduce this problem or is it just me?
