### ISSUE TITLE
Collapsed page-nav covers content

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1590]
V2 behavior:
![image](https://user-images.githubusercontent.com/1673303/122249198-39658600-cefb-11eb-86dc-2b5acb41aca2.png)

V3 behavior:
![image](https://user-images.githubusercontent.com/1673303/122249055-1e931180-cefb-11eb-96fd-46c9d2cc52f0.png)

**Comment by jonahtanjz** [comment]
Thanks for bringing this up Prof @damithc. The fixed header padding is dynamically adjusted by accessing the `cssRules` property of individual stylesheet. But due to [Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) security, the `cssRules` is not accessible if the stylesheet is imported from a different domain (external stylesheet etc.), causing the function to fail. I will raise a PR to fix this.
