### ISSUE TITLE
User Guide: Unable to open details panel on mobile

### ISSUE THREAD

**Issue by samuelfangjw** [MarkBind/markbind#1601]
**Tell us about your environment**
Safari, iOS.

**What did you do? Please include the actual source code causing the issue.**
<img width="30%" src="https://user-images.githubusercontent.com/60355570/123526331-b669da00-d709-11eb-8d72-0e208f54b299.PNG" alt="IMG_2596"></img>

On the Nav Bar section at https://markbind.org/userGuide/readerFacingFeatures.html, I am unable to expand the details panel (circled in red). I am able to open other details panels on the same page without any issues.

**Comment by jonahtanjz** [comment]
Thanks for the catch @samuelfangjw. Seems like this is caused by [`.card-container::before`](https://github.com/MarkBind/markbind/blob/master/packages/core-web/src/index.js#L52) of the next panel blocking the details panel in the mobile version.

![image](https://user-images.githubusercontent.com/47470981/123533002-9277ba00-d744-11eb-8b88-dc2510a00e8a.png)

@ang-zeyu Can I check why was [this]((https://github.com/MarkBind/markbind/blob/master/packages/core-web/src/index.js#L52)) part needed? I tried removing it and it seems to resolve the above issue and it does not cause any spacing issues with the panels. I may have missed some edge cases which would require this?

**Comment by ang-zeyu** [comment]
@jonahtanjz 
It was introduced in #1191 to allow navigating to `minimised` panels (which use `span`s). And then slightly altered in #1557 to accomodate the ssr pr changes. (but not enough)

There's a couple of easy enough fixes if you want to take a shot at it.

---

As a side tip, I'd highly recommend getting used to your ide's git annotate / blame features, its a really effective tool for getting the context for a change, especially when no one remembers anything anymore 😏. (assuming the commit history is decently maintained of course)

**Comment by jonahtanjz** [comment]
Thanks @ang-zeyu! I will look into this
