### ISSUE TITLE
PlantUML diagrams require a manual refresh when live-previewing in lazy loading mode

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1617]
When using `markbind server -o`, if a page has a PlantUML diagram, the diagram appears as a broken image link when the page is auto-refreshed (due to an edit to the source code). Only after manually refreshing the browser I can see the diagram in the previewed page.
After auto-refresh by the live preview:
![image](https://user-images.githubusercontent.com/1673303/123758504-91d05680-d8f1-11eb-9f10-f609c0e717f5.png)

After another manual refresh:
![image](https://user-images.githubusercontent.com/1673303/123758583-a4e32680-d8f1-11eb-9017-5f3b5a2d6736.png)

Not sure if it is general issue or related to my local set up though.

**Comment by ang-zeyu** [comment]
The pages are probably being generated before the puml (separate process) does here

**Comment by riyadh-h** [comment]
> 
> 
> The pages are probably being generated before the puml (separate process) does here

I believe you're right, @ang-zeyu. I tried using `execSync` instead of `exec` for the PlantUML command execution call and the issue doesn't seem to occur anymore.

However, (re)building the pages takes more time now (average of 1.2 seconds for `execSync` compared to an average of 0.2 seconds for `exec`). I'm not sure if this difference would be significant in some websites that use MarkBind.

**Comment by tlylt** [comment]
@markbind/contributors if anyone is interested...this issue has adjusted to high priority now.

**Comment by SPWwj** [comment]
> Referenc

I can help with this.
