### ISSUE TITLE
Functional tests failed to run properly when executing `npm run test` in `packages/cli`

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1641]
**Tell us about your environment**
Windows 10

 **MarkBind Version:**
3.0.6

**What did you do? Please include the actual source code causing the issue.**
According to the developer guide > test section:
>If you only want to run tests for one of the packages (packages/*), simply switch into the appropriate directory and use npm run test as well!

So I ran `npm run test` in the root folder, everything seems fine and tests are passing. However, when I ran `npm run test` in `packages/cli`, I got stuck.

**What did you expect to happen?**
Expect test cases to run successfully. In particular, expect the functional tests in `cli/test/functional` to run successfully. This is correctly shown when running in the root directory:
![image](https://user-images.githubusercontent.com/41845017/127865586-573243de-c817-460d-b3a1-9cef5dc2bfb8.png)

**What actually happened? Please include the actual, raw output.**
However, when running in `packages/cli`, the unit tests are ok, but the functional ones are not ok:
![image](https://user-images.githubusercontent.com/41845017/127865782-81fc102a-853d-4bc2-8b65-c6bbc5c6aa7b.png)
![image](https://user-images.githubusercontent.com/41845017/127865811-90306c5f-b44d-4477-8a0a-4a8cd87996a6.png)

it gets stuck at running test_site tests and does not continue to the next test. i.e. 'test_site_algolia_plugin' and 'test_site_special_tags'.

Not sure if this is an issue with outdated documentation or a bug as I did not make any changes to the files but running the test cases in root directory or packages/cli have different outcome.

**Comment by jonahtanjz** [comment]
Ahh seems like this is a bug. The functional test script executed should be the same when run in the `packages/cli` and root directory itself. Will have to investigate why they are giving different result. Good catch @tlylt!

**Comment by wxwxwxwx9** [comment]
@tlylt Thanks for reporting this! I've looked into this and this is indeed a bug. 

Just to explain my findings. I think there are 2 parts to address in this issue. 

Firstly, regarding "getting stucked" at test_site tests, this blocking behavior stems from our usage of the diff library, specifically the following line of code. 

```
const diffParts = jsdiff.diffChars(expected, actual);
```

I suspect the reason for the blocking behavior may be because there are too many character diff. Probably a bug with the library? Not too sure, I probably have to look into the library to verify if it is really the case. But let's ignore this for now. 

Secondly, to explain why the tests are failing when ran from `packages/cli` vs running it from root, it's because the actual output are different in the 2 cases. It's something I missed out when working on a past PR. But this should be a rather straightforward fix. 

If you don't mind, would you like to take this on as your first issue? :-)

**Comment by tlylt** [comment]
@wxwxwxwx9 Sure, I will take this:)
