### ISSUE TITLE
Polish the default & documentation styles

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#1669]
Just a few areas in the default styles I noticed could use a little polish in general

- [ ] `<ol / ul / li>` indentation is too much at times, especially for mobile devices (relying on user agent stylesheet currently)
- [ ] `<box>` indentation / padding is a little wasteful on mobile devices
- [ ] margin below headings / paragraphs / tabs is a little small 
- [ ] `indented` `<div>`s inside the documentation are not well padded on mobile devices
- [ ] ❔ (post below / edit the post, probably a lot more I missed out)

Also not sure whether some of these are the result of improperly configured reset stylesheets, worth investigating in that direction first as well.

**Comment by riyadh-h** [comment]
Hello again!
Here are the results of my attempts (note: mixed images are just to highlight the difference between before and after):
>
> #### `<ol/ ul /li>` indentation is too much at times, especially for mobile devices (relying on user agent stylesheet currently)

[Before](https://user-images.githubusercontent.com/69278589/139568124-9efb541b-62ef-46ce-84ef-6c2c09fa6e45.jpg) | [After](https://user-images.githubusercontent.com/69278589/139568162-5a47bedd-da80-400d-abf9-746179d5be68.jpg) | [Mixed](https://user-images.githubusercontent.com/69278589/139568210-db985b38-099a-485e-a5ad-797a22e7b85c.jpg)

* Screenshots were taken from an Android phone using the DuckDuckGo browser.
* For `ol`/`ul` elements, I've set `padding-left` to `1.5rem`.

---

>
> #### `<box>` indentation / padding is a little wasteful on mobile devices

[Before](https://user-images.githubusercontent.com/69278589/139570435-845069d9-0a42-4a42-b4e0-6afcf11591b4.jpg) | [After](https://user-images.githubusercontent.com/69278589/139570446-2ef16481-2338-4a11-b3ee-5d7552479fbc.jpg) | [Mixed](https://user-images.githubusercontent.com/69278589/139570463-f13623a6-e410-44dd-b562-b63edc8f9d06.jpg)

* Screenshots were taken from phone.
* In `TipBox.vue`...
    *  For `.contents`, I've set `padding` to `0` only (`6px` left- and right-padding was removed).
    * For `.box-body-wrapper`, I've set `padding` to `0.75rem` for all sides.

---

>
> #### margin below headings / paragraphs / tabs is a little small

[Before](https://user-images.githubusercontent.com/69278589/139570523-fab35311-ddca-42f1-a988-762bf279b61e.png) | [After](https://user-images.githubusercontent.com/69278589/139570534-3f4210a9-7ff9-451b-8f8f-644601c12678.png) | [Mixed](https://user-images.githubusercontent.com/69278589/139570545-e85efb59-a9f9-4d71-b5a4-233879151cd2.png)

* Screenshots were taken from a Windows 10 machine using Firefox.
* For heading elements, I've set `margin-bottom` to `1rem`.
* For paragraphs and tabs, I couldn't decide on value for their bottom margins. Can you elaborate on how big should the margins be, please?
    * IMO, the currently-set margins seem to be fine.

---

>
> #### `indented` `<div>`s inside the documentation are not well padded on mobile devices

[Before](https://user-images.githubusercontent.com/69278589/139570690-3c70667b-2bb7-44e3-9291-da50821a1d80.jpg) | [After](https://user-images.githubusercontent.com/69278589/139570700-db0d4c88-d8e3-42d7-97e5-08fcfc89e034.jpg) | [Mixed](https://user-images.githubusercontent.com/69278589/139570710-15b67515-d11b-4b04-8f58-444bfaa3ff0c.jpg)

* Screenshots were taken from phone.
* For `indented` in `main.css`, I've set `padding-left` to `10px`.

Let me know what you think about these adjustments 😃 

Also, 

>
> not sure whether some of these are the result of improperly configured reset stylesheets, worth investigating in that direction first as well.

I'm not too familiar with reset stylesheets, but since Bootstrap is used by MarkBind, wouldn't [Bootstrap's reset stylesheet Reboot](https://getbootstrap.com/docs/4.0/content/reboot/) be applied automatically without configuration? I'm not sure if MarkBind uses another reset stylesheet or not.

**Comment by ang-zeyu** [comment]
Looks good to me generally 👍 Thanks for the screenshots as well.

> For paragraphs and tabs, I couldn't decide on a value for their bottom margins. Can you elaborate on how big should the margins be, please?
> IMO, the currently-set margins seem to be fine.

👀 [tabs](https://github.com/MarkBind/markbind/blob/master/packages/vue-components/src/Tabset.vue) shouldn't have any margin right now, you can try it out by placing some text under the tabs [here](https://markbind.org/userGuide/usingComponents.html#tabs).

As for paragraphs, agree its a little subjective on second look. If it looks fine to you (could also try putting multiple successive paragraphs and see if looks too "wordy"), I think we can leave it be for now.

> I'm not too familiar with reset stylesheets, but since Bootstrap is used by MarkBind, wouldn't Bootstrap's reset stylesheet Reboot be applied automatically without configuration? I'm not sure if MarkBind uses another reset stylesheet or not.

Yes it should be applied currently already, I found it strange that it didn't include any default list element styles being a reset stylesheet though. Wasn't sure if its an improper configuration somewhere on our end.

**Comment by riyadh-h** [comment]
@ang-zeyu Np, and thanks for the feedback!

>
> 👀 tabs shouldn't have any margin right now, you can try it out by placing some text under the tabs here.

Huh, I thought [this margin that's set to `.nav-tab`](https://github.com/MarkBind/markbind/blob/00dd09104fd80d7a9839181f97bd650462ff2028/packages/vue-components/src/Tabset.vue#L105-L107) is supposed to be the one for tabs, not sure if I'm correct or not 😅 

>
> As for paragraphs, agree its a little subjective on second look. If it looks fine to you (could also try putting multiple successive paragraphs and see if looks too "wordy"), I think we can leave it be for now.

Okay 👍
I copied a few *Lorem ipsum* paragraphs into a page, and [this was the result](https://user-images.githubusercontent.com/69278589/139617335-702d08eb-3c50-4134-ae21-1a04d1cfac18.png).

Also, I wanted to ask about a few (minor) details:
* Should we apply the `ol`/`ul` indentation adjustment to larger devices as well?
* Would it be better to have the CSS rules for ordinary HTML elements (e.g., `ul`, `ol`, `h1`) inside `core/template/default/stylesheets/main.css` or `core-web/src/styles/markbind.css`?
    * It seems that both already include some CSS rules for such elements (e.g., `mark` in `main.css` and `code` in `markbind.css`).

**Comment by ang-zeyu** [comment]
> Huh, I thought this margin that's set for .nav-tab is supposed to be the one for tabs, not sure if I'm correct or not 😅

ok just got the confusion 🤣:

> under the tabs
- That's for the area between the tab's contents and headers (I think you are referring to this, agree this is fine as well)
- Below the tab's contents and headers (0 margin currently)

> I copied a few Lorem ipsum paragraphs into a page, and this was the result.

This looks good!

> Should we apply the ol/ul indentation adjustment to larger devices as well?

I'll have to look at the PR to figure out, but it looks ok based on your earlier screenshot as well.

> Would it be better to have the CSS rules for ordinary HTML elements (e.g., ul, ol, h1) inside core/template/default/stylesheets/main.css or core-web/src/styles/markbind.css?

It should go in `core-web/src/styles/markbind.css` which contains our "bundled" styles (comes with every site). 

`core/template/default/stylesheets/main.css` mostly contains "layout" styles specific to the template that the author may want to modify for their use case (e.g. if you want to put the site nav on the right instead).

> mark in main.css and code in markbind.css

Nice catch, this is an oversight and should be moved to `markbind.css` sometime in another PR.

**Comment by riyadh-h** [comment]
Ah, I get it now 😂
Okay, so I tried to experiment with different values for the bottom margin, and I think `1.5rem` looks good. It's larger than the margins of paragraphs so that the readers wouldn't confuse the tab contents with subsequent paragraphs:

[Before](https://user-images.githubusercontent.com/69278589/139757868-4fe8b478-9d87-4dfc-92a7-61d33aafae7c.png) | [After](https://user-images.githubusercontent.com/69278589/139757922-3b1233c5-f211-4c1b-bd33-b5fc7b1c4b51.png) | [Mixed](https://user-images.githubusercontent.com/69278589/139757943-4f390059-e37e-4b8c-b092-48fbcdb16559.png)

Also, I think that we can try to avoid that confusion by giving the tab contents a background color or a border on all sides (or both). However, doing so would require some padding around the contents to make them more readable, which might not be ideal for viewing on mobile devices.

Here are some screenshots of experimenting with this idea:

[PC (no padding)](https://user-images.githubusercontent.com/69278589/139763968-e3a9b177-7413-41c3-b6f0-8ccb0a390668.png) | [PC (padding)](https://user-images.githubusercontent.com/69278589/139763985-c07521e6-1daa-4e29-b784-a01b1bc6ce9c.png) | [Phone (no padding)](https://user-images.githubusercontent.com/69278589/139763994-28a2ea59-25d3-4b3b-96dd-a7ad5c9f6441.jpg) | [Phone (padding)](https://user-images.githubusercontent.com/69278589/139764005-57b86ad0-7e7a-4c52-955c-829820c513aa.jpg)

You can ignore the extra horizontal line at the bottom in the phone screenshots.

>
> I'll have to look at the PR to figure out, but it looks ok based on your earlier screenshot as well.

Okay, I think I'll set it for all devices for now. 

>
> It should go in core-web/src/styles/markbind.css which contains our "bundled" styles (comes with every site).
>
> core/template/default/stylesheets/main.css mostly contains "layout" styles specific to the template that the author may want to modify for their use case (e.g. if you want to put the site nav on the right instead).

Got it 👍 

Thanks for the clarifications!
I'll try to create a PR for the changes soon 👍

**Comment by damithc** [comment]
> Also, I think that we can try to avoid that confusion by giving the tab contents a background color or a border on all sides (or both). However, doing so would require some padding around the contents to make them more readable, which might not be ideal for viewing on mobile devices.

I prefer to use some sort of border at the bottom rather than a bg color to distinguish tab contents. Content in tabs are meant to be alternative threads of the flow of content. Whichever the tab is selected, the content should blend into the main flow. So, it makes sense to mark the start and end the alternative content in a subtle way, for which borders are a better fit than bg colors (the latter indicates different _type_ of content rather than a different _flow_).

**Comment by riyadh-h** [comment]
Ah, I see.
Thanks for the input, @damithc 👍 

>
> Content in tabs are meant to be alternative threads of the flow of content. Whichever the tab is selected, the content should blend into the main flow.

May I check if the suggested bottom margin in [my previous post](https://github.com/MarkBind/markbind/issues/1669#issuecomment-957002416) is in line with this purpose?

**Comment by damithc** [comment]
> May I check if the suggested bottom margin in [my previous post](https://github.com/MarkBind/markbind/issues/1669#issuecomment-957002416) is in line with this purpose?

Yes, I'm OK with that one.
