### ISSUE TITLE
Flags in `markbind serve` does not seem to work. Specifically `-f` and `-d`

### ISSUE THREAD

**Issue by ong6** [MarkBind/markbind#1682]
**Tell us about your environment**
Windows 10
VScode

**MarkBind Version:**
Latest version

**What did you do? Please include the actual source code causing the issue.**
- Create a test template
- Run `markbind serve -d` to run the markbind server locally. 
- Edit the markbind template and save the file.

Repeat and test for the `-f` flag.

**What did you expect to happen?**
Expected the website to reload and reflect changes on the live webpage.

**What actually happened? Please include the actual, raw output.**
The page does not reload and instead stays the same

Example of what actually happened for the `-d` flag
![StaleReload](https://user-images.githubusercontent.com/19247856/136797187-6d904f66-e65d-401a-82e7-9818fcb68275.gif)

**Comment by aaronsms** [comment]
The issue here is that a simple string check is used in live server module, thus */ == */index.html equality checks fail.

**Comment by ryoarmanda** [comment]
Good catch, thanks for the analysis, @ong6! I made that live-server patch a short while ago, if I may add more to it:

The reason of this oversight is that in cli/index.js, there is a MarkBind-side pre-processing step that modifies request url from `*/` to `*/index.html` before it finds its way to the live-server patch, so the patch worked on this as pre-condition. Turns out, this step is only done when `-o` is specified.

The default entry page path in `-o` is always set to `/index.html`, so this is not an issue on that mode. However, on other modes (such as `-d` and `-f` as described), the default entry page path is always `/`.
