### ISSUE TITLE
Some images in User Guide not working

### ISSUE THREAD

**Issue by ong6** [MarkBind/markbind#1710]
**Tell us about your environment**

Viewing from Google Chrome 

* **MarkBind Version:**
N/A

**What did you do? Please include the actual source code causing the issue.**

Was reading more about plugins when i noticed that the sample images when plugins are added are all not present.

Example image from [using plugins page](https://markbind.org/userGuide/usingPlugins.html):
![image](https://user-images.githubusercontent.com/19247856/149267000-1be0cb45-270c-4066-bf2e-f24e6f6c9556.png)

**What did you expect to happen?**

Images should load properly

**What actually happened? Please include the actual, raw output.**
N/A

**Comment by tlylt** [comment]
Can confirm this behavior.
When checking out the image files that the broken images are referring to, it seems like the images themselves are broken:
![image](https://user-images.githubusercontent.com/41845017/149268947-a0038751-7421-4660-8724-9524e7fa8cb4.png)

It seems like the problem is introduced in this [commit](
https://github.com/MarkBind/markbind/commit/14923efab89ba40a2dd3e84af85325fea0f9b0a2#diff-8124bca43bfb44df726bef0b41269b9aca6208e94b3b9f39aafe1797cf6219a9) for PR: Wrap fenced code blocks on-demand(#1668)
