### ISSUE TITLE
Missing linebreak in logging below progress bar

### ISSUE THREAD

**Issue by jovyntls** [MarkBind/markbind#1723]
**Tell us about your environment**
MacOS Monterey
* **MarkBind Version:** v3.1.0

**What did you do? Please include the actual source code causing the issue.**
Run `markbind serve` on a site with logger warnings

**What did you expect to happen?**
The warning log message should be on a new line below the progress bar.

**What actually happened? Please include the actual, raw output.**
There is a missing line break between these two lines:
<img width="1050" alt="Screenshot 2022-01-18 at 3 24 58 PM" src="https://user-images.githubusercontent.com/61113575/149891960-116cd8f5-e9f9-40ce-9c29-03f2e96fe059.png">

**Comment by ryoarmanda** [comment]
Ah, this is something that I have been eyeing on for a while. Further research may be needed, but for a preliminary thought, I think this might be because of the way this kind of "updatable" progress bar works. If I recall it right, the common trick of progress bars like these are to use the return carriage (`\r`) to overwrite the old bar. The incoming logs messed up with the flow a little bit and cause the image above.

This is essentially what the first item on #1633 is trying to tackle. Feel free to research any ways to create or find a different progress bar display mechanism. I mentioned the `apt-get`'s progress bar there (the one you usually use to install packages in Linux), I remember that even with incoming log outputs, the progress bar on that program stays intact and don't clutter the console, not sure how they did it.

**Comment by jovyntls** [comment]
Hi @ryoarmanda, thanks for your explanations (it was helpful 😄 )! I'll take some time to look into this and see what can be done.

**Comment by tlylt** [comment]
Happen to investigate into the progress bar in another PR so leaving some notes here:

- It seems like when there is a warning that disturbs the progress bar, it recreates another one. So on top of the linebreak that is missing, the progress bar is unnecessarily rendered twice(somehow, not exactly sure why)
![image](https://user-images.githubusercontent.com/41845017/153006359-00c50285-60da-4cbb-a153-8206b95ae74e.png)

- If without any warning, it should and will only render one progress bar.

- The [`bar.interrupt()`](https://github.com/visionmedia/node-progress#interrupt) method might be a possible solution for this issue. see https://github.com/visionmedia/node-progress/issues/188#issuecomment-614598634
Or I am guessing we could possibly find an alternative as the `node-progress` module that we are using is no longer actively maintained (last update 2018)

**Comment by tlylt** [comment]
Reopening because while broken link reporting is shifted to the end of page generation(hence resolving the missing linebreak for those logs), other types of warnings such as `builtwarn: modal has a header slot, 'header' attribute has no effect.` still occur without linebreak. E.g:
![image](https://user-images.githubusercontent.com/41845017/163676394-f89add8f-8e65-4678-b134-ad90895902e0.png)
