### ISSUE TITLE
Setup Code Coverage

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1755]
**Is your request related to a problem?**
Would be nice to keep track of the code coverage stats.

**Describe the solution you'd like**
Both of the following are viable solutions with good documentation on how to get started
- [Codecov](https://about.codecov.io/)
- [Coveralls](https://coveralls.io/)

**Describe alternatives you've considered**
nil

**Additional context**
I'm not too sure how code coverage is handled in a mono-repo. I guess in terms of implementation we can do this incrementally, setting up instrumentation and CI for individual packages and their existing test cases first.

**Comment by ang-zeyu** [comment]
I think this is definitely nice to have (e.g. https://github.com/MarkBind/markbind/pull/1746 surfaced an entirely untested branch).

Let's put this on hold until #1421 however, as the tooling will likely change significantly with it.

**Comment by jovyntls** [comment]
#1421 and #1913 are largely done now - we're just left with a few test files that are mostly small and isolated. If anyone wants to look into this issue please feel free!

**Comment by lesterong** [comment]
hello, i would like to look into this issue 🙂

**Comment by tlylt** [comment]
> hello, i would like to look into this issue 🙂 

Sure. Let us know if you have any updates in this issue👍

**Comment by lesterong** [comment]
> Sure. Let us know if you have any updates in this issue👍

I just took a brief look at Codecov and Coveralls, and both seems to offer a very similar feature set at least for our needs. Both offer support for monorepos through Carryforward flags. Is there any preference for one or the other? I am leaning towards Codecov as their documentation appears to be more comprehensive than Coveralls.

**Comment by tlylt** [comment]
> I just took a brief look at Codecov and Coveralls, and both seems to offer a very similar feature set at least for our needs. Both offer support for monorepos through Carryforward flags. Is there any preference for one or the other? I am leaning towards Codecov as their documentation appears to be more comprehensive than Coveralls.

No objections to either. Could you find out the comparisons in terms of the free plan that each offer? If they are similar we can go with Codecov as suggested. Let us know on Slack if you need help with credentials/access to set it up for MarkBind.

**Comment by lesterong** [comment]
For the purposes of MarkBind, I do not see a big difference in terms of what Codecov and Coveralls offer. For both, we will be under the Open Source plan, which is free.

**Language Support**: Both support the languages used by MarkBind (mainly JavaScript and TypeScript).

- [Languages supported by Coveralls](https://docs.coveralls.io/integrations#language-integrations)
- [Languages supported by Codecov](https://docs.codecov.com/docs/supported-languages)

**Monorepo**: Both support carryforward flags, which allows us to have coverage for each MarkBind package.

- [Carryforward Flags in Coveralls](https://coveralls.io/better-monorepo-support)
- [Carryforward Flags in Codecov](https://docs.codecov.com/docs/carryforward-flags)

**CI Providers**: Codecov and Coveralls support a slightly different range of CI providers

- [Supported CI Providers in Coveralls](https://coveralls.io/supported-continuous-integration)
- [Supported CI Providers in Codecov](https://docs.codecov.com/docs/supported-ci-providers)


Otherwise, I do not see any major concerns for MarkBind. Do let me know if there's any particular feature that we require for MarkBind in terms of code coverage.

**Comment by tlylt** [comment]
> > Sure. Let us know if you have any updates in this issue👍
> 
> I just took a brief look at Codecov and Coveralls, and both seems to offer a very similar feature set at least for our needs. Both offer support for monorepos through Carryforward flags. Is there any preference for one or the other? I am leaning towards Codecov as their documentation appears to be more comprehensive than Coveralls.

👍 can proceed with Codecov
