### ISSUE TITLE
Update version & content of init-* repos

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1810]
**Tell us about your environment**
Windows
* **MarkBind Version:**
v3.1.1
**What did you do? Please include the actual source code causing the issue.**
The following repos are quite outdated (~2 years), would be good if they are updated (eg. markbind-cli version).
https://github.com/MarkBind/init-typical
https://github.com/MarkBind/init-typical-netlify
https://github.com/MarkBind/init-minimal-netlify

**Comment by tlylt** [comment]
Hi @damithc, wonder if you can recall for the above-mentioned repos such as https://github.com/MarkBind/init-typical, do you need to manually deploy them to netlify (or how's the deployment done)? I don't mind putting up PRs to update the repos to MarkBind v4, but I think it will have to be redeployed.

**Comment by damithc** [comment]
@tlylt I think those repos were used to get MarkBind featured in `https://jamstack.org/generators/?utm_source=blog&utm_medium=about-ssgs-pnh&utm_campaign=devex` I don't remember how it was done exactly though, as it was done by one of the devs.

https://github.com/MarkBind/markbind/issues/479 might have some relevant info

**Comment by tlylt** [comment]
> @tlylt I think those repos were used to get MarkBind featured in `https://jamstack.org/generators/?utm_source=blog&utm_medium=about-ssgs-pnh&utm_campaign=devex` I don't remember how it was done exactly though, as it was done by one of the devs.
> 
> #479 might have some relevant info

I see. Thanks, @damithc!
Meanwhile, I am expanding the scope of this issue to also explore ways to automate the update of such repositories, so that they stay up-to-date with the latest release (this should be possible via GitHub Action)

**Comment by yucheng11122017** [comment]
Hi @tlylt can I ask what is exactly meant by update the code? Is it to update the template to show more existing features? Could I also check what you mean by `markbind-cli version`? 

Sorry for disturbing thank you!

**Comment by tlylt** [comment]
> Hi @tlylt can I ask what is exactly meant by update the code? Is it to update the template to show more existing features? Could I also check what you mean by `markbind-cli version`? 
> 
> 
> 
> Sorry for disturbing thank you!

Those repos contain the resultant files after running markbind init. However as they were generated by older versions of markbind-cli, the content and the version specified in those files are outdated.

Replace them with the latest content generated by markbind init should be sufficient. Just make sure to check that everything still works,
Especially for the netlify template, see if there are any details that may affect the integration.

**Comment by yucheng11122017** [comment]
Hi @tlylt I am encountering an error when trying to create a pull request for init-typical. 
I am unable to pass the checks because it cannot deploy to netlify due to a `UNSUPPORTED BUILD IMAGE` error. Screenshot of the log is shown below. 

According to documentation online, this is because netlify no longer supports Ubuntu 16.04 Xenial Xerus. However, I am unable to change the build image since I don't have permissions to access the settings. The [tutorial](https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239) is here. 

Does our team have access to the netlify account? 

Thank you!

![image](https://user-images.githubusercontent.com/77204346/213643774-db054469-f55c-424d-a54a-5c81588da910.png)

**Comment by tlylt** [comment]
PRs merged in respective repos, thanks @yucheng11122017
