### ISSUE TITLE
Nunjucks embeds override variables defined in the file it is called in

### ISSUE THREAD

**Issue by kaixin-hc** [MarkBind/markbind#1830]
**Tell us about your environment**
macOS Monterey

* **MarkBind Version:**
v3.1.1
**What did you do? Please include the actual source code causing the issue.**
In docs/userGuide/settingSiteProperties.md , the site title is set to `site.json File` instead of `Setting Site Properties`

```
{% set title = "Setting Site Properties" %}

[some code here]
{% from "njk/common.njk" import embed, previous_next %}
[more code here]
{{ embed("References → **`site.json` File**", "siteJsonFile.md") }}      // commenting this line out fixes the issue
```

**What did you expect to happen?**
I expected the site title to be 'Setting Site Properties'.

**What actually happened? Please include the actual, raw output.**
<img width="1628" alt="Screenshot 2022-03-14 at 7 40 49 PM" src="https://user-images.githubusercontent.com/59471320/158164942-397161dc-bdde-4404-9b41-059496b385ce.png">

**Comment by jonahtanjz** [comment]
Seems like this is due to the `embed` macro using `<include />` without the `omitFrontmatter` attribute. This pulls in the `frontmatter` from `siteJsonFile.md` file which has the title "site.json File". Although this is undocumented, if a page has multiple `frontmatter`s, it will take the last `frontmatter`. 

We can add this in the documentation as a warning and maybe add a new parameter to the `embed` macro so that we can choose to add the `omitFrontmatter` attribute to `<include />` if needed.

**Comment by RyanCheungJF** [comment]
Hi, could I take up this issue?

**Comment by calvintanwj** [comment]
Hi, can I attempt this issue as a first timer?
