### ISSUE TITLE
Run CI test for pull requests against all branches

### ISSUE THREAD

**Issue by jonahtanjz** [MarkBind/markbind#1876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the area that this feature belongs to?

DevOps

### Is your feature request related to a problem? Please describe.

Currently only PRs against the master branch will trigger the CI test workflow. For instance #1834 does not have any CI test when merging to the bootstrap development branch.

### Describe the solution you'd like

Trigger CI test for all base branches in MarkBind. This will be useful for hot fix branches as well.

**Comment by tlylt** [comment]
Will it be possible that PRs to a non-master branch do not pass the CI checks for some legitimate reason? Perhaps because the changes are drastic and progressive, some test cases are ok to fail initially but will be fixed later on. If such cases are valid, then perhaps the CI runs on those PRs may not be strictly necessary (in a sense that it does not give any good information about the quality of this PR)

**Comment by jonahtanjz** [comment]
> Will it be possible that PRs to a non-master branch do not pass the CI checks for some legitimate reason?

Agree there could be such cases but I think these can be exceptions (i.e continue to merge to dev branch even if CI is failing).

> If such cases are valid, then perhaps the CI runs on those PRs may not be strictly necessary (in a sense that it does not give any good information about the quality of this PR)

I think having CI test on PRs to all branches will be useful in general. For PRs that are progressive, if the tests are meant to be updated together, it would be good to pick up failing tests earlier instead of only seeing it in the final merge to master. For hotfix branches, it would definitely be needed since it is going to be used for releasing a new version.
