### ISSUE TITLE
Better Developer doc for merging PRs

### ISSUE THREAD

**Issue by ong6** [MarkBind/markbind#1881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the area that this feature belongs to?

Documentation

### Is your feature request related to a problem? Please describe.

The documentation on merging PRs are slightly vague and can be updated with clearer wording.

![image](https://user-images.githubusercontent.com/19247856/161771668-f140f1ce-97af-4b5a-87b7-5eebac33e136.png)

### Describe the solution you'd like

- [ ] Clearer documentation on merging PRs (e.g. Mentioning that squash commit should be used)
- [ ] Steps on how to undo a accidental merge commit
- [ ] Examples of when to squash and merge commits

**Comment by jonahtanjz** [comment]
On top of that, we can give some examples of when to use `squash` and `merge` commit.

**Comment by tlylt** [comment]
I think even though we linked `Working with PRs@SE-EDU`, I did not realize that our default is squash when I first read it... perhaps due to the content being hidden in the closed panel.

As mentioned in the issue description, perhaps we can adapt the content from the panel directly in the project management section to be more explicit about our default squash strategy and the examples.

https://se-education.org/guides/guidelines/PRs.html#merging-prs
![image](https://user-images.githubusercontent.com/41845017/166854109-cc97e1fa-cf97-4e93-96fb-28a79b87f836.png)
