### ISSUE TITLE
Integrate Markdown linter to enforce consistency

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Inspired by a recent review comment on my PR that some of the markdown I wrote weren’t compliant with the recommended style, perhaps would be good to have a linter to enforce it instead of relying on manual checking.

### Describe the solution you'd like

Integrate a Markdown linter both locally as part of linting, as well as CI check.
For possible packages to use, there’s https://github.com/DavidAnson/markdownlint which seems to be quite promising.

**Comment by ang-zeyu** [comment]
Implementation wise this might be a little difficult as MarkBind extends commonmark, but maybe there's some configuration options in there that could fix this 🤔 

> Inspired by a recent review comment on my PR that some of the markdown I wrote weren’t compliant with the recommended style, perhaps would be good to have a linter to enforce it instead of relying on manual checking.

Which PR is this? 👀 
(not aware that we had a recommended style)

Just my two cents,

I don't think linting _documentation_ would turn out to be quite worth the maintainence costs of introducing such linters into our toolchain.

I'm also personally somewhat against introducing silly stringent standards like "ensure paragraphs stay on one line, enable word wrap in your ide" which introduces more trouble for contributors, and does not produce any real tangible readability benefits like eslint does with code.

This is not to say we shouldn't aim to make our documentation _look consistent to the reader_ (which, most of the _syntactic_ rules in https://github.com/DavidAnson/markdownlint do not help with), but I think this may be better achieved through PR reviews as we've been doing so far.

E.g. I do not think it poses a readability issue to developers if you use either of these. (much less, to the reader)

```
* list

- list
```

**Comment by tlylt** [comment]
> Which PR is this? 👀 (not aware that we had a recommended style)

https://github.com/MarkBind/markbind/pull/1872#discussion_r842783272

**Comment by ang-zeyu** [comment]
A simple (maybe inappropriate) analogy might be that we are able to read microsoft word documents from anyone 😂

**Comment by ang-zeyu** [comment]
> > Which PR is this? 👀 (not aware that we had a recommended style)
> 
> [#1872 (comment)](https://github.com/MarkBind/markbind/pull/1872#discussion_r842783272)
> 
> Mentioned here https://markbind.org/devdocs/devGuide/styleGuides.html

Thanks for pointing this out. I missed this in https://github.com/MarkBind/markbind/pull/1246

pinging @damithc for discussion

**Comment by damithc** [comment]
As the amount of our documentation grows, it's nice if it's follows a consistent style, although we don't want to be overly prescriptive.
Some style rules actually have tangible benefits and help to educate the writer (the writer may not be aware of those benefits or those syntax options). e.g., using `1.` for every item in numbered lists
We can start by enforcing just a few rules that we think have value and pilot it for a while. If it's getting in the way, we can get rid of it. 
We are not in dire need of a linter right now though (i.e., the expected benefit is not that high). So, it depends on how much effort is required for adopting one too (i.e., the cost shouldn't be high either).

**Comment by ang-zeyu** [comment]
> it's nice if it's follows a consistent style, although we don't want to be overly prescriptive.

> Some style rules actually have tangible benefits and help to educate the writer (the writer may not be aware of those benefits or those syntax options). e.g., using 1. for every item in numbered lists

> We are not in dire need of a linter right now though (i.e., the expected benefit is not that high). So, it depends on how much effort is required for adopting one too (i.e., the cost shouldn't be high either).

Agreed as well, if there are certain rules with real readability benefits, we can look into it.

This issue would be very low priority too, I'll leave this open for investigation if anyone is interested.

> Implementation wise this might be a little difficult as MarkBind extends commonmark, but maybe there's some configuration options in there that could fix this 🤔

To give one example, we modify the markdown/html parser to allow parsing things like `<puml>`, which can contain almost anything. The linter likely won't be able to accomodate this as nicely.

---


Just adding some anecdotal experience from my past 2 years reviewing PRs here too 😅, I've never really encountered any issues with readability in _documentation source files_ syntax from anyone, even the most trivial comments are only related to grammar / wording.

I think there is a natural tendency to follow ⬇️ even without a linter (also rather surprised markdown linters exist as such):

> it's nice if it's follows a consistent style, although we don't want to be overly prescriptive.

Nevertheless, ⬇️

>Agreed as well, if there are certain rules with real readability benefits, we can look into it.

**Comment by tlylt** [comment]
> > Implementation wise this might be a little difficult as MarkBind extends commonmark, but maybe there's some configuration options in there that could fix this 🤔
> 
> To give one example, we modify the markdown/html parser to allow parsing things like `<puml>`, which can contain almost anything. The linter likely won't be able to accomodate this as nicely.

Some custom configuration will be necessary, and perhaps not too difficult as well (something like configuring Eslint options, which is quite typical)

> Just adding some anecdotal experience from my past 2 years reviewing PRs here too 😅, I've never really encountered any issues with readability in _documentation source files_ syntax from anyone, even the most trivial comments are only related to grammar / wording.

The downside of that is now we do have some inconsistencies and while some reviewers may not look at markdown styling, some do (and in the future too). This means time is spent on giving such feedback and making the adjustments. The time that could be avoided if there's help for the authors to write the document consistently in the first place. One important fact is that updates to the existing documentation is going to mirror what has been done. If things were inconsistent, the documentation will grow more so in the future. Low impact still, but not very nice.

Linters do more than linting nowadays in our IDE. They provide warnings, links to related rules, an explanation of the rationale behind such rules, and auto fixing that can be of great help for anyone who's lazy (practically everyone). Some rules besides aesthetic, does more help in terms of informing the writer before he needs to serve the site and obverse the error in the browser. Those squggly lines can save debugging time, especially when you happen to casually miss a blank line.

Again, some rules may not be easily enforced and some may not be very useful, but some do:
(Just taking one example that I saw)
https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md042---no-empty-links
![image](https://user-images.githubusercontent.com/41845017/163838047-a6fa2bc1-1815-4402-b8cc-56aee41374e7.png)


> I think there is a natural tendency to follow ⬇️ even without a linter (also rather surprised markdown linters exist as such):
> 
> > it's nice if it's follows a consistent style, although we don't want to be overly prescriptive.

To rely on memory or personal grasp of the markdown formats in my opinion is just not going to cut it, because rules when not enforced, cease to exist.

The point is to make the product better, which sometimes involves a trade-off between the quality of the product and the effort required. I agree on that due to the low significance, we should make such improvements that do not make the developers less productive when writing docs.

As a first-step/low hanging fruit, we can document the existence of such tools and provide a MarkBind friendly config file in our DG, for anyone who's interested. This is similar to the debugger settings that we currently have for VScode/webstorm. 
I might do just that when I got the time...(I have the markdownlint extension installed in my VScode, but haven't got the time to play around with it 😓 )

**Comment by ang-zeyu** [comment]
> Some custom configuration will be necessary, and perhaps not too difficult as well (something like configuring Eslint options, which is quite typical)

one example, in a "vanilla" markdown parser like markdown it:

 (if we don't want lists in trees to be validated since they aren't really trees)
https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md032---lists-should-be-surrounded-by-blank-lines

```
foobar  // markdown paragraph start
<tree>  // markdown continue
* Item 1  // parsed as list (try in the github renderer for example)
  * Nested Item 1
  * Nested Item 2
</tree>
```

or issues with markdown-it-attrs, etc.

Not quite sure if these would have configuration options, as they require rather significant markdown parser modifications.

**Comment by ang-zeyu** [comment]
> Linters do more than linting nowadays in our IDE. They provide warnings, links to related rules, an explanation of the rationale behind such rules, and auto fixing that can be of great help for anyone who's lazy (practically everyone). Some rules besides aesthetic, does more help in terms of informing the writer before he needs to serve the site and obverse the error in the browser. Those squggly lines can save debugging time, especially when you happen to casually miss a blank line.
>
> Again, some rules may not be easily enforced and some may not be very useful, but some do:
(Just taking one example that I saw)
> https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md042---no-empty-links

Agree things like this could benefit. (in this particular case though, implementing hash checking might be the right direction)

My argument was for syntactic consistency, per the issue title.

The majority of rules like this https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md009---trailing-spaces, I'm really having a hard time believing would have any real benefits. Or, when they do pose a tangible readability issue to the reader (e.g. https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md001---heading-levels-should-only-increment-by-one-level-at-a-time), are already being dealt with seldomly in our PRs.

> The downside of that is now we do have some inconsistencies and while some reviewers may not look at markdown styling, some do (and in the future too). This means time is spent on giving such feedback and making the adjustments. The time that could be avoided if there's help for the authors to write the document consistently in the first place. One important fact is that updates to the existing documentation is going to mirror what has been done. If things were inconsistent, the documentation will grow more so in the future. Low impact still, but not very nice.

There definitely are inconsistencies, and it is definitely "not as nice". It is not a win-for-all decision. My argument and analogy on the point with microsoft word is that these inconsistencies do not affect developer readability in any meaningful way, and / or are already enforced to a "good enough" degree by a natural tendency to adhere to the majority style in our documentation. 

The biggest case in point I am raising therefore is that we have been doing ok for the past 2 years (and then likely even before that for 3 years) (MarkBind is ~5 years old) without a markdown syntactic consistency standard. 

There are also many successful and much larger projects that do not have such standards imposed. Rather, they focus on communication to the reader, which is what documentation is ultimately about.
- https://www.gatsbyjs.com/contributing/gatsby-style-guide (Just in case, no, the formatting section inside there isn't what you think. Have a closer look. These are all things that do affect reader readability in some way.)

Another case in point, even when such standards are imposed, there is often disagreement on which ones have the winning rationale. In which case I really believe we don't bother imposing such subjective standards at all. E.g.
- https://se-education.org/guides/conventions/markdown.html (line wrapping)
- https://docs.saucelabs.com/contributing/style-guide/#content

> This means time is spent on giving such feedback and making the adjustments.

*Do not forget*:
- The time spent by N contributors over P PRs and K standards correcting things (which, even with a linter, adds up) 
- The increased setup work needed to integrate linting tools for contributors and on our end
- The increased barrier to entry to getting contributors at all, which is paramount for an open source project
- The cognitive overhead for reviewers to impose such standards (which, even with a linter, adds up), distracting from reader readability issues that do matter in documentation writing

> some reviewers may not look at markdown styling

no, this assumes we agree on imposing such standards at all. Inconsistent stylistic reviewing standards is the last thing an open source project should be having.

> To rely on memory or personal grasp of the markdown formats in my opinion is just not going to cut it, because rules when not enforced, cease to exist.

Yes, it won't. See my concluding suggestions.

Ultimately, I'm weighing my opinion on this based on what I've observed in these past 2 years vs the cons of a markdown standard. Which, I really believe everyone has been doing a good job, and that "proof is in the pudding" here. I'd much rather we invest our time and 🧠 into the goal of reader communication in documentation. Things like this https://www.gatsbyjs.com/contributing/gatsby-style-guide.

This is not something like code that far too often runs into severe consistency issues that really do affect code readability, in which case, eslint does help.

---

@damithc @tlylt 

I'm going to controversially suggest therefore we remove the markdown standard from the developer guide at all, which we've been doing ok without.

To be clear as well, I'm still welcoming PRs like https://github.com/MarkBind/markbind/pull/1829/files as and when needed. But these things are few and far between and self-evident without having to explicitly enforce a markdown standard.

> My argument and analogy on the point with microsoft word is that these inconsistencies do not affect developer readability in any meaningful way, and / or are already enforced to a "good enough" degree by a natural tendency to adhere to the majority style in our documentation.

> "proof is in the pudding"

Pinging for a few more opinions as well if this is really the case or just "in my head" @ryoarmanda @jonahtanjz @wxwxwxwx9 @raysonkoh 


> As a first-step/low hanging fruit, we can document the existence of such tools and provide a MarkBind friendly config file in our DG, for anyone who's interested. This is similar to the debugger settings that we currently have for VScode/webstorm. This is focusing on helping the developers while not enforcing the rules via strict linter checks before push/merge.

I am also not against this to be clear (especially the more functional rules in there). Making it optional will alleviate most of the concerns. But not as a "first-step", but a final one.

**Comment by damithc** [comment]
> Ultimately, I'm weighing my opinion on this based on what I've observed in these past 2 years vs the cons of a markdown standard. Which, I really believe everyone has been doing a good job, and that "proof is in the pudding" here. I'd much rather we invest our time and 🧠 into the goal of reader communication in documentation. Things like this https://www.gatsbyjs.com/contributing/gatsby-style-guide.

Yes, this kind of guidance is indeed good and more important.


> I'm going to controversially suggest therefore we remove the markdown standard from the developer guide at all, which we've been doing ok without.

I have no violent objections to removing it. I value consistency in style however. If it turns out future PR authors are not being consistent with the existing style we can consider bringing it back.

**Comment by ong6** [comment]
I feel we should add a formatter first given that most people use auto format as a means to fix their basic layouts. But there's also no harm in adding a simple linter. I personally [markdownlint](https://github.com/DavidAnson/markdownlint) as well. 

Though the value of a linter may be limited (compared to a formatter) as different pages might **want** to have different layouts and a linter could be quite annoying by stopping user freedom.

**Comment by ang-zeyu** [comment]
> > Which, I really believe everyone has been doing a good job, and that "proof is in the pudding" here.
> 
> I don't mean to be overly critical here. We certainly have generated a ton of good content, by no means sub-standard. I am pointing out the room for improvement, which in my opinion is always something worth bringing up, especially in open source projects.

👍, not interpreted as such. Only meant for clarification on how I'm weighing my opinion .

> > My argument was for syntactic consistency, per the issue title.
> 
> While it is important to make documentation consistent FOR the reader, I am seeing a slightly less, but nonetheless valid concern about the consistency of our documentation code (don't forget, markdown is a lightweight markup language, which I feel comfortable enough to respect it in some regard, as "code"). Again, this is an open-source project, a collaboration done among multiple developers, across a totally different time frame. Important context.
>
> > My argument and analogy on the point with microsoft word is that these inconsistencies do not affect developer readability in any meaningful way, and / or are already enforced to a "good enough" degree by a natural tendency to adhere to the majority style in our documentation.
> 
> The problem with this analogy is that, for Microsoft Word/PowerPoint, the reference is missing the important context we have here: "multiple actors, across time". And just to make one case in this equal analogy: in Microsoft words, one can use multiple spaces to serve as a linebreak (pushing the content from one page to the next). While this works fine, whenever some content is added in the front, the spaces push the content on the next page further down. If a linebreak is used, the content on the second page will remain on top until the previous page is filled. Non-obvious choice, no immediate impact, could manifest in the future, when someone else is editing the document.

> slightly less

Indeed this is subjective. (in my opinion as long as its readable, its fine)

The microsoft word analogy is definitely not the most appropriate as well, as mentioned, and is not meant to be referenced to such a degree. But I do hope I got my general point and opinion across more clearly with it. 

Will leave the case for this to other folks pinged who can drop in on this. I realise as well I am going to be rather biased here as someone who has been keeping track of the documentation and code in evaluating the degree of this problem.

> This depends on what we do with https://markbind.org/devdocs/devGuide/styleGuides.html, because I believe while not explicitly stated as a reviewer's responsibility, this is enough for a developer to assume that there is a markdown code style that we ought to follow.
>
> The point of having such linting tools is exactly to make these pain points go away. For example with a slight barrier, we eliminate/greatly reduces the other efforts required. Hence this list is a little misleading in that they are not necessarily a package. (Some trade-offs may be required, but those trade-offs could be worth it)

Apologise for the miscommunication here: my entire post was made in view of my suggestion on removing the markdown style guide completely. (not just linting) In which case I do believe the points to be valid. (let me know otherwise)

i.e. If we were to put a style guide up there, then we should be consistently following it. In which case, a markdown linter would definitely help. If we don't follow a markdown style guide, then there's obviously no additional barrier to entry from not having a linter.

I'll edit the comment to reflect this more clearly.

> Even though Gatsby does not place an emphasis on this, others do: See examples [here](https://github.com/DavidAnson/markdownlint#examples). The point is not to find projects that do adopt this, the point is show that it can be done in reasonable fashion that other projects find it worthwhile.

My original (deleted) comment actually referenced how gatsby does not emphasize stylistic issues in there. (but discovered they actually do have a linter in code, though not sure of the specifics beyond that)

This quote is instead for pointing to reader readability issues mentioned in there, nothing more.

And yes, there are definitely large projects out there using this (and ones that don't), but each project has their own context, and I would be wary of drawing parallels here.

The best way to decide on this would be opinions from you guys.

> To be clear, I am not in favor of the argument over `-` or `*` when writing a list. I am open to exploring the existing rules and if they are useful (functional or otherwise), I am open to adopting them. If they are not, then we shouldn't be. In any case, we should not make it a false dichotomy.
> 
> I thank @ang-zeyu for providing your insights into the problem, which are indeed enlightening. From a project direction perspective, I'm in no position to push anything forward, and hence I should state here that this issue is more for discussion than anything (at least for me). Pinging @ong6 @kaixin-hc @jovyntls for thoughts and comments since they have been working on this project lately, and have written enough documentation to chime in.

> should not make it a false dichotomy.

Agreed.

---

> more for discussion 

I've been out of touch with the experience of developing PRs here largely for the past 2 years already, save for a few "administrative/smaller" PRs. This is my controversial "managerial" opinion, and I'm not going to necessitate we go in one direction or another. I realise all the more from this issue as well that opinions from you guys would definitely be the best way to go in resolving such issues that pertain to ground work.

That said, I would still like to inform your opinion with ⬇️, hopefully your experience with reviewing PRs in this short (except @jonahtanjz @ryoarmanda) span gives you some understanding here.

Perhaps to get some leadership on a conclusion here, we can leave the final decision (on whether to stick with the markdown style guide) to a slightly more senior dev @jonahtanjz or @ryoarmanda. (but feel free to drop your opinion! @MarkBind/active-devs)

> Do not forget:
>
> The time spent by N contributors over P PRs and K standards correcting things (which, even with a linter, adds up)
> The increased setup work needed to integrate linting tools for contributors and on our end
> The increased barrier to entry to getting contributors at all, which is paramount for an open source project
> The cognitive overhead for reviewers to impose such standards (which, even with a linter, adds up), distracting from reader > readability issues that do matter in documentation writing

**Comment by ang-zeyu** [comment]
Doing a few explicit pings to get the remaining opinions in this rather long thread / maze if you have the time 🙂 
@jonahtanjz @ryoarmanda @jovyntls @kaixin-hc 

Thanks for the dropping in so far @tlylt @ong6

**Comment by jovyntls** [comment]
Personally I would love to have at least a formatter to catch and fix inconsistencies in the docs if it can automatically fix these issues (similar to `npm run lintfix`). It could also be helpful for MarkBind users as well, so they don't need to manually configure their own linter.
If I am reading this discussion correctly, it seems that the concerns with this are: (1) the time and effort needed to implement and maintain a linter (along with prioritising it over other work), and (2) whether or not we should/need to enforce a coding style in our docs. 

On (1), I'm not very familiar with modifying existing linters for our custom uses, so I can't comment on whether or not the time/effort is worth the tradeoffs. I do have some concerns with handling edge cases in MarkBind syntax, especially since we use a combination of markdown + markdown-it plugins + HTML + nunjucks + MarkBind components. And as discussed by others above, I'd like to second the concern on maintainability (linter will have to be compliant with all future MarkBind components).  

If there is a viable and sustainable solution, I think the Markdown linter is a great idea. Though I definitely recognise that the time taken to find viable solutions is not trivial and will be quite significant for a challenging task like this. ☹️ 

On (2), I think we can consider starting to enforce a small set of rules for our docs. There are quite a few parts of the MarkDown guide that have value, e.g. using `1. 1. 1.` for lists as mentioned above, and the point on [line wrapping](https://se-education.org/guides/conventions/markdown.html#:~:text=Do%20not%20wrap%20lines%20at%20a%20specific%20length.%20Coding%20standards%20for%20other%20languages%20typically%20specify%20a%20maximum%20length%20for%20a%20statement.%20However%2C%20Markdown%20is%20used%20to%20write%20natural%20language%20content%20which%20should%20not%20be%20chopped%20into%20a%20sentence%20fragments.). If this is not enforced by a formatter/linter, I think it would be good to have an agreed-on set of rules that we can fall back on and enforce. We can keep this set of rules small and purely functional, in line with the philosophy of prioritising readability for developers.

> I'm going to controversially suggest therefore we remove the markdown standard from the developer guide at all, which we've been doing ok without. 

I think instead of removing it altogether, we can incorporate elements of this discussion into our DG markdown guide (or at least mention docs guidelines somewhere), by stating that we prioritise readability and do not enforce a specific standard. 
When I was starting out on the project, I actually found the MarkDown guide helpful as an assurance that I wasn't blatantly violating any coding standard that I wasn't aware of :)  So I do think there's value in addressing our stance towards documentation formatting in our devdocs.

> I feel we should add a formatter first given that most people use auto format as a means to fix their basic layouts. But there's also no harm in adding a simple linter. I personally [markdownlint](https://github.com/DavidAnson/markdownlint) as well.

I think this is a good point to differentiate between a formatter and a linter! A linter may not be necessary since our docs will be parsed by MarkBind, which would catch most syntax errors (or can be improved to catch more syntax errors, if it's within the scope of MarkBind's purpose).

**Comment by kaixin-hc** [comment]
I think most points have been said and the discussion has been quite lively! I personally really like the suggestion:
> As a first-step/low hanging fruit, we can document the existence of such tools and provide a MarkBind friendly config file in our DG, for anyone who's interested. This is similar to the debugger settings that we currently have for VScode/webstorm. This is focusing on helping the developers while not enforcing the rules via strict linter checks before push/merge.

I use markdownlint to catch my formatting inconsistencies when I write markdown already. I expect making such tools and configurations more visible will make those reviewing more sensitive to checking their work for consistency and clarity. It would also just be convenient for me 😂 .

Responding to:
> The biggest case in point I am raising therefore is that we have been doing ok for the past 2 years (and then likely even before that for 3 years) (MarkBind is ~5 years old) without a markdown syntactic consistency standard.

I think it's possible that the markdown syntactic consistency standard has contributed to this as well. As new contributors, I know that I double and triple checked the style guides before making PRs, and Jovyn has also shared that reviewing the short list of rules has helped her PR with confidence. Is it possible that most new developers have also quietly read and adhered to the style guide? The existence of the rules might have reduced the number of inconsistencies by creating a shared standard that all developers can reference - even if they rarely need to be enforced.

Overall:
* I have a slight preference for having the Markdown style guide - the rules included are short and common-sense, and not difficult to adhere to. Explicitly stating the rules is also a comfort. (In the case the guide is removed, I think explicitly stating the absence of a style guide will be helpful for nervous new contributors).
* We might want to update the style guide with MarkBind specific rules - like a space after <box> or <panel> in order to ensure the formatting inside the element is parsed correctly in all cases. Or like forgetting a blank line above a table. These are technically documented, but not easy to reference when debugging.
* Potential documentation about how to write in a more user-friendly way is unlikely to be necessary, as a lot of the advice is common sense and I think will naturally emerge during a PR review

**Comment by jonahtanjz** [comment]
> As the amount of our documentation grows, it's nice if it's follows a consistent style, although we don't want to be overly prescriptive.
Some style rules actually have tangible benefits and help to educate the writer (the writer may not be aware of those benefits or those syntax options). e.g., using 1. for every item in numbered lists

I do agree that having a markdown linter for our documentation would be good as this will keep the styling and coding standard there consistent.

> To give one example, we modify the markdown/html parser to allow parsing things like <puml>, which can contain almost anything. The linter likely won't be able to accomodate this as nicely.

However, we have to take note that MarkBind combines a lot of custom syntax that works together with Markdown. Other examples that I think will be hard for the linter to detect is Markdown within `header` or `content` attributes in components like `panel`s or `popover`s etc. In such cases, I doubt it will be easy to configure the linter to catch any styling inconsistency for these Markdown syntax.

Unless we can figure out a way to detect these, I don't think it's a good idea to strictly enforce a linter as there will be inconsistency. "Bad" Markdown syntax may get away and new developers not familiar with the coding standard of Markdown may think that these are fine (since it passes the linter test). We want to avoid this kind of inconsistency in our style guide and rules.

> As a first-step/low hanging fruit, we can document the existence of such tools and provide a MarkBind friendly config file in our DG, for anyone who's interested. This is similar to the debugger settings that we currently have for VScode/webstorm. This is focusing on helping the developers while not enforcing the rules via strict linter checks before push/merge.

With that being said, I think having the idea of an optional linter is fine. Something like the above.

**Comment by tlylt** [comment]
Revisiting this Issue for a resolution in the near future...

My original concerns:
1. Our Markdown style guide is in place but is neither strictly adhered to nor consistently checked. This has led to instances of inconsistency within our documentation.
2. While creating new documentation, I often refer to existing content nearby. This practice may perpetuate further inconsistencies.
3. Inconsistencies and non-compliant documents are sometimes identified during code reviews, leading to: 
   a. Additional effort for reviewers to identify and comment on these issues.
   b. Requirement for PR authors to undergo another iteration to rectify these issues.

In summary, these issues contribute to potential frustration experienced by MarkBind developers when making PRs related to documentation.

Follow-up per original discussion:
1. Observation Period: Over the next few months, we can monitor the situation. If this issue becomes irrelevant, we will maintain the status quo and close it.
2. Should the need arise, let's make this issue into an exploratory task to experiment with a linter. This will involve assessing its impact on various aspects like the number of file changes, effects on git history, and alterations to the developer workflow. Based on this assessment, we will decide whether to make this step mandatory or optional, or to close the issue entirely.
