### ISSUE TITLE
Modal not working correctly in UG Page Navigation Menus section

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1909]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 10

### MarkBind version

3.1.1

### What did you do? Describe the bug

Click on the modal trigger in https://markbind-master.netlify.app/userguide/syntaxcheatsheet page-navigation-menus, two modals opened for that.

### Steps to reproduce

- Enter https://markbind-master.netlify.app/userguide/syntaxcheatsheet
- Go to Page Navigation Menus
- Click on the `Example usage of the <page-nav /> component`

### Expected behavior

Expected to behave normally like in https://markbind.org/userGuide/syntaxCheatSheet.html

### Actual behavior

Open two models
![](http://g.recordit.co/UGbL7vBW4A.gif)

### Anything else?

Other pages seem to work fine. Wonder if it's due to the Bootstrap update, @jovyntls any idea?

**Comment by jovyntls** [comment]
The top-left positioning seems to be caused by putting a modal in a panel header, which could be messing with the positioning of the modal.

I haven't verified this, but I suspect the two modals appearing at once is caused by having two modals with the same ID in the same page? i.e. the top-left one is from the panel header, the centred one is from the panel contents.
