### ISSUE TITLE
id collision with markdown headings will result in incorrect anchor scrolling effect

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1915]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 10

### MarkBind version

Master branch and v3.1.1

### What did you do? Describe the bug

Specify an id in a div, which happens to be the same as the id generated by a markdown heading. The bug is that the scrolling will result in the heading being hidden under the top bar.

### Steps to reproduce

In a `.md` file, specify the following:

```md
<div id="test">

# test
Some text

</div>
```
Then serve the page and click on the anchor icon beside the "test" heading

### Expected behavior

To scroll to the top correctly, and show something like:
![image](https://user-images.githubusercontent.com/41845017/165303313-5cd36959-f3b5-4ce0-af8d-1ba5be58855c.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/41845017/165303379-f410193a-9e94-4249-9d3f-78a0242b595c.png)

### Anything else?

Could be due to the same id.
![image](https://user-images.githubusercontent.com/41845017/165303466-4da3fb0c-d659-4b70-9402-3deacb8c7f54.png)

**Comment by jonahtanjz** [comment]
Thanks for raising this issue @tlylt 

For this I can think of 2 possible solutions:

1. When setting the heading `id`s for the anchor navigation, we can try to avoid generating `id`s that already exist on the same page, similar to how duplicate heading titles are handled currently in [`setHeadingId`](https://github.com/MarkBind/markbind/blob/master/packages/core/src/html/headerProcessor.js#L12). However, this would mean that we will need to store all the `id`s of the page before generating the heading `id`s. This step is currently done in the [_process](https://github.com/MarkBind/markbind/blob/master/packages/core/src/html/NodeProcessor.js#L310) method, so we will not be able to tell what are all the existing `id`s at that point. We will need to move this step to after all the nodes are processed.

2. The other simpler solution is to prepend/append the generated `id`s for the anchor navigation with some fixed value that is uncommon instead of using only the titles (e.g from `id=<title>` to `id=anchor-nav-<title>`). This can similarly be implemented within the [`setHeadingId`](https://github.com/MarkBind/markbind/blob/master/packages/core/src/html/headerProcessor.js#L12) method.

For solution 1, it is guaranteed that there would not be any duplicates and users will not have to do anything but will be hard to implement. For solution 2, there will still be a possibility of having duplicates but low chance of it happening (we could also add in the user guide to let users know not to set any `id`s in the form `anchor-nav-<title>`). Feel free to suggest other possible solutions :)
