### ISSUE TITLE
Replace use of deprecated `url.parse`

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#1944]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

Code Quality, Security

### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/41845017/171970633-ff3ed599-07ec-471c-839b-585bc99966c5.png)

### Describe the solution you'd like

Replace the use of `url.parse` with another API

**Comment by domlimm** [comment]
Hello, I would love to pick this up as my first issue if that's okay! 😃

**Comment by ang-zeyu** [comment]
Please do @domlimm 🙏. Thanks for taking this up!

**Comment by domlimm** [comment]
@ang-zeyu Thanks, cheers!

I have taken a look at the setup instructions. A little confused as to how I can test if the changes for this issue work.

Have already run `npm link` and `markbind` can be used via my forked root directory terminal.

Appreciate if you could please point me in the right direction! 😄

**Comment by ang-zeyu** [comment]
There are a couple of usages in both the development server we spin up for the content author and build code, so it would be best to test both functionalities.

1. Run `npm run build:backend` in the root directory to build our typescript code
2. To the test former, run `markbind s -d` inside the `docs/` folder. Try editing a few files then see if the live preview functionality still works (you should see your changes reflected almost immediately)
3. For the latter, you can run our functional tests with `npm run test` (in the root directory)

> A little confused

We've recently shook up our development environment a fair bit with the addition of typescript, the documentation might still be lacking in this regard, or other areas too.
Please help to point out any issues / hiccups in there! 😶.

**Comment by domlimm** [comment]
Hello, thanks for typing that @ang-zeyu! I guess will be more familiarise once I explore more. But right now lines 1 and 2 work for this issue! 😃 

I have been stuck at this for awhile and this is what I have so far:

I have been getting `TypeError [ERR_INVALID_URL]: Invalid URL` and realised that `req.url` is equals to just `/` at my end. Maybe because it's `localhost`?

However, it's odd that when using the original codes in `master` i.e. `var reqpath = isFile ? "" : url.parse(req.url).pathname;` I am able to get the FE page running...

![image](https://user-images.githubusercontent.com/46486515/183724961-dfd08f92-9949-4b78-b30e-aa5857be87fe.png)

**Comment by tlylt** [comment]
> Sorry I have actually started working on this issue in the afternoon yesterday but been facing the issue above, but after some findings it's clearer now. Will keep looking. I understand that as what Yong Liang has said, we just need to utilise another API which I suppose is Node's WHATWG URL API.

Yes, I was looking for an alternative API (that has not been deprecated) to replace `url.parse`. If I remember correctly, you might have to research a bit and do some custom handling, in order to ensure that the new API you choose can result in the same expected behavior as before 🦾
