### ISSUE TITLE
Embed PPT feature clips when mobile width is small

### ISSUE THREAD

**Issue by ong6** [MarkBind/markbind#1952]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#1797 

### Tell us about your environment

Windows 10

### MarkBind version

3.1.1

### What did you do? Describe the bug

This is a continuation of PR #1797 as that PR does not fix the behavior of ppt embeds at low screen sizes. 

As can be seen from this screenshot, the right side is getting cut off:
![image](https://user-images.githubusercontent.com/19247856/175819995-5b5ab6cc-aba3-4414-92b5-128c9bb92ce4.png)

The proposed solution is mentioned by @ang-zeyu as follows:
> Keep the best of both worlds. That is, while keeping the aspect ratio, scale the ppt embed after some minimum width threshold (we can just use the existing fixed width as one), but otherwise, the embed should minimally be kept at that width. Hint in the first 2 paragraphs in this https://github.com/MarkBind/markbind/pull/1797#discussion_r846779449.

(also read the PR thread to get more insight)

### Steps to reproduce

1. from root navigate to the docs folder `cd docs`
2. run `markbind serve -d` and go to the embeds page with the PowerPoint embed.  
3. `Ctrl + shift + i` or go into the developer mode and change dimensions to responsive.
4. At a 100% zoom, set the width to 320px

After following these steps, you should see the screenshot above.

### Expected behavior

Aspect ratio of the ppt embed should be preserved, instead of it being cut off like in the screenshot.

### Actual behavior

PPT embed gets cut off on the right side due to scaling issues.

**Comment by kaixin-hc** [comment]
After reading the thread, and looking at the screenshot, one of the original issues were the bottom buttons were cut off, making a ppt embed unusable on mobile. This has since been fixed, and the simple solution chosen was the simple one of the ppt embeds being a fixed size that the user should scroll to view.

Here's a video of what it looks like now, just to make it clearer: 

https://github.com/MarkBind/markbind/assets/59471320/41070c4a-e3d0-4216-90dd-d28a9c2fc086

[This comment](https://github.com/MarkBind/markbind/pull/1797#discussion_r900702912) is the one linked in this PR, proposing the alternate solution requested in this issue and some additional areas to look at in the future. The discussion also spanned "usability" vs "looking nicer" - my own two cents is that the current solution is pretty usable, and additional effort might necessarily lead to a better solution. 

Unless someone has particular interest in taking this up to explore CSS, I think we can argue that this isn't a bug to be fixed anymore and just a product decision.

**Comment by yucheng11122017** [comment]
Looks good to close
