### ISSUE TITLE
Minimal panel button wrapper is on the next line

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#1979]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Anything

### MarkBind version

4.0

### What did you do? Describe the bug

![Untitled](https://user-images.githubusercontent.com/3306138/182011476-030fd0be-c9ea-4085-8241-6de66af5fbe8.png)

Probably a regression from: https://github.com/MarkBind/markbind/pull/1694

In particular:
- https://github.com/MarkBind/markbind/pull/1694#pullrequestreview-860602847 (cc @jonahtanjz for context on what it was trying to solve if any, we should try to preserve both desired behaviours)
- https://github.com/MarkBind/markbind/pull/1694/commits/b435cc3b53c8224872d0abdad3e05b8ef640f677

**Comment by jonahtanjz** [comment]
> (cc @jonahtanjz for context on what it was trying to solve if any, we should try to preserve both desired behaviours)

I think it was because `display: inline-block` was shifted from the `.button-wrapper` class in `NestedPanel.vue` to the `.glyphicon` class but since the glyphicon css already has the rule, we decided to remove it and forgot to shift the `inline-block` back to `.button-wrapper`. 

Thanks for the catch @ang-zeyu :)
