### ISSUE TITLE
The page becomes unscrollable after opening and closing modal

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2008]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

n/a

### MarkBind version

4.0.0

### What did you do? Describe the bug

See https://github.com/nus-cs2103-AY2223S1/forum/issues/1

**Comment by tlylt** [comment]
Some preliminary investigation:
- the problem is due to the fact that after a modal is opened, `style="padding-right: 17px; overflow: hidden;` will be added to the `<body>` to prevent scrolling the content behind the modal. However in the problematic case, the `style="padding-right: 17px; overflow: hidden;` is not removed when the modal is closed (if it does, then there's no problem).
- for the problematic modals, it seems like they are the ones that have been referenced in more than one places. So for example the [`cloning`](https://nus-cs2103-ay2223s1.github.io/website/schedule/week2/topics.html#tools-git-and-github-clone-copying-a-repo) section, which is also referenced below via include embed, in the `pull` section.
  - their source code  (view raw)  in https://github.com/se-edu/se-book/blob/bb291347ddd56f86b120daa7cf03920e5a5d58c7/gitAndGithub/clone/text.md and https://github.com/se-edu/se-book/blob/bb291347ddd56f86b120daa7cf03920e5a5d58c7/gitAndGithub/pull/text.md
  - removing the include in the pull section resolves the scroll issue temporarily
![image](https://user-images.githubusercontent.com/41845017/184463423-7bc197ab-4f27-4371-b1e0-45ead1238779.png)
![image](https://user-images.githubusercontent.com/41845017/184463447-fc60de3f-ecae-48d4-bc7c-af19b792272f.png)

Pinging @jovyntls :) if you have any context or encounter of this issue during the migration to vue-final-modal? Seems like this and the duplicate modal issue are likely linked to the migration.
- the duplicate modal issue also shows up in the 2103T website, in https://nus-cs2103-ay2223s1.github.io/website/schedule/week2/topics.html#tools-git-and-github-pull-fetch-downloading-data-from-other-repos by clicking on `[Git & GitHub → Clone]` and then `cloning`

**Comment by damithc** [comment]
Thanks for the quick investigation @tlylt Good to know that it doesn't affect every modal. Let's see if someone can fix this quickly.
