### ISSUE TITLE
Consider running tests/lints before pre push

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#2021]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

DevOps

### Is your feature request related to a problem? Please describe.

I'm always frustrated when I push my code up only to have it fail in CI 10mins later, due to forgetting to run tests / lints.

### Describe the solution you'd like

Consider running tests / lints before push.

A more controversial one would be pre commit. 

Notes:
- This can still be prevented using `git push --no-verify`.
- (maybe overkill for this project, pointing out this for ideas / research) https://pre-commit.com/

**Comment by tlylt** [comment]
Related to #1966 on precommit.

**Comment by EltonGohJH** [comment]
I will give this a try

**Comment by tlylt** [comment]
> I will give this a try

Previously played around with it for some time and realized there are a few things to take note (some details are in https://github.com/MarkBind/markbind/issues/1966)

- for linting, it would be faster if we only lint files that have changed, which requires some configuration in order to make it work. As we have a few different eslint configs for different packages, there's a need to ensure that the current configs are still respected when linting via hooks
- for testing, there might be a problem when the backend is not built (due to our typescript setup), this means if the backend is not ready and we run the test via hooks, the test will fail unless we do a `npm run build:backend`. If somehow the backend is not automatically built, then running the tests before pre-push might fail unexpectedly.

**Comment by tlylt** [comment]
Fixed by #2035
