### ISSUE TITLE
Omit pageNav element if there are no navigable heading to remove unnecessary separator

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#2055]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 10

### MarkBind version

Master branch

### What did you do? Describe the bug

![image](https://user-images.githubusercontent.com/41845017/207470997-7e31d1e2-c29e-440a-9f53-6ed497996a2d.png)

### Steps to reproduce

- `markbind init`
- go to `contents/topic1.md`
- add the following:
```
<frontmatter>
  layout: default.md
  pageNav: 2
</frontmatter>
```
- remove the default `# Topic 1`
- run `markbind serve -d`
- view the topic1 page

### Expected behavior

- If there are no navigable headings and no page title, the separator should not appear (the whole pagenav should be omitted)
- If there are page title, just show the page title

### Actual behavior

See screenshot above

**Comment by domlimm** [comment]
Hey YongLiang! Could I look into this issue?

**Comment by domlimm** [comment]
hello @tlylt! sorry it's been awhile since i touched markbind. im having troubles when i run `markbind serve -d`. i get brought to the local markbind directory on `localhost:8080`. kinda stuck on how to start up the frontend. could i please get some help? 😭

![image](https://user-images.githubusercontent.com/46486515/208054466-ce42545b-c68e-4f81-bb5b-83a5b2446305.png)

i get a bunch of errors too when i run `markbind serve -d`. not sure what am i missing out on for the setup..

![image](https://user-images.githubusercontent.com/46486515/208054417-f9f6dc5d-4977-4afa-a405-b3125a54cc0f.png)

thanks so much!!

**Comment by tlylt** [comment]
@domlimm have you tried `npm run setup` to reset the markbind master branch first? also may need to ensure that your fork and local master branch are up-to-date.

For the serve, are you serving the docs or your test repo? If so you may want to `markbind init` again just in case your old test repo is no longer compatible

**Comment by domlimm** [comment]
@tlylt thanks for your lightning quick reply!

**have you tried npm run setup to reset the markbind master branch first? also may need to ensure that your fork and local master branch are up-to-date.**
yes, i have done this!

my fork is on par with master!
![image](https://user-images.githubusercontent.com/46486515/208055752-8382c13e-f2c2-4edd-85a7-7ab446651a98.png)

**For the serve, are you serving the docs or your test repo? If the latter you may want to markbind init to get a fresh site again just in case your old test repo is no longer compatible**
hmmm... this im not too sure. i remember the last time i just ran `markbind serve -d` from the root folder.

i have run `npm run build:web` too.

![image](https://user-images.githubusercontent.com/46486515/208056321-391c1243-a0e6-4d77-b7f3-51126cf35deb.png)

**Comment by domlimm** [comment]
okay i think if i remember correctly, the previous time i `markbind init` and another folder was created. i ran the fresh site then from the new folder.

sorry a little confused with the setup to get started. trying to recall and will write it down 🤣

**Comment by tlylt** [comment]
> hmmm... this im not too sure. i remember the last time i just ran markbind serve -d from the root folder.

If you want to serve the markbind docs, `cd docs` then `markbind serve -d`

For testing, I would also typically create a site via `markbind init` in a separate folder, and run `markbind serve -d` in that folder to make changes to test

**Comment by domlimm** [comment]
ah okay! that makes sense. yup that's how the setup goes. i understand now, thank you yl!!

**Comment by domlimm** [comment]
hey @tlylt! i have a few questions if you don't mind..

1. for this issue, should we be looking from `markbind\packages\core\src\Page\index.js` to omit the pagenav? from my research, this file's methods parse/process all the content to build the page contents and passes it onto `Layout*.js` for further processing. also as for the Vue components, it seems like the components are provided with data and not really the right place to look at for this issue. please correct me if i'm wrong. a little lost on where i should start to solve this bug. i have only meddled with the Page, LayoutManager and Layout files with log statements to see how the data is processed from the `*.md` files.
2. how can we test for the changes on the testing folder (i.e., When we make a new folder and run `markbind init`, etc.) after editing on the working folder? 

thank you!

**Comment by domlimm** [comment]
hello @tlylt,

> This issue came about when I was working on PR https://github.com/MarkBind/markbind/pull/2054 (pls feel free to give a PR review if you wish). I was thinking it should probably work if I adjust the method that generates the pageNav html output in index.js accordingly. Feel free to experiment around and see if that works (probably need to double check whether the whole vue component portal to layout for pageNav will have any errors or not)

i have just taken a look at it! anyway, i'm not sure if this is a false positive, i have only added this and it seems like the line is removed and the bootstrap error seems to have disappeared:

![image](https://user-images.githubusercontent.com/46486515/208125544-e36c5318-c79b-4b9a-ab38-c6ce383cc91a.png)

> If you set up the markbind project correctly, when you use markbind serve or markbind serve -d etc, it should be calling from your local markbind copy, so whatever changes you made will be executed without any issue. For changes that affect typescript files, you may need to re compile, see dev docs for more details.

For me, I usually make some changes to source code, then make some changes to the test site to trigger certain features, then run markbind serve -d to see the updated output. Then if I need to make more changes to the source code, I think I will need to stop the test site, and rerun markbind serve -d so that the changes are reflected.

ah okay! yeah that's what I was thinking too, wanted to confirm. because we use `npm run link`. thanks so much for the advice yl!

**Comment by domlimm** [comment]
hey yl, just an update both errors are gone with the current attempt which can be found in the PR linked to this issue for your review please. maybe there is a better way, let's discuss! thanks!!
