### ISSUE TITLE
Modal doesn't appear in CS2103 website - team based tasks

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2064]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#2008

### Tell us about your environment

n/a

### MarkBind version

4.0.2

### What did you do? Describe the bug

See https://github.com/nus-cs2103-AY2223S1/forum/issues/399

### Steps to reproduce

n/a

### Expected behavior

n/a

### Actual behavior

n/a

### Anything else?

n/a

**Comment by damithc** [comment]
Bumping this up, as it looks like we didn't get around to resolving this.

**Comment by WillCWX** [comment]
Issue is caused by the parent pop-up being invisible

The main culprit is in the file `tp-ped-fragment.md` which has a modal that has no trigger

```html
<modal large header="Admin {{ icon_embedding }} Project →" id="modal:v1.3-ppp">
  <include src="tp-deliverables.md#tp-deliverables-ppp"/>
</modal>
```

`tp-deliverables.md`
```html
<span id="tp-deliverables-ppp">
<include src="tp-deliverables-ppp-fragment.md" />
</span>
```

![image](https://github.com/MarkBind/markbind/assets/55905659/2cfa39cf-36a8-4f73-8553-a1d80652c1b1)


As this is processed first, this causes `tp-deliverables-ppp-fragment` to be the parent pop-up and then the `team based tasks` to be its child pop-up.

Hence, when we click the `team based tasks`, the pop-up occurs but is invisible as the parent pop-up is invisible. The page may also become unscrollable in some instances.

![image](https://github.com/MarkBind/markbind/assets/55905659/000fe2ae-55d4-4d38-adea-75bd607de40c)


Removing the modal fixes the issue. (Checked by `markbind serve` on the fix)

**Comment by damithc** [comment]
@WillCWX great work figuring out the issue 💯  Yes, that fixed the problem.
