### ISSUE TITLE
Modal makes the page unscrollable in CS2103 website print.html

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2065]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#2008

### Tell us about your environment

n/a

### MarkBind version

4.0.2

### What did you do? Describe the bug

See https://github.com/nus-cs2103-AY2223S1/forum/issues/480

### Steps to reproduce

n/a

### Expected behavior

n/a

### Actual behavior

n/a

### Anything else?

n/a

**Comment by jovyntls** [comment]
Seems to be caused by some of the source code in the vue-final-modal library, [here](https://github.com/vue-final/vue-final-modal/blob/5812ea78dcbfe1488fbf7a3edc70d156dc0cdfaa/lib/utils/bodyScrollLock.js#L85-L120)

Usually the body overflow will be restored to its previous state, but in this case it is not (not sure why). We could manually restore the overflow value in the modal component?

**Comment by jonahtanjz** [comment]
I think this is a similar issue to #2025. Seems to be caused by hydration issue in [this specific line](https://github.com/se-edu/se-book/blob/91c267af1b7578c60209041705b74fe429ec37ae/modeling/modelingASolution/basic/text.md?plain=1#L69) (block level element inside `<p>`).

![image](https://user-images.githubusercontent.com/47470981/212036112-65313306-0853-4833-b1ef-8f306c6909dc.png)

**Comment by damithc** [comment]
Yup, that fixed it. Thanks @jonahtanjz
