### ISSUE TITLE
How do we use milestones in PRs (and releases)?

### ISSUE THREAD

**Issue by jovyntls** [MarkBind/markbind#2142]
Currently, when reviewing PRs, we assign milestones to PRs after the first approval, as stated in the DG:

> Once the first approval is given from a developer, assign a version milestone to the PR (this is usually the next version, unless there is a justification for delaying the merging to future versions).

1. If we want to delay the merging to future versions, do we keep the PR un-merged until the desired milestone is the next milestone? If so, should we create (and document) a label for such PRs that indicate the delayed merging?
2. Should we always assign the milestone as the next version? This seems to contradict semantic versioning, where we should increment the patch version for bug fixes and the minor version for backwards-compatible feature additions. 
3. How do we currently use PR milestones in releases? I've noticed some discrepancies in the milestone assigned to the PR and the release that it's included in:
	- No milestone, included in v3.1.0: #1653, #1654 
	- Milestone is 3.0.7, included in release v3.1.0: #1636 
	- Milestone is 3.0.0, included in release [v2.17.3](https://github.com/MarkBind/markbind/releases/tag/v2.17.3) (and also v3.0.0?): #1419 

If these concerns are valid, maybe we could document the role of the milestone in PRs, and how PR milestones are used releases?

**Comment by jonahtanjz** [comment]
From my understanding, the milestones are mainly there to facilitate in the tracking of the changelog during release (filter out the relevant PRs).

In terms of naming of the milestones, we will usually start off by assigning PRs to the next patch version (following semver convention) so that we can easily do a patch release if required. If at any point we introduce PRs with new features or breaking changes, our next release will have to be a minor or major change respectively. All PRs after this should be assigned to the latest milestone. If there are any PRs that were assigned to an "unreleased" milestone, they will be part of the new release as well.

For example (if our current version is `4.0.2`):
1. Merge a PR (patch in nature) - assign to milestone `4.0.3`
2. Make a patch release `4.0.3` - our next milestone will be `4.0.4`
3. Merge a PR (patch in nature) - assign to milestone `4.0.4`
4. Merge a PR (contains breaking changes) - assign to milestone `5.0.0`, all future PRs should be tagged to this version
5. Make a major release `5.0.0` - this will include both the PRs tagged with `4.0.4` and `5.0.0`

Since we don't usually cherry pick our commits in the master branch during release, the above should work. The exception is that if we need to do hotfix releases (for urgent bugfixes but we already have major changes in the master branch etc.), we will first create a new branch from the last release commit, then create PRs that target the hotfix branch. With this approach, we can still merge major changes into the master branch without delaying the PRs.

**Comment by tlylt** [comment]
Hi @jonahtanjz, just to make sure it's clear, using the current status as an example:
- we are currently at v4.0.2
- we have patch PRs merged in and tagged under v4.0.3
- we also have minor PRs merged in and tagged under v4.1.0

If we are going to do a release now, the version that we will use is v4.1.0, which includes all the PRs merged in since v4.0.2 ?

**Comment by jonahtanjz** [comment]
> If we are going to do a release now, the version that we will use is v4.1.0, which includes all the PRs merged in since v4.0.2 ?

Yup, the release version should be `4.1.0` and it should include all PRs assigned to both `4.0.3` and `4.1.0` :)

**Comment by tlylt** [comment]
With the use of patch, minor, major tagging, I was planning that we remove the need to add milestones since it's only used to identify the  next release version. This is so that we can avoid the scenario of adding PRs to the next minor version and then suddenly have a major update PR...

**Comment by kaixin-hc** [comment]
That makes a lot of sense to me! @MarkBind/active-devs how do we feel about stopping using the milestones to label PRs?

**Comment by yucheng11122017** [comment]
> That makes a lot of sense to me! @MarkBind/active-devs how do we feel about stopping using the milestones to label PRs?

to be honest... we haven't be doing that in a while haha

**Comment by tlylt** [comment]
> to be honest... we haven't been doing that in a while haha

If @yucheng11122017 and @itsyme can confirm that we were able to create releases without the need for milestones (replaced by the SEMVER labelling), then the remaining TODOs for this issue are to
- [ ] close the milestones in https://github.com/MarkBind/markbind/milestones
- [ ] remove the "Set a milestone to the PR." and "Update milestones." steps in https://markbind-master.netlify.app/devguide/projectmanagement
