### ISSUE TITLE
Fix panel transition abruptly "snapping" under certain circumstances

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#2185]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Desktop Chrome + Mobile Andoid Chrome

### MarkBind version

Latest main branch

### Describe the bug and the steps to reproduce it

![panelheighttransitionbug](https://user-images.githubusercontent.com/3306138/220949938-853dbc81-3893-4fba-a7df-70da5eed5f24.gif)

Under certain circumstances, the panel expansion transition abruptly snaps to the end.

### Expected behavior

The transition should continue smoothly all the way.

**Comment by tlylt** [comment]
- [Link](https://markbind.org/userGuide/components/presentation.html#panels:~:text=%3C/panel%3E-,OUTPUT%3A,-Right%20click%20and) to an example panel > `Right click and inspect my HTML before expanding me!`
- The issue is that the opening animation will "speed up"/"end abruptly" when reaching the end of the panel content
- It seems to be reproducible whenever the content of the panel is more than 1 line, especially if it contains something like: line + linebreak + line.

Minimal reproducible examples:
```
<panel header="Normal Panel">
Some Text
</panel>

<panel header="Problematic Panel">
Some Text

Some Text
</panel>
```

I'm guessing that it might have something to do with the rendering of the "back to top" button.
![image](https://user-images.githubusercontent.com/41845017/223017405-3f56c7fd-a72d-4a9d-910d-4fa04b676596.png)

**Comment by yucheng11122017** [comment]
When the panel bottom-switch is set to false, this problem does not seem to happen. 
Also does not occur when the text is very long and wraps to more than one line without any line breaks.

**Comment by yucheng11122017** [comment]
I believe the problem is as follows

1. The panel is opened,
2. The max height of the panel is set to the [scroll height](https://github.com/MarkBind/markbind/blob/master/packages/vue-components/src/panels/PanelBase.js#:~:text=in%2Dout%27%3B-,this.%24refs.panel.style.maxHeight%20%3D%20%60%24%7Bthis.%24refs.panel.scrollHeight%7Dpx%60%3B,-%7D) of the panel which does not include the height of the panel-switch for some reason. The transition uses this value. 
3. When it finishes the transition, the [max height is set to none](https://github.com/MarkBind/markbind/blob/master/packages/vue-components/src/panels/PanelBase.js#:~:text=panel\)%20%7B-,this.%24refs.panel.style.maxHeight%20%3D%20%27none%27,-%3B) which is when the entire panel with the scroll button is displayed. This does not have a transition, resulting in the abrupt transition

**Comment by lhw-1** [comment]
As mentioned [here](https://github.com/MarkBind/markbind/pull/2200#issuecomment-1469373312), the original issue with the abrupt snapping seems to not occur on FireFox Ver. 110.0.1 (on Windows 10), but does occur on Google Chrome Ver. 111.0.5563.65 (also on Windows 10).
