### ISSUE TITLE
Consider removing/reordering for Travis CI or adding a warning

### ISSUE THREAD

**Issue by yucheng11122017** [MarkBind/markbind#2264]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

Windows 10

### MarkBind version

V4.1.0

### Describe the bug and the steps to reproduce it

Travis CI has a problem with their [accounts ](https://travis-ci.community/t/exceeded-user-count-unlimited/10484/49) which blocks users from using it. Plus it is the only CI that requires a credit card. 
But it is currently listed as the first CI platform (besides Github Pages) which may led users to use this first. 

### Expected behavior

1. Either remove instructions on deploying using Travis 
   - But kind of wasted to just remove it
2. Reorder to put Travis at the end 
3. Add a warning about the problems with Travis listed above.

**Comment by tlylt** [comment]
Seems to have a response for the problem mentioned: https://travis-ci.community/t/exceeded-user-count-unlimited/10484/50

Agreed that we may not want to recommend this approach due to the points mentioned.

> 1. Either remove instructions on deploying using Travis 
>    - But kind of wasted to just remove it
> 2. Reorder to put Travis at the end 
> 3. Add a warning about the problems with Travis listed above. 

Let's reorder. I don't recall needing credit card but I'm not sure of the latest state of Travis CI. Instead of warning, we can add a note about the constraints.  It should link to their official website and state the date that we observed the issue/problem, as things may change in the future.

**Comment by tlylt** [comment]
I had the impression that Travis CI is mentioned first but in https://markbind-master.netlify.app/userguide/deployingthesite
it's actually not. I think it's ok to add a warning if necessary, but there's no need to reorder.

**Comment by ang-zeyu** [comment]
> I think it's ok to add a warning if necessary

I'll close this as it seems like a generic bug. Any communication should be with Travis CI.
