### ISSUE TITLE
Use markbind instead of markbind-cli in npm

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#227]
Should we change to `markbind` instead of `markbind-cli` in npm?

**Comment by acjh** [comment]
[`markbind`](https://www.npmjs.com/package/markbind) is the core library, which handles many things without writing to files.
This makes more sense as the main package name, to be used as a dependency.

[`@angular/cli`](https://www.npmjs.com/package/@angular/cli) has a similar convention.

@Gisonrg Your thoughts?

**Comment by Gisonrg** [comment]
I don't have any preference. Many projects use `PROJECT_cli` as the npm package you need to install to run the application (e.g. [gitbook](https://github.com/GitbookIO/gitbook/blob/master/docs/setup.md#install-with-npm))
Personally I guess as long as the final command we type in terminal is `markdown` we are fine. Changing name is not high priority though, and is actually a pretty tedious process because you also need to update dependent libraries / tools used. Those time could be better put into bug fixing / feature development :P

**Comment by acjh** [comment]
> Personally I guess as long as the final command we type in terminal is `markdown` we are fine.

I believe you mean `markbind` 😉

**Comment by damithc** [comment]
If it is common-enough practice, we can follow the same. After all, one day we might have a markbind-gui :-p
I'll close this for now.
