### ISSUE TITLE
site.json: Give an easier way to specify which files to exclude from the build process

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#228]
If there's a directory that the user does not want MarkBind to traverse during the page rendering, he must modify the glob's regex to specifically exclude such directories. For example:

`"**/index.md"` --> `"{,!(book)/**/}index.md"`

to exclude `index.md` files residing in `book` directories.

I suggest that we provide a user an alternative way to ignore entire directories directly with an `"ignore"` parameter for `"pages"`:

```json
  "pages": [
    {
      "glob": "**/index.md"
    },
    {
      "ignore": "book/"
    },
```

**Comment by acjh** [comment]
I feel that this isn't appropriate as `glob` explicitly asks MarkBind to *process files that match this pattern and generate pages*.

If this were to be implemented, it should:
- definitely be outside the `"pages"` array as it doesn't specify a page to be rendered;
- maybe have `"exclude"` in its name rather than `"ignore"` to avoid ambiguity.

**Comment by ang-zeyu** [comment]
Moved to #715
