### ISSUE TITLE
variable with complicated value not working

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#232]
Steps to reproduce:
1. set up the repo https://github.com/nus-cs2103/website-base locally
2. markbind serve
3. go to http://127.0.0.1:8080/website/book/architecture/introduction/what/

Expected:
![image](https://user-images.githubusercontent.com/1673303/40372351-0db0024a-5e17-11e8-8e20-420f001d0ebb.png)

Actual:
![image](https://user-images.githubusercontent.com/1673303/40372374-1d6d8982-5e17-11e8-8ceb-bcb979b4312c.png)

Current page source:
```
<frontmatter>
title: "Software Architecture: Introduction: What"
</frontmatter>

{{index_body}}
```

The page works if I replace the variable `{{index_body}}` with its value.
```
<frontmatter>
title: "Software Architecture: Introduction: What"
</frontmatter>

<link rel="stylesheet" href="{{baseUrl}}/css/textbook.css">

<div class="website-content">

<tip-box>
  <include src="outcomes.md" />
</tip-box></p>

<include src="full.md" boilerplate />

</div>
```
Am I using variables beyond its intended use? I assumed they can contain any text fragment.

**Comment by rachx** [comment]
> Variables are replaced at the render stage.

I think I replace it in the includeFile stage.

I played around with it and I think the problem is because when we use nunjucks to render the user define variables, it autoescapes the angle brackets to `&lt;` etc. Markbind won't parse it subsequently.

I think you can use `{{ index_body | safe }}` to manually mark the content of index_body as safe and it should work correctly (even for `<include src=...>`.
We can also turn off autoescaping for nunjucks.

**Comment by rachx** [comment]
Yep it does

**Comment by damithc** [comment]
> Yep it does

Oh? nice! 💯

**Comment by damithc** [comment]
Seems to be solved.
