### ISSUE TITLE
Show file location for 'variable with no name ...' warning

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2338]
v5.0.1

Current:
![image](https://github.com/MarkBind/markbind/assets/1673303/6364fa05-235b-4e37-97b5-645c7bf4a6a2)

Suggested: also indicate which file contains the offending variable

**Comment by tlylt** [comment]
@damithc yes good point. I have tracked down the issue, which seems to stem from the use of `<span id` instead of `<variable name=` within _markbind/variables.md, see global variable usage in https://markbind.org/userGuide/reusingContents.html#global-variables

Adding warnings to the current site (useful when there are multiple site) + the value might help debugging:
![image](https://github.com/MarkBind/markbind/assets/41845017/f38b1dca-57f2-4efb-a8b9-aedc1c13dffe)

It's somewhat related to this breaking change: https://github.com/MarkBind/markbind/releases/tag/v5.0.0#:~:text=7.%20Clean%20up%20docs%20%26%20tests%20for%20variables%20by%20%40tlylt%20in%20%232301

To rectify, you need to update span id to variable name for book/_markbind/variables.md and _markbind/variables.md (or anything else that I missed)

**Comment by damithc** [comment]
> To rectify, you need to update span id to variable name for book/_markbind/variables.md and _markbind/variables.md (or anything else that I missed)

Yup, that worked. Thanks for the troubleshooting help, @tlylt
