### ISSUE TITLE
Re-introduce lazy loading for pictures

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#2367]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Any related issues?

#2365, #1626, #2364

### What is the area that this feature belongs to?

Author Usability, Reader Usability

### Is your feature request related to a problem? Please describe.

See related issues for context.

TLDR: scrolling to anchor does not work as expected when there are lazily loaded images, hence we will remove existing lazy loading support.

### Describe the solution you'd like

Add an option to specify eager/lazy loading of images, 
https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading

Need to ensure scrolling still works.

**Comment by yucheng11122017** [comment]
Hi I've done some research on this 
1. One way to fix this issue is to call another scrollIntoView when the images have been loaded. But this would need to be done for every single lazy loaded image which is not ideal - https://stackoverflow.com/questions/68467475/lazy-loading-conflicting-with-scrollto-anchor-to-id-scroll-stops-halfway-throu 
2. Another way is to call two animations (basically the same as the first but only 2 animations). When the first is ending, hopefully the images would have loaded and hence the second animation would result in correct positioning https://stackoverflow.com/questions/63197942/scrollintoview-not-working-properly-with-lazy-image-load
3. Both method 1 and method 2 are extremely hacky. I think generally the better way is the user to input the height and width so that scrollIntoView can compute properly and hence doesn't get pushed down.  https://www.reddit.com/r/webdev/comments/13kcpko/how_to_fix_jscss_scrolling_down_in_the_page_with/

**Comment by LamJiuFong** [comment]
Thank you @kaixin-hc for your suggestions! I will try to tackle this issue
