### ISSUE TITLE
MarkBind Template for CS2103/Software Documentation

### ISSUE THREAD

**Issue by itsyme** [MarkBind/markbind#2384]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

Author Usability

### Is your feature request related to a problem? Please describe.

There is no large incentive for CS2103 users to use MarkBind over the default option

### Describe the solution you'd like

A template for CS2103 students to use for their team project would incentivise users to use MarkBind over the default option as there is something for users to start with that is catered to this specific use case.

Use the [existing template](https://github.com/damithc/ab3-markbind) already created.
User should be able to call `markbind init --template cs2103` to create this template

### Describe alternatives you've considered

Possible to generalise to a more generic documentation template. We could base it off CS2103 and name it something like Software Documentation as it may seem odd to non-NUS users which could possibly put them off using MarkBind.

**Comment by damithc** [comment]
@itsyme CS2103 students are given a MarkBind version of the AB3 website (work done by @tlylt ). It is in a separate branch in AB3. Just need to merge it to master branch. https://nus-cs2103-ay2324s1.github.io/website/admin/appendixE-gitHub.html#markbind

**Comment by itsyme** [comment]
> @itsyme CS2103 students are given a MarkBind version of the AB3 website (work done by @tlylt ). It is in a separate branch in AB3. Just need to merge it to master branch. https://nus-cs2103-ay2324s1.github.io/website/admin/appendixE-gitHub.html#markbind

Ahh I see thanks for the clarification prof!

**Comment by yucheng11122017** [comment]
Please also finish off #2072 if you are finishing this issue :)

**Comment by lhw-1** [comment]
Here is the [link to the deployment](https://github.com/damithc/ab3-markbind/tree/gh-pages) that needs to be referenced.

**Comment by KevinEyo1** [comment]
Can I take this issue?

**Comment by lhw-1** [comment]
In terms of the template itself, I think we can refer to it as the AB3 template instead of the CS2103 template (and the command will be `markbind init --template ab3` accordingly) - [AB3](https://se-education.org/addressbook-level3/) is part of the [SE-EDU](https://se-education.org/) initiative which [MarkBind falls under](https://se-education.org/docs/tools.html), whereas CS2103 is NUS-specific and may seem odd to non-NUS users as @itsyme pointed out.

In terms of the general software documentation, I think we can consider this as a separate issue, since it would require more research into what would constitute a minimal yet useful set of features for general software documentation. It would also be good to refer to what other tools (E.g. Jekyll, Docusaurus, etc.) have in place for this (if any).

So perhaps for this issue #2384, we can reduce the scope to just focus on the ab3 template 👍

**Comment by KevinEyo1** [comment]
Do I need to setup repos on MarkBind for this template to link to Netlify, based on what is done for the [default](https://github.com/MarkBind/init-typical-netlify) and [minimal](https://github.com/MarkBind/init-minimal-netlify) template?

**Comment by tlylt** [comment]
> Do I need to setup repos on MarkBind for this template to link to Netlify, based on what is done for the [default](https://github.com/MarkBind/init-typical-netlify) and [minimal](https://github.com/MarkBind/init-minimal-netlify) template?

Can probably create one in your personal account first. Once everything is settled it can be easily transferred over.

**Comment by kaixin-hc** [comment]
Summarising progress - we now have a template for software project documentation (https://github.com/MarkBind/markbind/pull/2400). We can consider closing this issue, or more clearly outlining how we want to support the cs2103 usecase
