### ISSUE TITLE
UG: images appear in two places

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2401]
![image](https://github.com/MarkBind/markbind/assets/1673303/53fc2e9c-d1d1-49b5-9828-0e8d6ae95925)

It is OK for something to appear in multiple places, if intentional. But if this is not intentional, need to consolidate into one place.

**Comment by yucheng11122017** [comment]
Thanks for pointing this out @damithc! 
It seems like Markbind has two components for images... 
One is using markdown syntax ("images" in the UG) and another is ["picture" ](https://markbind.org/userGuide/components/imagesAndDiagrams.html#pictures). 
I think "image" got included within "formating content" in the UG because it is from markdown. 
Seems like the major difference between the two in terms of usability is that "picture" can add an caption below it, while "images" doesn't support it natively. 

Should we look to combine these two components? Or find a way to reformat it?

**Comment by EltonGohJH** [comment]
@yucheng11122017 
I agree. Both of them are different and have different syntax. 
Maybe we can disambiguate and help the users out?

I think we can solve it by linking them to one another.
For example, in the markdown syntax image, we can say that if you want to add a caption to your image, you can refer to the image component.

Then for the image component, we can say that if you want to create a clickable image please refer to the markdown syntax image?

**Comment by damithc** [comment]
Yes, cross-linking should be good enough.
Another difference between `pic` and `img` is `pic` auto-resize the image to fit the enclosing container (e.g., a panel), if the image is bigger than the container.
