### ISSUE TITLE
.gitignore not generated when init

### ISSUE THREAD

**Issue by tlylt** [MarkBind/markbind#2416]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

macOS 14

### MarkBind version

5.2.0

### Describe the bug and the steps to reproduce it

When running `npx markbind-cli init`, the `.gitignore` file is not generated. I tested on Windows 10 and it seems to work fine. May need someone to confirm using a mac machine.

### Expected behavior

Should generate .gitignore as per https://markbind-master.netlify.app/userguide/gitignorefile

**Comment by kaixin-hc** [comment]
Tested with MarkBind 5.2 on macOS 13.6

- When using the globally released version `npm un -g markbind-cli`, followed by `npm i -g markbind-cli`, followed by `npx markbind-cli init`, the .gitignore file is not produced
- When linked to this git version (`cd packages/cli` followed by `npm link`), the .gitignore file is produced.

Perhaps the difference lies there 🤔

**Comment by tlylt** [comment]
> Perhaps the difference lies there 🤔

Seems like it could be. If you do the [dev dependency](https://markbind.org/userGuide/gettingStarted.html#method-2-install-markbind-locally-as-a-dev-dependency-in-package-json) method to install markbind, you can check the npm_modules folder for the files we ship. Not sure if I have the correct local, but it looks like at least for the markbind core i have, it doesn't contain the `.gitignore` file.
![image](https://github.com/MarkBind/markbind/assets/41845017/6aa44504-51e0-475c-9b31-3490cfce8605)

Maybe something to do with how we release markbind

**Comment by LamJiuFong** [comment]
Maybe because the `.gitignore` is not released as part of the package due to some restrictions of npm (they don't allow .gitignore to be part of a package). Hence the file will not be copied over when running `markbind init`
![Screenshot 2024-03-16 at 8 28 08 AM](https://github.com/MarkBind/markbind/assets/122192553/6a64594d-1e3c-456a-a9f6-724802275147)

A common workaround is to rename the `.gitignore` to `gitignore` before publishing. Then as part of an init script, rename the `gitignore` file to `.gitignore`.
https://stackoverflow.com/questions/24976950/how-do-i-include-a-gitignore-file-as-part-of-my-npm-module

I have tried to publish my own package and the `.gitignore` file I created is indeed not published on npm. And it is also possible to copy a `gitignore` file to a `.gitignore` when doing init. I will work in this direction and try to resolve this issue.
