### ISSUE TITLE
Use justified text formatting for tooltips

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2420]
For cases such as the below, centering the tooltip text doesn't seem like a good fit.

![image](https://github.com/MarkBind/markbind/assets/1673303/dd0e04bc-d6cf-4dd0-a86c-6e5e4f71f1b1)

Perhaps _align-left_ or _justify_ is better?

**Comment by kaixin-hc** [comment]
Hi! I'd like to clarify what you feel the issue is with centering here?

**Comment by damithc** [comment]
> Hi! I'd like to clarify what you feel the issue is with centering here?

Centering is not normally used for a paragraph of text. So, longer the text, the odd it feels to have centered text.

I suspect the slight discomfort is caused by starting point of each line not being at a predictable place, requiring a little bit of extra effort when reading each line (plus straight lines are easier on the eye compared to jagged edges).

**Comment by EltonGohJH** [comment]
I agree that for long text centering makes it kinda hard to read. 
Maybe someone can try whether justify or left align is better as compared to text centered.

**Comment by kaixin-hc** [comment]
Okay, a quick visual comparison as follows...
|   | Text aligned to left | Centered |
|---|----------------------|----------|
| Short Text (no visual change) |       <img width="700" alt="Screenshot 2024-02-15 at 3 43 41 AM" src="https://github.com/MarkBind/markbind/assets/59471320/700c5389-0762-482a-9152-0bc192e331d9"> | <img width="697" alt="Screenshot 2024-02-15 at 3 53 30 AM" src="https://github.com/MarkBind/markbind/assets/59471320/6a2c5390-d1c7-4881-ae03-84a7631bbef8"> |
| Medium Length  | <img width="859" alt="Screenshot 2024-02-15 at 3 43 26 AM" src="https://github.com/MarkBind/markbind/assets/59471320/acb978fa-37ac-479a-b3e8-a3032d6febe9"> | <img width="764" alt="Screenshot 2024-02-15 at 3 59 15 AM" src="https://github.com/MarkBind/markbind/assets/59471320/ccddf631-0629-4979-9cee-041c34b65ec9"> |
| Long Text  | <img width="873" alt="Left formatted tool tip, long text" src="https://github.com/MarkBind/markbind/assets/59471320/37c696cc-0f75-4a7c-b520-c8be45954c28">  |  <img width="700" alt="centered tool tip, long text" src="https://github.com/MarkBind/markbind/assets/59471320/870f91fe-a1aa-4e25-9159-9f1815c572d4"> |

Bonus - Justified long text:
<img width="778" alt="Screenshot 2024-02-15 at 4 03 21 AM" src="https://github.com/MarkBind/markbind/assets/59471320/719aeed5-4418-47c8-a561-dfa1ae2047b0">

I personally like center alignment for tooltips that are relatively short but more than a single line, but left alignment is also OK. Justified is harder to read for me though because of the inconsistent spacing.

Though I feel as a user if your tooltips are so long, this default is a little ugly either way, and I would probably switch to panels or similar.

**Comment by damithc** [comment]
> Though I feel as a user if your tooltips are so long, this default is a little ugly either way, and I would probably switch to panels or similar.

Good point @kaixin-hc In fact, we can say the tooltip is for short text and popovers is for longer text. The latter is left-aligned, wider, and easier to read:
![image](https://github.com/MarkBind/markbind/assets/1673303/118b7d4d-6ce8-4a73-90de-73f3acc7cd27)

I'll close this issue for now.
