### ISSUE TITLE
Explore using Bun for testing and setup

### ISSUE THREAD

**Issue by EltonGohJH** [MarkBind/markbind#2448]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

DevOps

### Is your feature request related to a problem? Please describe.

Testing and running setup locally can be slow.

### Describe the solution you'd like

I am thinking whether we can introduce bun just for testing and setting up which will improve dev experience.
I think that Lerna can work with running bun but I am not 100% sure so we need to investigate.

### Additional context
If you do migrate to bun, please do a comparison to see if it is worthwhile to add this dependency in!

_No response_

**Comment by EltonGohJH** [comment]
Out of curiosity, I tested bun on markbind-cli.  When I did that serve -d, does not work.
From how I feel, the perfomance gain is negligible when I tested markbind serve. 

I think that for this maybe we can just focus on markbind run setup and test. (So, the dependency is on dev's end rather than users)

**Comment by KevinEyo1** [comment]
**Version 1.0.x using Windows through WSL**
Bun is supported for Linux and macOS. Currently Windows is not fully supported and only has an experimental build. Current best option before v1.1 is to use Bun within WSL, instructions can be found [here](https://bun.sh/docs/installation).

Note: for bun to work for these scripts itself, and any scripts that call them, need edit them
```
"csslint": "stylelint **/*.css **/*.vue",
"csslintfix": "stylelint **/*.css **/*.vue --fix",
```
```
"csslint": "stylelint \"**/*.css\" \"**/*.vue\"",
"csslintfix": "stylelint \"**/*.css\" \"**/*.vue\" --fix",
```

Test environment:
Git clone markbind and setting up 2 environments, one running npm commands and one running bun commands, timings vary each call and the following are just one sample size of comparison. Generally, there is little to no difference with occasional spikes of differences where bun is faster than npm, but also where npm is faster than bun.
Efficiency can be weaker due to certain commands being unreplacable by bun, such as `npm ci` and `lerna run prepare`.

![image](https://github.com/MarkBind/markbind/assets/105847348/825a8a01-d773-4025-8ee5-00c4f4dc9aad)

**Comment by KevinEyo1** [comment]
**Version 1.1.2 using Windows**
Windows is now supported as well, so I re-ran tests and the timings are still very variable without clear improvement for bun. This particular sample is in fact leaning to npm for being faster.
![image](https://github.com/MarkBind/markbind/assets/105847348/9a557ee0-2c03-47e9-ab93-4c2b1929c42a)

**Comment by yucheng11122017** [comment]
Thanks for the through investigation @KevinEyo1! In the case, we can close this issue for now. Would be good to explore other tools that can speed up our tests and running but I guess Bun is not the tool for that :(
