### ISSUE TITLE
Alternatives for MarkBind components

### ISSUE THREAD

**Issue by acjh** [MarkBind/markbind#245]
[yuche/vue-strap](https://github.com/yuche/vue-strap), the upstream of [MarkBind/vue-strap](https://github.com/MarkBind/vue-strap), officially [deprecated](https://github.com/yuche/vue-strap#deprecated) their repo 8 hours ago.

As far as I can tell from the [forks](https://github.com/yuche/vue-strap/network/members) and the [contributors graph](https://github.com/yuche/vue-strap/graphs/contributors):
- [wffranco/vue-strap](https://github.com/wffranco/vue-strap) is the most popular (341 stars, 134 forks, active* Feb–Oct 2017).
- we're the second-most forked and the most active (9 forks, active* May 2018 – today).

yuche [recommended](https://github.com/yuche/vue-strap#deprecated):
- [bootstrap-vue/bootstrap-vue](https://github.com/bootstrap-vue/bootstrap-vue) (5127 stars, 735 forks, active* Apr 2018 – 2 days ago).
- [wxsms/uiv](https://github.com/wxsms/uiv) (506 stars, 97 forks, active* Mar 2018 – today).

I believe it's in MarkBind's best interest in the long term to port over to [bootstrap-vue's components](https://bootstrap-vue.js.org/docs/components).

<sub>*activity based on the [past 35 commits on master](https://github.com/MarkBind/vue-strap/commits/master).</sub>

**Comment by damithc** [comment]
It's a good thing this happened early in the summer so that we have time to do a major change like that. :-p

**Comment by acjh** [comment]
This means going from Vue 1 → Vue 2 and Bootstrap 3 → Bootstrap 4.
Major change indeed, but I guess we should keep up with the times 🙈

**Comment by damithc** [comment]
> Major change indeed, but I guess we should keep up with the times

Yeah.  No choice. @Gisonrg any advice? Any idea how much work is needed?

**Comment by damithc** [comment]
Looks like we have to move from glyphicons → fontawesome too. Bootstrap has dropped support for glyphicons

**Comment by Gisonrg** [comment]
In 2017 I checked Vue 2.0 and found there are some features regarding dynamic template rendering in 1.0 are removed in 2.0 for some security reason (unfortunately I can't rmb the exact piece now), not sure if it is achieve-able now.
As for the estimate of time, I believe it would take at least 1-1.5 month for a total re-write and migration (tasks I foresee: research what is supported (and not), migrate components, redevelopment, testing, migrate existing sites and release).
Also, think about creating our own repo/library for components using bootstrap-vue instead of forking and build on top of it (favor composition over "inheritance")

**Comment by damithc** [comment]
@yamgent this one can be closed, right?

**Comment by yamgent** [comment]
Yes, the components are currently self-maintained now, so the intention is actually met.

We could explore how we can further exploit Bootstrap-Vue for new/existing MarkBind components, but they should be a separate issue from this one.
