### ISSUE TITLE
Add a reminder when contributor is new to ping all contributor bot

### ISSUE THREAD

**Issue by yucheng11122017** [MarkBind/markbind#2457]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### What is the area that this feature belongs to?

DevOps

### Is your feature request related to a problem? Please describe.

I sometimes forget to add contributors when they have contributed for the first time. So I was thinking about automating this process. 

### Describe the solution you'd like

One possible solution I found was [all-contributors-auto-action](https://github.com/JoshuaKGoldberg/all-contributors-auto-action) which aims to do this. This would need some investigation and testing about how well it works 
Would be open to other solutions as well.

**Comment by kaixin-hc** [comment]
Love the initiative! 

But reading about [all-contributors-auto-action](https://github.com/JoshuaKGoldberg/all-contributors-auto-action), it seems like its actually used to populate a backlog of contributors (all contributors newest PR). So in our usecase, it seems to imply it would add a lot of backlogged contributors? (Maybe I'm misunderstanding)

**Comment by kaixin-hc** [comment]
You've changed my mind - I think then the main issue that @yucheng11122017 has brought up here is that it is easy to forget that we are using the bot and that we have this on the main page, probably because we don't use it super regularly. Maybe we could make a note that contributors can ask to be added themselves (if they want). Maybe there's somewhere else we can get the nudge to express that appreciation - like an automated reminder or suggestion. 

Not sure.

**Comment by tlylt** [comment]
> Maybe there's somewhere else we can get the nudge to express that appreciation - like an automated reminder or suggestion.

Maybe an automated reminder comment on first time contributor PRs...should be quite doable.

**Comment by yucheng11122017** [comment]
> > Maybe there's somewhere else we can get the nudge to express that appreciation - like an automated reminder or suggestion.
> 
> Maybe an automated reminder comment on first time contributor PRs...should be quite doable.

Ok I think that makes more sense! 
It seems there is this github action which checks if someone is a first time contributor 

https://github.com/marketplace/actions/first-contribution-check-action

Combined with a response, I think this would be sufficient

**Comment by KevinEyo1** [comment]
Should this action be ran on PR `merged` event? Or do we count the possibility of contribution without having merged the code (running action on PR `opened` or `reopened` event)?

**Comment by kaixin-hc** [comment]
On merged seems like a good implementation to me! The allcontributors PR is usually not merged until the first PR is merged!

**Comment by KevinEyo1** [comment]
Currently, the on merged implementation checks for all PRs of the repo to look for any PR of the author to determine whether the author is a new contributor, which can be slow in performance.
Listing contributors fails as running it on merged would be after the merge, so the author would be in the list of contributors already.

Without the limitation of it being on merged, such as any event before merged like on PR opened, it will work. I think this can be an acceptable implementation since it is just a reminder ping. This can also be aided by an on merge event that checks for this prior ping, to re-ping it on merge, allowing it to work fundamentally the same but with better performance.

I will try to see if there are any other possible implementations.

**Comment by KevinEyo1** [comment]
Actually the time taken based on testing averages 5 seconds for the `on merged` implementation, so it should be fine even in the long term.

**Comment by KevinEyo1** [comment]
As per discussion with Prof @damithc, we can ping either specific people or active devs, whoever works best (maybe the person who merged it whom should be an active dev, so as to avoid pinging too many people), to add the contributor to the list of contributors, as well as a welcome message for the contributor. We assume that all users want to be added in.

**Comment by kaixin-hc** [comment]
I like the idea of pinging the person who merged it in!

Thanks for your work on this Kevin :) It's really appreciated!
