### ISSUE TITLE
Search for heading: result covered by navbar

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#252]
v1.8.0

Steps:
* Go to https://markbind.github.io/markbind
* Search for `search`
* Hit enter

Result: the correct place of the document loads but the heading is covered behind the navbar.
![image](https://user-images.githubusercontent.com/1673303/40913993-14284ec2-6829-11e8-8bd6-c2c48503da6f.png)

**Comment by yamgent** [comment]
This problem was previously fixed in PR MarkBind/vue-strap#14 (issue number #152). The old fix is shown below ([source](https://github.com/MarkBind/vue-strap/blob/41078432f10bda9c3f7504c3adee77cca8a290b5/src/Navbar.vue#L85-L89)):

`src/Navbar.vue`:

```javascript
    let height = this.$el.offsetHeight
    if (this.placement === 'top') {
      document.body.style.paddingTop = height + 'px'
      $(window).on('hashchange', () => scrollBy(0, -height))
    }
```

This fix does the adjustment after the browser scrolls to the correct position.

However, due to the race condition in issue number #310, the covering problem reappeared. `hashchange` is sent after the browser scrolls to the correct position, but it does not mean that Vue has finish loading the page (which is the race condition).

The block of code listed above does not wait till Vue finishes loading, therefore it no longer works.

_Suggestion:_ Somehow execute this block of code above after Vue finish loading, rather than after the browser scrolls?

_Alternative fix:_ Detect if the page has a navbar, and if so, get its height, and scroll accordingly. This can be done in `setup.js` rather than `src/Navbar.vue`.
