### ISSUE TITLE
Close button of boxes located too far inside

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#2558]
Example:
https://nus-cs2103-ay2324s2.github.io/website/schedule/week1/index.html
![image](https://github.com/MarkBind/markbind/assets/1673303/5399910b-545c-48b2-a9eb-8dce74c49d4e)

Previously, it was like this:
![image](https://github.com/MarkBind/markbind/assets/1673303/e9637fbb-0fe5-4e24-ac1f-61d60376298d)

It's possible the location is affected by the presence of a heading. Example:
![image](https://github.com/MarkBind/markbind/assets/1673303/f6250f03-7153-41c1-80e3-4344acfa0bc9)

Possibly related to https://github.com/MarkBind/markbind/pull/2487 ?

**Comment by damithc** [comment]
Raising priority, as this makes dismissible boxes look broken.

**Comment by gerteck** [comment]
After some tracing, the regression was indeed unintentionally caused by #2487 , although the cause is quite simple but elusive. 

The change to the classname of the body wrapper in the PR from `alert-dismissible` to `alert-dismissible-box` removed the effect of the global bootstrap css, causing this regression.

* Should be a simple fix to revert this, while keeping original addressed issue fixed.
* Perhaps some documentation warning devs about this would be good to prevent this further regressions?

---
### Additional details for anyone who wants to trace the code, for your convenience. 

>MarkBind core-web library
> This package houses the various frontend assets used in the core package.
> Some external assets included are Vue.js, Bootstrap bundles, and FontAwesome bundles.
> Internal bundles are also present, generated from setup scripts, custom stylesheets and the UI components library.

For anyone who wants to trace the code:

https://github.com/MarkBind/markbind/blob/db8bc534a5e457c8fba707adda418bb91b0befe5/packages/core/src/Site/index.ts#L1310-L1312

From bootstrap.min.css (unminified)
```css
.alert-dismissible {
    padding-right: 3rem;
}
.alert-dismissible .btn-close {
    position: absolute;
    top: 0;
    right: 0;
    z-index: 2;
    padding: 1.25rem 1rem;
}
```
[Link](https://getbootstrap.com/docs/5.1/components/alerts/) to Bootstrap v5.1 > Alerts for documentation: 

cause of regression:
```
   <!-- Body wrapper -->
      <div
        :class="[
          'box-body-wrapper',
          {
-           'alert-dismissible': dismissible && !headerBool(),
+           'alert-dismissible-box': dismissible && !headerBool(),
            'box-body-wrapper-with-heading': headerBool(),
          },
        ]"
      >
```

* [See exact commit](https://github.com/MarkBind/markbind/pull/2487/files?diff=unified&w=0#diff-d90afd9ee277216dd38ff2d79eb4d7a31be8725e6808c37cd7b6c8ede03c81eaR63-R71)

Change of class name caused `.btn-close` to effectively not have absolute position, causing it to collapse.

![image](https://github.com/user-attachments/assets/0a3d39b8-3a3a-408a-a4b2-33e103fae03a)

**Comment by damithc** [comment]
Thanks for the investigation, @gerteck
