### ISSUE TITLE
baseUrl's value sometimes wrong when referencing inner website's content

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#262]
v1.8.0 (not the latest version)

Consider this page: 
https://github.com/nus-cs2103/website-base/edit/master/se-book-adapted/chapters/test.md

Rendered version:
https://nus-cs2103.github.io/website-base/se-book-adapted/chapters/test.html

It's the same content included twice, once directly (i.e., text.md#body), once indirectly (i.e., index.md). Surprisingly, the direct version has broken image links while the indirect version that goes through further variables, includes, and boilerplates seems to have the correct image links.

Any idea what's going on?

BTW, it works locally. The problem happens when I deploy.

**Comment by yamgent** [comment]
Preliminary findings: `{{hostBaseUrl}}` were different values at different stages of the rendering, and both parts had their variables replaced at different times.

Still investigating this issue.

**Comment by yamgent** [comment]
@damithc FYI, the first issue (see below) can immediately be fixed by making changes on your side in `website-base`: https://github.com/yamgent/website-base/commit/4f74fdb4c62e63e785e25557966e73b06ad6322a

I have found the fix for the second issue, and modified PR #263 accordingly. Will have to wait for that to be merged before the images work.

---

## 1. CSS url issue
**Affected webpage:** `https://nus-cs2103.github.io/website-base/se-book-adapted/chapters/architecture.html`

**Description:** The URL to the CSS (`textbook.css`) did not work (resulting in a stretched webpage effect), as it uses the `{{baseUrl}}` variable.

**Why the Bug Exist:** When using nunjucks' import feature, nunjucks will ignore any variables declared inside the imported file, unless it is specified to import the file "with context".

**Solution:** If we want to use `{{baseUrl}}` for the URL to the CSS file, we must use the keywords "with context" when importing "config.md" and "chapter.md". The commit that fixes this can be found [here](https://github.com/yamgent/website-base/commit/4f74fdb4c62e63e785e25557966e73b06ad6322a). 

## 2. Broken image issue
**Affected webpages:** `https://nus-cs2103.github.io/website-base/se-book-adapted/chapters/architecture.html`, `https://nus-cs2103.github.io/website-base/se-book-adapted/chapters/test.html`

**Description:** The images are broken because the URL to the images are wrong (the `baseUrl` appears to be missing).

**Why the Bug Exist:** I have traced down the issue to `{{hostBaseUrl}}` being prematurely replaced when the value is not injected yet.

**Solution:** I have fixed the behavior, and the fix is in PR #263. The images will no longer be broken after the PR is merged.

## How the Webpages Looks Like After Applying the Fixes

* [architecture.html](https://yamgent.github.io/website-base/se-book-adapted/chapters/architecture.html)
* [test.html](https://yamgent.github.io/website-base/se-book-adapted/chapters/test.html)

**Comment by damithc** [comment]
Yup, the _CSS url issue_ worked.  Thanks for finding the workaround 👍
