### ISSUE TITLE
Advanced tips: Code for modal's customized slots does not work

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#313]
**Tell us about your environment**

* **MarkBind Version:** 1.8.4

**What did you do? Please include the actual source code causing the issue.**

I copied this code from the "Advanced Tips and Tricks" section for "Components Reference", and pasted it in a new website (by doing `markbind init`, and modifying `index.md`).

The code uses customized slots.

```html
<trigger for="modal:tip-example" trigger="click">Click here to show Modal.</trigger>
<modal id="modal:tip-example">
  <div slot="modal-header" class="modal-title text-center">
    <span style="font-size:20pt"><span style="color:red;">BIG</span> header</span>
  </div>
    Modal allows you to style both header and footer individually, with style classes and inline styles.
  <div slot="modal-footer" class="text-center">
    <span style="font-size:10pt">Tiny <span style="color:green;">footer</span></span>
  </div>
</modal>
```

**What did you expect to happen?**
The customized slot content should show properly in the modal.

<img src="https://user-images.githubusercontent.com/3168908/42430300-ef70d4e2-8370-11e8-8862-1f47461ba000.png" width="400" />

**What actually happened? Please include the actual, raw output.**
<img src="https://user-images.githubusercontent.com/3168908/42430266-b66cf248-8370-11e8-9f58-a0ce467d6b24.png" width="400" />

**Comment by Chng-Zhi-Xuan** [comment]
**Discussion**
- Bug was narrowed down to `<trigger>` being an inline `<span>` component. This results in automatic wrapping with a `<p>` tag by MarkBind. The wrapping breaks or swallows other components directly in the next line, which may cause the component to render incorrectly.<br><br>
- The solution is to add a line break after `<trigger>` or wrap it in a non-inline element (`div`, `p`).<br><br>
- As `<trigger>` being an inline element is intentional, we should update our user guide. Specifically, 
 to describe this behaviour and work-around in the `Trigger` section.

**Alternative solution**
- Create a new attribute (`stand-alone`) within the `<trigger>` component. It can be used to toggle which template should be used for `<trigger>`, either as a stand-alone (wrapped in a div) or inline (default behaviour)

**Comment by acjh** [comment]
> Create a new attribute (`stand-alone`)

`inline=false` is more intuitive and meaningful.
