### ISSUE TITLE
Feature request: Specify expansion level in schedule

### ISSUE THREAD

**Issue by okkhoy** [MarkBind/markbind#379]
**Tell us about your environment**
Windows 10 

* **MarkBind Version:**
v1.9.2

**What did you do? Please include the actual source code causing the issue.**
Try to view only headings in the schedule page e.g., in https://nus-cs2103.github.io/website-base/index.html

```html

```

**What did you expect to happen?**
To see something like this: 
![image](https://user-images.githubusercontent.com/1023494/43256131-64acc938-90fe-11e8-989f-cda3369a410b.png)

**What actually happened? Please include the actual, raw output.**
Currently the view is either all collapsed:
![image](https://user-images.githubusercontent.com/1023494/43256154-7a9fd2a8-90fe-11e8-88d3-1eec9089cec8.png)

OR

Fully expanded:
![image](https://user-images.githubusercontent.com/1023494/43256180-8c81808e-90fe-11e8-8741-dbf16937cd5d.png)

If the default behavior can be set to "expand on demand" it would be nice:
Something similar to one of the previous versions of the site: 
![image](https://user-images.githubusercontent.com/1023494/43256247-beefd642-90fe-11e8-95d9-a5094a4fd72f.png)

May be similar to #348

**Comment by damithc** [comment]
@okkhoy those panels are set to expand by default. They can be set to be collapse by default too. This is not related to markbind. Can be controlled in website code. 

Last semester Henry requested them to be expanded by default because a student expanding the panel is likely to want to expand each of the inside panels too, and auto-expanding saves them one step.

**Comment by okkhoy** [comment]
Lol! I guess I will live with that. I was trying to find a way to get all LOs in one list view somehow!
We can close the issue I guess.
