### ISSUE TITLE
Markdown rendering breaks if document does not start with 2 empty lines

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#429]
**Tell us about your environment**

* **MarkBind Version:** 1.12.0

**What did you do? Please include the actual source code causing the issue.**

~~Omitting the `<frontmatter>` causes the Markdown syntax to be not properly rendered.~~ Not leaving at least 2 empty lines causes Markdown syntax to break.

`index.md`:

```markdown
# Some heading
The **quick** brown fox jumps _over_ the lazy dog.
```

**What did you expect to happen?**
The Markdown syntax should be rendered.

**What actually happened? Please include the actual, raw output.**
<img src="https://user-images.githubusercontent.com/3168908/45096444-2969c680-b153-11e8-98fd-bc926a22386c.png" />

**Comment by jamos-tay** [comment]
I suspect it's something to do with the parser, leaving out the newline between the frontmatter and a header also seems to fail to render:

```
<frontmatter>
  title: "Hello World"
  footer: footer.md
  siteNav: site-nav.md
</frontmatter>
# Header
```

![image](https://user-images.githubusercontent.com/19278089/45102973-6b9a0480-b161-11e8-9c3a-9fe8e0404813.png)

I'm guessing it's because 2 newlines are needed before the first instance of markdown text. A simple workaround would be to put this in `addContentWrapper`. This seems to work:

![image](https://user-images.githubusercontent.com/19278089/45103278-21655300-b162-11e8-8c10-b16ee7536cd8.png)

Thoughts?

**Comment by yamgent** [comment]
> I'm guessing it's because 2 newlines are needed before the first instance of markdown text. A simple workaround would be to put this in addContentWrapper.

This is most likely the correct reason. I `git bisect`ed it and landed on the exact same method, and I recall the Markdown standard specifying the need to have 2 newlines when wrapped with html tags. So let's go with that. :+1:
