### ISSUE TITLE
Stray dash in output caused by popover

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#456]
v1.13.0
Location: https://nus-cs2103-ay1819s1.github.io/cs2103-website/se-book-adapted/chapters/testCaseDesign.html#equivalence-partitions

There seems to be a stray dash in the output.
![image](https://user-images.githubusercontent.com/1673303/47250885-a380b100-d45c-11e8-9b79-3a7ab329cb32.png)

**Comment by damithc** [comment]
Another case. I'm guessing this is something to do with popovers.
![image](https://user-images.githubusercontent.com/1673303/47264979-4c113c80-d553-11e8-9e21-ebe1201759f1.png)

**Comment by damithc** [comment]
Further updates: in fact the stray dash has a popover
![image](https://user-images.githubusercontent.com/1673303/47542155-b688fa80-d90e-11e8-8f93-037980f6d92d.png)

**Comment by jamos-tay** [comment]
Is this on a public repo? The problem doesn't seem to happen for the book repo... Can I see the markdown used to generate this page?

**Comment by damithc** [comment]
> Is this on a different repo? The problem doesn't seem to happen for the book repo... Can I see the markdown used to generate this page?

https://github.com/nus-cs2103-AY1819S1/cs2103-website

**Comment by damithc** [comment]
Live version https://nus-cs2103-ay1819s1.github.io/cs2103-website/se-book-adapted/chapters/gatheringRequirements.html#interviews

**Comment by jamos-tay** [comment]
I can't seem to reproduce the error on my side, when I run serve on the `master` and `cs2103` branch, they both render correctly:

![capture](https://user-images.githubusercontent.com/19278089/47734511-678fec00-dca5-11e8-8b6c-73d4b5f8067d.PNG)

Is it due to the differing build environment. The 'dash' seems to be an empty `span` that's being rendered. Here's the relevant code portion:

![capture4](https://user-images.githubusercontent.com/19278089/47734629-a02fc580-dca5-11e8-8263-e2c4a7f78672.PNG)

For some reason the popover code is causing it to render an extra empty span:

![capture3](https://user-images.githubusercontent.com/19278089/47734671-bb023a00-dca5-11e8-988b-0da4cf5d0f73.PNG)

Here's how it renders on my side:

![capture2](https://user-images.githubusercontent.com/19278089/47734681-c3f30b80-dca5-11e8-9d58-d0b5466c86f6.PNG)

Can confirm that it's being caused by popover, though, since it's appearing after all other popovers I've found as well. Any ideas?

**Comment by yamgent** [comment]
> Live version https://nus-cs2103-ay1819s1.github.io/cs2103-website/se-book-adapted/chapters/gatheringRequirements.html#interviews

Can't reproduce the bug for this url either on my side. I also suspect that it could be a different build environment, but I haven't had the time to investigate that claim.

----

The popover has two separate HTML parts. The one that I have highlighted is for the first `<!---->` part that had some content rendered in for the buggy website:

https://github.com/MarkBind/vue-strap/blob/9226252ae923f3463dcf56d356e3975295fafec6/src/Popover.vue#L3-L4

(btw ignore the `<!--` `-->` in the source, this is **not** the `<!---->` that you see in Chrome. Not sure why the original developers put that in, but we should have cleaned this up during the migration).

For the correct behaviour, when the reader hovers over the trigger, the second `<!---->` is the one that will be populated for revealing the content of the popover, as shown below:

![bug](https://user-images.githubusercontent.com/3168908/47763190-a9974d00-dcfa-11e8-887f-961d351ed822.gif)

Therefore, since the buggy website had the first `<!---->` populated, and it is always populated, I suspect that there could be some content inside the popover that is hindering the way that the popover code is being rendered, resulting in the logic inside the code I highlighted at the start being triggered, and the first `<!---->` being populated.

**Comment by damithc** [comment]
In my new PC I'm using MarkBind from a DOS window rather than GitBash (which was what I used when I posted this issue). I'm still getting the same problem :-(

![image](https://user-images.githubusercontent.com/1673303/50445307-da85ae00-0948-11e9-8d71-90e485e62fc3.png)

**Comment by damithc** [comment]
Still happening :-(

**Comment by damithc** [comment]
Example https://se-education.org/se-book/gatheringRequirements/interviews/

**Comment by damithc** [comment]
Turns out it was caused by a non-printable char in my code.
![image](https://user-images.githubusercontent.com/1673303/60502509-9062f800-9cf0-11e9-9326-ec785933cb7b.png)

How did I get it in my code? I use a text expansion tool to generate templates of frequently used code snippets. It turns out the offending char was in the code snippet template that I used (not sure how I got there in the first place). As the tool stores all my code snippets in a  cloud-backed database, I get the same hidden char every time I used that code snippet no matter which computer I use :-p
