### ISSUE TITLE
Provide a way for github repos to auto-deploy docs using Travis

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#457]
Current: the user has to specifically run the `markbind deploy` to deploy the site to GitHub. This is suitable for user docs which should only be deployed when a new version of the product has been released

Suggestion: Also provide a way to set up Travis so that docs are deployed everytime a specific branch is updated (e.g., `master`). 

Justification: When using Markbind for dev docs, docs needs to be auto-updated every time the master branch is updated.

Side note: in the longer term, it's ideal if ther is a way to maintain both user docs and dev docs in the same repo but update user docs only when there is a new release yet update dev docs everytime the master branch updates. Note sure if we can do that though. Until we get there, we can say that user docs site should be deployed to a separate repo.

**Comment by damithc** [comment]
> One way we can go about supporting this feature, is to extend #440 to allow specifying custom `.json` files for `markbind deploy`, and maintain two separate `.json` files for different scenarios (one for the user docs and one for the dev docs).

Yup, we'll need something like that if we want to support both types of docs in parallel. But before that, we need something like se-edu's auto-publish mechanism for Travis to push the site to repo's gh-pages branch right?

**Comment by yamgent** [comment]
> But before that, we need something like se-edu's auto-publish mechanism for Travis to push the site to repo's gh-pages branch right?

Yep, we could convert the logic of se-edu's auto-publish script [`deploy_github_pages.sh`](https://github.com/se-edu/addressbook-level4/blob/master/config/travis/deploy_github_pages.sh) into a specialized MarkBind command for Travis, so that the Travis build can just call `markbind deploy --travis` or something similar, instead of users having to maintain their own `deploy_github_pages.sh` for auto-publishing.
