### ISSUE TITLE
Support disqus

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#481]
We can support an easy way for authors to enable user comments using the Disqus tool

**Comment by VincentTam** [comment]
Disqus has a plethora of shortcomings that deter many bloggers, say

1. privacy issues
2. slow load speed
3. no markdown support
4. poor SEO
5. high cost of migration

You may refer to these articles to know more.

1. https://victorzhou.com/blog/replacing-disqus/
1. https://old.reddit.com/r/programming/comments/b9022a/switching_off_of_disqus_reduced_my_page_weight_by/
1. https://medium.com/remys-blog/ejecting-disqus-4120e9985823

A discussion about Disqus's replacement is available in https://github.com/Pelican-Elegant/elegant/issues/288.

**Comment by damithc** [comment]
Thanks for the heads up @VincentTam 
We'll take that into account when we implement this feature.

**Comment by damithc** [comment]
Up ...

**Comment by ang-zeyu** [comment]
> Disqus has a plethora of shortcomings that deter many bloggers, say
> 
> 1. privacy issues
> 2. slow load speed
> 3. no markdown support
> 4. poor SEO
> 5. high cost of migration
> 
> You may refer to these articles to know more.
> 
> 1. https://victorzhou.com/blog/replacing-disqus/
> 2. https://old.reddit.com/r/programming/comments/b9022a/switching_off_of_disqus_reduced_my_page_weight_by/
> 3. https://medium.com/remys-blog/ejecting-disqus-4120e9985823
> 
> A discussion about Disqus's replacement is available in [Pelican-Elegant/elegant#288](https://github.com/Pelican-Elegant/elegant/issues/288).

The speed is still an issue, but we could counter it by adopting lazy loading for the disqus component

I don't think markdown support is of concern to most users =P
On the flip side note that disqus has its own mini editor to include images / bold text / etc.

One could argue only the content of the site should be indexed and not the comments since it may have irrelevant content, hence indexing the comments actually hurts SEO; but either way the impact is really minor here.

Privacy is a thing, though I don't think it matters too much in the context of documentation / education sites.

Overall I think we should still go with disqus _first_ since it has the best integration and one of the few with an ad-based free plan, and is by far the most popular choice still even with its issues.
What do you think? @damithc @VincentTam

**Comment by damithc** [comment]
@ang-zeyu I agree. I'm OK to go ahead with Disqus first while we keep a lookout for better alternatives.

**Comment by ang-zeyu** [comment]
Noted, I'm thinking of making it a plugin first, with the configuration supplied under `pluginsContext`, so it is entirely opt-in.
The author would then be able to use it via a nunjucks variable `{{ disqus }}`, so one could easily insert it wherever desired (even in the expressive layouts file).

I'm not too sure about the [page identifier](https://help.disqus.com/en/articles/1717082-what-is-a-disqus-identifier) though, which is used to tie a thread to the page.
If we use the url (omitting the baseurl so that changes to it won't affect the identifier), the issue would be that once versioning is implemented, past threads' comments will not be correctly archived to the past pages as well and _will stay in the current version_.
I don't think there is any way around this automatically; disqus's [migration tools](https://help.disqus.com/en/articles/1717068-migration-tools) help in migrating to new urls and domains / merging threads but requires manual configuration.

This can actually be desired though (keeping top, useful comments across all versions), what do you think?

**Comment by damithc** [comment]
> This can actually be desired though (keeping top, useful comments across all versions), what do you think?

Yes, I don't mind that behavior.

**Comment by ang-zeyu** [comment]
or a component `<disqus>` may be better for extensibility; should be easier to implement as well
