### ISSUE TITLE
Improve the default `site.json` settings generated during init

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#507]
Justification: It lowers the initial barrier to entry as any folder with .md files can be served as a MarkBind site. The 'quick start' can omit mentioning `markbind init` and `site.json` altogether. 

If the site.json is missing, we can use defaults for all configuration options and consider all *.md and *.mbd files as pages.

**Comment by yamgent** [comment]
1. I feel that `markbind init` and `site.json` are pretty important concepts to teach the users upfront (since they form the core of MarkBind), and 'quick start' is the best place to do that. 
2. `markbind init` is easy to run anywhere. `init` does not pollute the user's folder structure much, so its effect is easily reversible if authors only want to try it out. We can tell the author to run `markbind init` and add `"glob": "*.md"` in `site.json` if they wish to try it on an existing folder.

**Comment by damithc** [comment]
Yes, it may be better to run `init` sooner than later. I'm also OK to expose the user to `site.json` early but I'd rather the user doesn't need to start tinkering with site.json right away. In other words, the site.json we generate should be good enough to last for a while. 

How about we do these changes to `markbind init`?
1. Don't overwrite index.md if it exists
2. Tweak site.json/pages to serve all .mbd and .md files
3. Tweak site.json/ignore to ignore git folder. and all .mbd files

**Comment by yamgent** [comment]
> * Don't overwrite index.md if it exists

This is already the behavior actually. In fact, all files inside `_markbind/` also follows the same behavior.

> * Tweak site.json/pages to serve all .mbd and .md files
> * Tweak site.json/ignore to ignore git folder. and all .mbd files

Seems like a reasonable plan, since ideally the initial `site.json` created by `init` should _be_ the default settings themselves.

Having all `.md` and `.mbd` files included is a sane default: I would think that authors should only have to worry about `site.json` when they require some additional setup, such as overriding the page title, rather than when they merely want to include a new `.md` file (in our current version, fiddling with `site.json` is a must once you have a file that is not `index.md`).
