### ISSUE TITLE
Support for bootswatch themes

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#547]
What do you guys think of adding support to themes provided by https://bootswatch.com/ ? Does our current architecture even suitable for that kind of theming support?

**Comment by yamgent** [comment]
Can be done by copying the content of the theme's `bootstrap.min.css` to the layout's `styles.css`. But two things come to mind:

1. Custom parts that does not use Bootstrap styles (e.g. site navigation and footer) are partially not affected by the theme.
1. Seems to be one of the scenario whereby having a `settings.md` for layout (#539) would be beneficial (rather than copying `bootstrap.min.css`'s content to `styles.css`).

Here is an example of using the Solarized theme on the default website:

![solarized](https://user-images.githubusercontent.com/3168908/50725051-8cd02900-1132-11e9-88d5-a62d45ac0aaf.png)

**Comment by yamgent** [comment]
> We can let the user specify the theme in the frontmatter, layout, or site.json?

If we are embedding the themes with MarkBind, then it could be as simple as telling the authors the filename of the themes to use.

**Comment by damithc** [comment]
> Definitely possible, there needs to be changes to the CSS files and HTML templates to use the Bootstrap styling classes, to be overridden by a theme seamlessly.

That's good. I think we need to provide some basic theming support or else all MarkBind sites will end up looking exactly the same :-p
