### ISSUE TITLE
Support jumbotron page header

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#549]
Example: from the markdownguide

![image](https://user-images.githubusercontent.com/1673303/50721663-1d404680-10fe-11e9-84a1-758be16299f1.png)

I wonder if we can provide support this kind of jumbotron to appear at the top of the page. The benefit is the site can be made to appear distinct simply by varying the background color. For project websites, the color can match the branding color of the project.

**Comment by Chng-Zhi-Xuan** [comment]
Implementation wise, it is quite simple with just a `<div>` and some custom `CSS`. 

Not sure if it is worth building an additional component (that is very similar to our existing `box` component).

**Comment by damithc** [comment]
> Not sure if it is worth building an additional component (that is very similar to our existing `box` component).

Hmm... doesn't the jumbotron (especially in this context) has different semantics? e.g., it should be edge-to-edge in the page but the text should be aligned to body text and it also affects the placement of components such as siteNav and pageNav.

![image](https://user-images.githubusercontent.com/1673303/50826109-c2188900-1375-11e9-9478-97ba37909ee6.png)

**Comment by Chng-Zhi-Xuan** [comment]
Thanks for the clarification, since in the original screenshot it just looked like a stand-alone `<div>` with its background changed.

The implementation just changes slightly. 

```html
<div class="my-jumbotron"> <!-- Using `position: fixed`, similar to `Navbar` component` -->
  <div class="same-classes-used-in-content-wrapper">
    <h2>Overview</h2>
    <p>Lorem Ipsum Lorem Ipsum.</p>
  </div>
</div>  
```

Both `site-nav` and `page-nav` will offset themselves automatically (same behaviour as `Navbar`). The inner `<div>` with mirrored classes should ensure the text is properly aligned with the rest of the content. 

We just have to pay attention to the `z-index` given to the jumbotron (less than `Navbar` and more than both `site-nav` and `page-nav`).

Another issue, **should we restrict the number of jumbotrons in a page?**

**Comment by damithc** [comment]
> Another issue, **should we restrict the number of jumbotrons in a page (to one)?**

If we name the component something more specific to its usage e.g., PageLead, it makes sense to restrict one per page.
