### ISSUE TITLE
Intra-page links are not compatible with GFMD

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#576]
v1.16.0

Current: The auto-generated link to heading `#Foo: Bar` will be `#foo-%3A-bar` instead of `#foo-bar` which is what GFMD generates.

Are we stuck with the curent or is it possible to go back to the previous GFMD-compatible state?

**Comment by damithc** [comment]
@jamos-tay @yamgent I remember this issue came up in a previous PR.  The current version is less author-friendly and also affects the ease of converting existing Markdown sites to MarkBind.

**Comment by yamgent** [comment]
We can revert back to the previous state (although we will have to implement the anchor name generation algorithm on our own, because it used to came from an outdated anchor package which we since upgraded).

Also, GFMD anchors are usually pretty strict, so for this case:

```markdown
# Some heading (extra)
```

The anchor will become `#some-heading-extra` instead of `#some-heading-(extra)`

**Comment by damithc** [comment]
> We can revert back to the previous state (although we will have to implement the anchor name generation algorithm on our own, because it used to came from an outdated anchor package which we since upgraded).

Let's go for it as the downsides of the current method are significant. 

> The anchor will become `#some-heading-extra` instead of `#some-heading-(extra)`

I guess we can live with that, especially because GFMD users are already accustomed to that system.

**Comment by yamgent** [comment]
Reopening this issue because the anchor generation fix is not done on the vue-strap's side.

**Comment by yamgent** [comment]
Switched to `p.Urgent` because this is blocking the release of the next version.
