### ISSUE TITLE
Support a header attribute for box components

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#61]
e.g. Something like this? Should be optional

![image](https://cloud.githubusercontent.com/assets/1673303/25617229/d6bab168-2f73-11e7-8d3d-982d8635b3a8.png)

**Comment by ang-zeyu** [comment]
Hi, I've implemented a preliminary version of this in my working copy. 
Looking for feedback on the styling / implementation.

It is added by including a `heading` attribute, for example `<box heading="Test heading">...</box>`

In addition, I'm unclear as to the workflow convention here when changes to vue-strap are required. 
Since all the changes were added in /vue-strap (save for `src/template/default/index.md`), should I make a pr to Markbind/vue-strap first and wait for the maintainers to update the dist and this repo, then make another pr to update index.md?

Or should my built vue-strap.min.js be pr-ed in this repo directly?

Diff: https://github.com/ang-zeyu/vue-strap/commit/499e8117d3ddaa3f56e50c5d4ae9fe6efad8862f

Current style:
![image](https://user-images.githubusercontent.com/3306138/70605758-112a0680-1c36-11ea-8b2d-df0c2ded3d14.png)

**Comment by damithc** [comment]
I'm OK with either style. Let's wait for a senior dev to answer your other query.

**Comment by yamgent** [comment]
> Since all the changes were added in /vue-strap (save for `src/template/default/index.md`), should I make a pr to Markbind/vue-strap first and wait for the maintainers to update the dist and this repo, then make another pr to update index.md?

Yes you should make a PR to MarkBind/vue-strap first. We generally do not update `vue-strap.min.js` in PRs, this is only done by repository maintainers themselves when doing release.

When you subsequently make another PR for the main MarkBind repo, you just need to mention that the new feature that you implemented in vue-strap was used. You don't have to wait for `dist/` to be updated before making this other PR.

**Comment by ang-zeyu** [comment]
Ok, thank you! @yamgent @damithc
