### ISSUE TITLE
<tooltip> example code uses undocumented option `effect`

### ISSUE THREAD

**Issue by Xenonym** [MarkBind/markbind#611]
**Tell us about your environment**

* **MarkBind Version:** 1.16.1

**What did you do? Please include the actual source code causing the issue.**
In our [documentation for the `<tooltip>` component](https://markbind.github.io/markbind/userGuide/usingComponents.html#tooltip), we use the `effect="scale"` option in the example code, which is not documented.

**What did you expect to happen?**
The `effect` option should be documented, or be removed depending on what should be the actual effect of `effect` (I tried `effect="fade"` like other components, but it didn't seem to work).

**Comment by Chng-Zhi-Xuan** [comment]
Within `Tooltip.vue`, only the `scale` effect's CSS is there, fade is not present that is why it doesn't work.

Yes, we should remove the example using `effect="scale"`, it is not necessary to specify the effect since the default value is already set to `scale`. 

Alternatively, support fade effect by inserting it into the CSS section of `Tooptip.vue` and document the feature. (Rigorous testing required to ensure fade effect isn't buggy)

**Side note:**

![tooltip-bug](https://user-images.githubusercontent.com/31084833/51463371-09ebd700-1d9e-11e9-95c3-bd9fd2801624.PNG)

Tooltip's hover example has the tooltip appear in the wrong location 😞. We either need to fix it or remove the example shown.

**Comment by damithc** [comment]
I don't mind removing support for the `effect` option as it doesn't seem to add much value.

**Comment by Xenonym** [comment]
Another minor nit: accidentally clicking on the `Markdown` example should not refresh the page.
