### ISSUE TITLE
Iconify pageNav when there is no space

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#616]
v1.17.0

Current: PageNav disappears when the page width is below a certain size

Suggested: Give some other way to access it if there is not enough space to show it. e.g., an iconified view that the user can click to expand?

**Comment by Chng-Zhi-Xuan** [comment]
Implementation wise, we can mirror the implementation of `site-nav`. However have 2 expandable bars (left and right) might take too much precious space (for mobile devices). Less time required to implement this.

A more integrated approach is having a second menu button appear below the `site-nav` menu button.

This will take more time to implement since:
- Need to ensure compatibility with existing `site-nav` code
- Account for all the different cases (`site-nav` still visible, `page-nav` collapsed) or (both `site-nav` and `page-nav` collapsed) etc.

Which do you prefer?

**Comment by damithc** [comment]
I prefer the first one. Perhaps we can find a way to prevent the iconified versions taking space? e.g., use a floating square (instead of a vertical column) with some transparency so that it doesn't take any extra space at all?

**Comment by Chng-Zhi-Xuan** [comment]
Yes it is possible to have a floating translucent button. We can refine the position and design once a working prototype is up (either from me or the CS3282 team 😃 )

**Comment by ang-zeyu** [comment]
closing as a possible specific solution to #980
