### ISSUE TITLE
Unexpected indentation in the first line of fenced text

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#618]
v1.17.0

Current:
![image](https://user-images.githubusercontent.com/1673303/51516815-95736f80-1e53-11e9-9d70-eae0572f017c.png)
Code:
![image](https://user-images.githubusercontent.com/1673303/51516830-ade38a00-1e53-11e9-894b-21896ce20728.png)

Problem: there seems to be an additional space at the start of the first line

**Comment by Chng-Zhi-Xuan** [comment]
**Cause:**

The `hljs` class is applied to the `<pre>` tag instead of the `<code>` tag when using the markdown code block syntax without specifying a language. 

This is due to some weird code, spotted by @amad-person when she was implementing the copy button for code blocks, within the Markdown-It library.

The underlying problem is that `<code>` tag has the `display` attribute default to `inline`, so only the first line within the `<code>` tag obeys the padding set by the element, while subsequent lines ignore the padding entirely.

**Comment by amad-person** [comment]
> The `hljs` class is applied to the `<pre>` tag instead of the `<code>` tag when using the markdown code block syntax without specifying a language.

Should we correct this in the code? The `hljs` class has `display: block` by [default](https://github.com/highlightjs/highlight.js/blob/master/src/styles/default.css), so adding the `hljs` class for `<code>` can fix the problem too.

**Comment by Chng-Zhi-Xuan** [comment]
I think we can correct this for now. Doesn't seem there is an example showing why the `hljs` class is inserted into `<pre>` instead of `<code>`. 

Do check if inline code blocks using single back quotes " ` " is intentionally putting the class in `<pre>` because we do not want `display: block` for inline elements.

**Comment by amad-person** [comment]
Inline code blocks with the `single back quote syntax` aren't being wrapped with a `<pre>` tag, I'm thinking this fix won't break existing behaviour:

<img width="879" alt="inline_code" src="https://user-images.githubusercontent.com/22164211/51590149-efdc0100-1f23-11e9-8400-cd49d5a9894a.png">
