### ISSUE TITLE
Variables in includes: provide a simpler syntax

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#642]
Current: syntax for specifying _include-variables_:
```html
<include src="foo.md">
  <span id="x">bat</span>
</include>
```

Suggested: also allow this syntax:
```html
<include src="foo.md" x="bat" />
```

Not sure how hard it is though.

**Comment by damithc** [comment]
> We should prefix variables (along the lines of [`data-*`](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes#HTML_syntax)) to not mix with attributes.

Good idea 👍

**Comment by yamgent** [comment]
Shouldn't be too hard to implement, we can use Cheerio to check the name of each attribute and process them if they have the `data-` prefix.

Of course, the content that these variables can have would be quite limited compared to the current way (e.g. you cannot put HTML code with the new syntax), but since we are supporting both version that shouldn't pose a problem.

**Comment by jamos-tay** [comment]
Sure, I'll wait for #627 to be merged first though cause there'll be conflicts
