### ISSUE TITLE
Allow any frontmatter property to be overridden by site.json

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#647]
Current: some frontmatter properties can be overridden by site.json, but not all.

Suggestion: allow any frontmatter property to be overridden by site.json

See discussion in #506

**Comment by damithc** [comment]
@jamos-tay this might fit with your current focus of standardizing the order of overriding

**Comment by jamos-tay** [comment]
Sure I can think of a fewof ways:

- Merge the site.config and frontmatter properties directly so anything can be overridden. The only problem is if frontmatter and site.json have conflicting properties. Say if we have a `title` property in site.json that represents the site title, we don't want to override the `title` property in frontmatter which represents a page title (just for example, I don't think we have any conflicting properties now)
- Specify all properties we can override, this is consistent with current behavior. Safest but requires more maintenance as more properties are added, also messy.
- Have a `frontMatter` property in site.json:
```
{
  ...
  "frontMatter" : {
    "title": ... // ovewrite stuff here
  }
}
```
As such all overridable properties that are currently in top level `site.json` will be moved here (`layout`, `tags` etc.) This one would require some tweaking to the current behavior though so it might end up breaking old sites.

**Comment by yamgent** [comment]
I think the override that we mean in this case is two things: (1) the `pages` in `site.json` overriding the actual page's `frontmatter`. (2) a global override inside `site.json` that applies to all pages, in which we can use your idea (the `frontMatter` property, but maybe we can name it `globalOverride` instead?).

Some properties does not make sense to have an global override (for example, the title, which means every page will have the same title for a global override). However, I don't think it warrants additional effort to specifically get rid of it, since authors can just choose not to use it. It also makes the thing easier to explain.
