### ISSUE TITLE
Allow accessing page variables from outside

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#682]
e.g., allow `<include src="foo.md#title"/>` (where `title` is a page variable in `foo.md`)

Some dicussion about this feature can be found [here](https://github.com/MarkBind/markbind/pull/627#issuecomment-460223203)

**Comment by jamos-tay** [comment]
Follow up from #735 

Okay, I'm having trouble with this too =P

We render the entire page's variables before any `include`s are processed, which means we can't read variables from inner files before hand. I probably have to read them separately, or work the page logic around so variables are rendered after `includes` (i.e. the preprocess step).

I think this is because the definition of a variable changed from 'global constant' to just 'a variable'. This affects the way they should be handled, so I think a rewrite might be in order.

**Comment by damithc** [comment]
yes, this one will be extremely challenging :-p
would something like this work? treat variables like global constants but internally prefix each with the path to the page e.g., `docs.userGuide.gettingStarted.title`. That way, they can be made visible everywhere but there is no danger of clashes.
Just a thought.

**Comment by acjh** [comment]
Further discussion about this feature can be found here: https://github.com/MarkBind/markbind/issues/674#issuecomment-462103962

**Comment by damithc** [comment]
Reopening as the corresponding PR has been reverted
