### ISSUE TITLE
Support custom boxes

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#69]
It's good if we create custom boxes (similar to current tip boxes) with a combination of color and icon.
```html
<box color="#42b0f4" icon=":rocket:">
    text
</box>
```

**Comment by yamgent** [comment]
One possible improvement to the original idea, is to add `color` and `icon` attributes to the existing tip-box component instead of creating a new box component.

This allows the user to inherit existing styles (e.g. the user may want to use the info tip-box, but still wants to override the icon with rocket)

```html
<tip-box type="info" icon=":rocket:">
    info but with rocket icon
</tip-box>
```

@damithc would that be good?

**Comment by damithc** [comment]
Yes, that works.
I'm in favor of using `box` instead of `tip-box` though: shorter and more generic.
