### ISSUE TITLE
Docs/drop-downs: documentation broken

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#704]
In _Using Components_ page:
![image](https://user-images.githubusercontent.com/1673303/52945982-f38d6700-33ad-11e9-856f-917290a9cebf.png)

In _Full Syntax Reference_ page:
![image](https://user-images.githubusercontent.com/1673303/52946057-10299f00-33ae-11e9-8e9c-f06a3b603736.png)

Also broken in _Reader-Facing Features_ page.

Not sure if I broke it during my recent PRs or it was broken to begin with :-p

**Comment by Xenonym** [comment]
Managed to track down the breaking change to #664 - the dropdown examples work at 185735ef8d9a5c6e32b81357c5c4bed51cbee30c but break at f9901fe7c8fe5b54e1ae8c59d0caeb1cc48f1daf. 

The generated source has multiple instances of:
```html
<span class="undefined temp-dropdown-placeholder">undefined</span>
```
Seems like anti-FUOC styles are not being applied properly for dropdowns in body text.

CC: @marvinchin 

Also: why are there 4 dropdowns in the example code but 7 dropdowns in the example output?

**Comment by damithc** [comment]
Thanks for looking into this @Xenonym 


> Also: why are there 4 dropdowns in the example code but 7 dropdowns in the example output?

This could be my doing. I was trying to simplify the examples. Maybe I simplified the code but forgot to do the same for the example output. Please fix that as well.

**Comment by marvinchin** [comment]
Thanks for spotting this! My bad for not noticing this when testing the anti-FUOC styles.

I've taken a look into it and there seem to be several issues causing this:
- Generation of placeholder span elements for dropdowns produce `<span class="undefined temp-dropdown-placeholder">undefined</span>` when the dropdown does not have a class and text. This was because of a mistake in string interpolation on my part. 
- `removeTemporaryStyles` (along with everything else in `executeAfterMountedRoutines`), which removes the placeholder classes and elements are not executed for content that is collapsed during initial render. This is the case for the `Full Syntax Reference` page.
- Somehow, a stray `<p>` tag is being inserted before the placeholder `<span>`. I've narrowed where this happens to `parser.js`, but will require a little more time to investigate why it is being added.

With regards to 

> `removeTemporaryStyles` (along with everything else in executeAfterMountedRoutines), which removes the placeholder classes and elements are not executed for content that is collapsed upon initial render. This is the case for the `Full Syntax Reference` page.

I'd like to ask the following:
- Do we need to apply the other methods in `executeAfterMountedRoutines` to the content in collapsed components?
- Can/Should we limit the application of anti-FUOC styles only to components within the `<navbar>`?
