### ISSUE TITLE
Fix missing space in log output

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#738]
Current:
![image](https://user-images.githubusercontent.com/1673303/53677892-46421980-3cf2-11e9-9c52-df28cc1585c3.png)

A space is missing? This can be phrased in a more readable way? e.g., `1234 ms`

**Comment by tawAsh1** [comment]
Hello.

Is this output necessary?
As far as I saw the code here, it seems that the site creation time has already been output in here "Website generation complete! Total build time: 6.126s".

https://github.com/MarkBind/markbind/blob/ba77643a598d80fe6c0255e068fc474822c03360/src/Site.js#L506-L536

**Comment by damithc** [comment]
> Is this output necessary?

Good question. The two numbers seem to differ slightly though. Let's wait to hear from a senior developer.

**Comment by yamgent** [comment]
Yes, this line popped up because we now print everything to the console since https://github.com/MarkBind/markbind/pull/721 came. Previously it was hidden inside the log, and never printed on the console.

The duration given by the profiler is always printed regardless of whether the site builds successfully or not (which is why it takes a slightly longer time before printing, compared to the one that prints straight away immediately after the generation is complete).

I don't think it is useful to print the duration when the site fails to build, so it should not be shown to the authors. Instead, we should explore downgrading the log levels for profiler messages, so that it doesn't show up on "info:" level.
