### ISSUE TITLE
Dynamic-panel in submodule not working

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#79]
website: schedule static-includes text book page which dynamic-includes another page from text book, and works as expected.

https://markbind.github.io/cs2103-website/

![image](https://user-images.githubusercontent.com/1673303/28301687-178e4e60-6bbb-11e7-9af4-35566b02fc5f.png)

Same text book page accessed directly, the dynamic include does not work.

https://markbind.github.io/cs2103-website/book/gitAndGithub/init/

![image](https://user-images.githubusercontent.com/1673303/28301723-4a06df74-6bbb-11e7-91ff-a239a554372e.png)

But the same page accessed from se-book site works fine.

https://markbind.github.io/se-book/gitAndGithub/init/

![image](https://user-images.githubusercontent.com/1673303/28301739-798a42e0-6bbb-11e7-9416-7cbf1c3581a8.png)

**Comment by acjh** [comment]
This occurs because `markbind-cli` determines new `baseUrl` for submodules in [Page.js#L61](https://github.com/MarkBind/markbind-cli/blob/5ca989faa145cb874a5ef4f97a3c4d5472757d22/lib/Page.js#L61).

This correctly resolves `{{baseUrl}}` references for the submodule to `/cs2103-website/book`,
e.g. `{{baseUrl}}/css/textbook.css` → `/cs2103-website/book/css/textbook.css`
but wrongly resolves relative includes (as above) that only require prepending `/cs2103-website`.

**Comment by damithc** [comment]
Good work @acjh Any suggested solution?

**Comment by acjh** [comment]
We can:
1. Handle original `{{baseUrl}}` strings and generated references differently.
This may use custom annotations in temporary files, e.g. `{{host-baseUrl}}`.
2. Convert `{{baseUrl}}` strings in submodules to be relative to the host project,
e.g. `{{baseUrl}}/css/textbook.css` → `{{baseUrl}}/book/css/textbook.css`.

I prefer `1` because `2` may require modifying all submodule files by string-replace.

**Comment by damithc** [comment]
Submit a PR if you can. Not sure when @Gisonrg can review though (I think he is travelling these days)

**Comment by Gisonrg** [comment]
@acjh's fix is working on my side, I'll let @damithc to check it and close this issue :)

**Comment by damithc** [comment]
Thanks @Gisonrg Let us know when the new version is out :-)

**Comment by damithc** [comment]
The loading problem seems to be fixed :+1: but the image links in the loaded page are broken now :-(
![image](https://user-images.githubusercontent.com/1673303/28709662-c55621da-73b3-11e7-93d2-caff43c57845.png)

**Comment by Gisonrg** [comment]
@damithc Just pushed this fix, try `npm i -g markbind-cli@1.3.5` to try it :)

**Comment by damithc** [comment]
Seems to work. Good work @acjh and thanks @Gisonrg :+1:
