### ISSUE TITLE
sitenav appears above the topnav dropdowns

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#802]
v2.0.0

![image](https://user-images.githubusercontent.com/1673303/55320370-7a535a80-54a9-11e9-9d4c-01c3e5d7e877.png)

**Comment by Chng-Zhi-Xuan** [comment]
A fix was done for Typeahead (search bar). Looks like this has to be done as well.

Details of the fix in the Commit Message [here](https://github.com/MarkBind/vue-strap/pull/101/commits/9a4a075bb8059193b46b34b6e1fdccb0348b247c)

**Comment by damithc** [comment]
Just realized that items are not clickable either. As such, a fix is needed pronto.

**Comment by marvinchin** [comment]
I've made a PR (https://github.com/MarkBind/vue-strap/pull/103) that uses the same fix as https://github.com/MarkBind/vue-strap/pull/101/commits/9a4a075bb8059193b46b34b6e1fdccb0348b247c.

However, https://github.com/MarkBind/vue-strap/pull/102 has been merged to vue-strap, but the corresponding PR in markbind https://github.com/MarkBind/markbind/pull/797 has not been merged. This causes our current navbar styles to break (they all turn blue).

![Screenshot 2019-04-01 at 8 02 42 PM](https://user-images.githubusercontent.com/17447681/55325952-1fc1fa80-54b9-11e9-8fda-ce32248ed555.png)

I'm thinking we either need to:
- Wait for #797 to be merged before releasing this fix (if severity of this issue is not high)
- Revert https://github.com/MarkBind/vue-strap/pull/102 in vue-strap master and create a new vue-strap release without those changes so that this fix can be released immediately
- Create an emergency build of vue-strap that includes https://github.com/MarkBind/vue-strap/pull/103 but without https://github.com/MarkBind/vue-strap/pull/102 that serves as a hotfix until the corresponding changes can be merged and properly released

What do you guys think about this?

cc: @yamgent @luyangkenneth

**Comment by luyangkenneth** [comment]
I think #797 is ready to be merged (pending action from anyone with merge privileges). Seems to me that it's the most straightforward way to unblock this fix.

**Comment by yamgent** [comment]
Double checked, MarkBind/vue-strap#103 fixed the issue. Since this is a critical bug, will make a new release soon.

**Comment by damithc** [comment]
Working. Thanks for the fix 👍
