### ISSUE TITLE
Migrate all MarkBind components from vue-strap to bootstrap-vue

### ISSUE THREAD

**Issue by luyangkenneth** [MarkBind/markbind#814]
The end goal here is to remove our dependency on vue-strap altogether. This is a major investment, so the team will have to make the choice of whether (or better yet, _when_) to prioritize this over feature work.

Related discussion:
- #411 illustrates the inconveniences of working with vue-strap
- #245 discusses the incentives of such a migration and what work it will involve

**Comment by damithc** [comment]
Would this solve FOUC problem?

**Comment by yamgent** [comment]
> Would this solve FOUC problem?

No, bootstrap-vue doesn't have anti-FOUC mechanisms.

**Comment by damithc** [comment]
Which components are pending migration?

**Comment by Chng-Zhi-Xuan** [comment]
Instead of modifying our current files `Vue.js` component files, I suggest we fork Bootstrap-Vue (removing vue-strap dependencies + security vulnerabilities) and start building templates to preserve MarkBind syntax.

If we were to take this approach, all the components will need their own template. Components that do not exist in `Bootstrap-Vue` such as panels, would have to be re-written (with the existing vue-strap code to serve as a guide).

**Comment by nbriannl** [comment]
May I clarify if this direction to migrate to bootstrap-vue is still actively being pursued? Or are we deciding to stick with our fork of VueStrap? Considerable improvements have been made so far especially updating of dependencies https://github.com/MarkBind/vue-strap/pull/130.

I was considering to investigate and possibly implement some PRs for vue-strap related to testing, but if the end goal is still bootstrap-vue then I'll divert my efforts elsewhere. 🙂

**Comment by kaixin-hc** [comment]
Trying to understand the relevance of this issue 6 years on is a bit tricky due to the changes since then. Let me summarise what I figured out...

===OG state of issue===
`vue-strap` was being maintained as a separate fork. #411 and #245 talk mainly about the inconveniences of working with a separate fork (eg - having to manually copy over, duplicating docs, etc and the reasoning behind it especially when the original repository was unmaintained. Our fork became quite markbind specific and fairly tightly coupled to markbind.

In June 2020, vue-strap was merged in as a scoped package `vue-components` 

3 components (Modals, Tooltips, Popovers were migrated to bootstrap-vue, which was at that time actively maintained) Triggers might have been migrated but they don't seem to be any more. The summary of discussion in [this comment in #1332](https://github.com/MarkBind/markbind/pull/1332#issuecomment-743769904) includes several of the concerns at the time as well as the reasoning and the decision not to depend on bootstrap-vue but rather implement the features we want from boostrap vue for 1) flexibility with our own components 2) increased coupling and complexity -- particularly as certain features (dropdowns, navbars) are already pretty markbind specific/dependent.

Then, with bootstrap getting bumped to v5. bootstrap-vue did not support v5, but the v5 features were useful to MarkBind. Hence, in 2022, Modals were migrated to depend on vue-modal and tooltips and popovers were switched to floating vue - as this provided additional reactivity and prevented ssr issues. 

MarkBind was bumped to Bootstrap v5. bootstrap-vue still does not support v5, and hasn't had a commit for 10 months. I think we can conclude this is unlikely. Furthermore, with vue-strap incorporated as a markbind scoped package we no longer face the inconveniences that motivated this issue.

So I'll close this issue now!
