### ISSUE TITLE
Document how to use URLs in _markbind/* files

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#820]
Previously, we used `{{ baseUrl }}` in `_markbind/*` files. e.g., `_markbind/head/*`. Now, we no longer need to use `{{ baseUrl }}` (is that correct?).

In that case, we need to update the documentation of those files ([example](https://markbind.org/userGuide/tweakingThePageStructure.html)) and also mention what is considered as the 'current directory' when giving URLs in those files.

**Comment by damithc** [comment]
@sijie123 @Chng-Zhi-Xuan  can look into this?

I'm a bit puzzled by why we use `../` in https://raw.githubusercontent.com/MarkBind/markbind/master/docs/_markbind/headers/header.md.

**Comment by yamgent** [comment]
> I'm a bit puzzled by why we use `../` in https://raw.githubusercontent.com/MarkBind/markbind/master/docs/_markbind/headers/header.md.

This is an error on our part, the `../` is probably unnecessary. It did not break anything because the current working directory for such files is the root, so going "up" a level does nothing at all (i.e. `https://markbind.org/../showcase.html` is the same as `https://markbind.org/showcase.html`).

**Comment by yamgent** [comment]
Nevermind, just did a check locally, seems like that's not the case, the `../` was intentional so as to back up to the correct root directory for some pages.

**Comment by damithc** [comment]
I feel like there is something amiss w.r.t. this use case. I suspect users still have to use `{{ baseUrl }}` in these files for them to work under all circumstances.

**Comment by sijie123** [comment]
I believe the reason why it's a blanket `../` partially stems from legacy - we always used `../`. This is because header.md could be included from within `userGuide/`. Using a blanket `../` allows any md file within the userGuide to correctly refer to the root directory.

More recently, header.md was moved into `_markbind/header/`. This does not change its behaviour. All files still include header.md implicitly using frontmatter. The context from which header.md is imported still does not change - files within `userGuide/` still need `../` to refer to the root directory.

Similarly, the relative URL change does not alter this behaviour. It's necessary that files within the userGuide refer to our main index page as `../index.html`. Simply using `index.html` refers to `userGuide/index.html`.

That said, it is correct that if we have more nested folders, within `userGuide/` or otherwise, the URL reference will be incorrect. It's probably better to refer to these links as absolute `{{baseUrl}}/` references instead.

**Comment by damithc** [comment]
> That said, @damithc is right about his intuition: if we have more nested folders, within `userGuide/` or otherwise, the URL reference will be incorrect. It's probably better to refer to these links as absolute `{{baseUrl}}/` references instead. This incorrect reference has been there for a while, and has been alright only because files that are directly accessible are never nested more than 2 layers deep.

I think we need to mention this when we explain intra-site links in user docs.
