### ISSUE TITLE
Separate UG and DG

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#833]
Current: both UG and DG are in the same site, deployed to markbind.org
Objective: to separate the two so that DG can kept in sync with the master branch head while UG can kept in sync with the latest release. Furthermore, the two can have two different Aloglia search indexes if we switch to Algolia search in future.

### Suggested plan (up for discussion):

Keep all source code in `markbind` repo, but generate three sites
1. UG+DG
   * This will be used for Netlify preview of any changes to UG or DG
   * specified in `site.json`:  UG+DG. 
2. UG
   * specified in `ug-site.json`: Omits all DG pages
   * Deploy UG site to markbind.org at release
3. DG
   * specified in `dg-site.json`: Omits all UG pages
   * Use Travis to auto-push DG site to to gh-pages markbind.github.io/devdocs when master branch is updated

* File structure
  ```
  site.json
  ug-site.json
  dg-site.json
  index.md
  userguide/
    └─ index.md
  devguide/
    └─ index.md
  ```

### Issues

* **How to build sites using different json files?**
  See #832 

* **How to make the root `index.md` file vary based on which site it is?**
  Use tags? e.g.,
  ```
  <span tags="ug">
    <include src="userguide/index.md" />
  </span>
  <span tags="dg">
    <include src="devguide/index.md" />
  </span>
  ```

**Comment by sijie123** [comment]
The idea of making the root `index.md` vary based on which site it is, is very helpful. However, this operation involves a rewrite on a scale similar to `convert relative src to absolute paths`, as we currently have no means of filtering by existence of tags. I think it would introduce a lot of bugs if we were to try and process this using markbind.
However, the idea is good because authors can easily write one page with content customised for potentially mutliple sites.
I was thinking if we could leverage Nunjucks to do this instead:
```
{% if "ug" in env %}
  <include src="userguide/index.md" />
{% endif %}
{% if "dg" in env %}
  <include src="devguide/index.md" />
{% endif %}
```
We define env in site.json (or somewhere similar), and it will look like
```
env: {
  "ug",
  "dg"
}
```
for a site that we want to deploy both ug and dg, or it will look like
```
env: {
  "ug"
}
```
for a site where we only want to deploy the ug.

**Comment by damithc** [comment]
> The idea of making the root `index.md` vary based on which site it is, is very helpful. However, this operation involves a rewrite on a scale similar to `convert relative src to absolute paths`, as we currently have no means of filtering by existence of tags. I think it would introduce a lot of bugs if we were to try and process this using markbind.

We have [this feature](https://markbind.org/userGuide/usingPlugins.html#filtertags-toggling-alternative-contents-in-a-page) already. In fact I tried it out before posting this suggestion.

**Comment by sijie123** [comment]
Oh! I didn't know we have this feature... 😝 
Yes, this makes it very easy for us to implement and for users to use the feature.
Thank you so much!

**Comment by damithc** [comment]
> Oh! I didn't know we have this feature... 😝

It's thanks to @jamos-tay's good work. It was not an easy feature to implement I believe.
