### ISSUE TITLE
Add an issue template for feature requests

### ISSUE THREAD

**Issue by amad-person** [MarkBind/markbind#834]
Currently, our issue template assumes that the user always wants to post a bug report. If a user wants to submit a feature request, we wouldn't want them to use the bug report issue template. Let's add an issue template for feature requests.

Resources:
1. GitHub documentation: https://help.github.com/en/articles/creating-issue-templates-for-your-repository
2. Example for manually creating different templates: https://github.com/gatsbyjs/gatsby/tree/master/.github/ISSUE_TEMPLATE

**Comment by raivatshah** [comment]
Hi, I'd like to help with this issue but it turns out that I cannot access the "settings" of this repo unless I'm a contributor already. I tried forking the repo and accessing its settings but those settings don't allow me to use templates. Must I duplicate the entire repo to access the "settings" ?

**Comment by yamgent** [comment]
Hi @raivatshah, the templates can be manually created without accessing the repo's setting, see this link for example: 

> 2\. Example for manually creating different templates: https://github.com/gatsbyjs/gatsby/tree/master/.github/ISSUE_TEMPLATE

**Comment by raivatshah** [comment]
Thanks @yamgent
