### ISSUE TITLE
Support puml files in boilerplates

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#926]
see [this comment](https://github.com/MarkBind/markbind/pull/919#issuecomment-509477742)

**Comment by nbriannl** [comment]
I think we can close this issue.

**Comment by damithc** [comment]
> I think we can close this issue.

Just to confirm,
* do boilerplates now support puml files?
* does live loading work when a puml file included in a boilerplate is updated?

**Comment by yamgent** [comment]
> * do boilerplates now support puml files?

Tested it and seems to be working, was also [commented](https://github.com/MarkBind/markbind/pull/919#issuecomment-511657479) in the original PR, that the source of the bug was just due to the fact that the paths were resolved wrongly (even for non-boilerplates).

> * does live loading work when a puml file included in a boilerplate is updated?

Also seems to work. I guess this issue is resolved then.
