### ISSUE TITLE
Nested dynamic includes working locally, but not on gh-pages

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#93]
Works correctly in local server (http://127.0.0.1:8080/website/book/common/outcomes.html):
![image](https://user-images.githubusercontent.com/1673303/29011013-360c0d62-7b62-11e7-8bc6-3d552259ecbd.png)

On gh-pages (https://nus-cs2103.github.io/website/book/common/outcomes.html):
![image](https://user-images.githubusercontent.com/1673303/29011039-66f681be-7b62-11e7-86b5-269101c70ad9.png)

Same page embedded in another place (https://nus-cs2103.github.io/website/book/modeling/):
Works in the first level, but breaks in the next level.

![image](https://user-images.githubusercontent.com/1673303/29011067-abb00f78-7b62-11e7-8bf7-2fe43c03cf7b.png)

I'm guessing the error is triggered when a dynamically included page includes another dynamically included page and possibly specific to Unix (my local computer is Windows), or the web server used by GitHub.

**Comment by damithc** [comment]
@Gisonrg (if you are back), @acjh please have a look. Need to fix quickly as I intend for the website to go live in the next couple of days 😓

**Comment by Gisonrg** [comment]
I will take a look tonight, need to check the console error on the deployed
gh-pages.
But I maybe slow as have work in the day time, meanwhile Aaron feel free to
fix it if you find anything. Thanks.

**Comment by acjh** [comment]
Found the cause and fixed this, but also found a related error. I'll fix that too and submit a PR in a bit.

**Comment by acjh** [comment]
Ignore the *related error*, it came up because I was troubleshooting the `nunjucks.renderString` API.
This was tricky to debug because `{{hostBaseUrl}}` is removed if not passed in as context parameter.

It works correctly in local server because `markbind` serves both `127.0.0.1` and `127.0.0.1/website`, so `/book/...` appeared valid locally but not when hosted by GitHub only on `...github.io/website`.

I checked that `_site` does not contain any more occurrences of `src="/book`, so the fix should work.
