### ISSUE TITLE
static includes that target a div: re-basing links doesn't work

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#94]
Given this code `[link]({{baseUrl}}/common/print.html)` in `book/usage.md` which is included in `schedule\overview\about.md` 
![image](https://user-images.githubusercontent.com/1673303/29060058-c55d44f2-7c4a-11e7-9c55-4d302fdbe7da.png)
![image](https://user-images.githubusercontent.com/1673303/29060078-d359145a-7c4a-11e7-8ebd-9b0ffc95a131.png)

`<include src="../../book/about/usage.md"/>` : link works
`<include src="../../book/about/usage.md#printing"/>` : produces a broken link
`<include src="../../book/about/usage.md#printing" dynamic/>` : link works

Looks like re-basing links doesn't work for static includes that targets a div (rather than entire page)

**Comment by damithc** [comment]
@acjh have a look at this when you have some time. This is a fundamental issue that is going to cause problems sooner or later.

**Comment by acjh** [comment]
Noted.

**Comment by acjh** [comment]
Investigated "re-basing links" which led me to [parser.js#L456](https://github.com/MarkBind/markbind/blob/a2969d9c0e092aeecbe5cd6aeb2811a94353b3a8/lib/parser.js#L456), but that doesn't seem to be the cause.
I'll see if I can take a look along the lines of "static includes that targets a div" tomorrow and get back.

**Comment by damithc** [comment]
@acjh thanks for the follow up. When the entire page is included, there is no problem. So it is likely to be some function not being called when a only div is included. Were you able to reproduce the problem?

**Comment by acjh** [comment]
I was able to reproduce:
- `<include src="../../book/about/usage.md"/>`

but not:
- `<include src="../../book/about/usage.md#printing"/>`
- `<include src="../../book/about/usage.md#printing" dynamic/>`

**Comment by damithc** [comment]
Try changing line 37 of this file https://github.com/nus-cs2103/website/edit/master/schedule/overview/about.md

Currently `<include src="../../book/about/usage.md#printing" name="Printing" dynamic/>` which works.
But if I change it to `<include src="../../book/about/usage.md#printing" />` the link produced is incorrect.

**Comment by acjh** [comment]
Okay, I can reproduce:
- `<include src="../../book/about/usage.md#printing"/>`

and:
- `<include src="../../book/about/usage.md"/>`
- `<include src="../../book/about/usage.md#printing" dynamic/>`
- `<include src="../../book/about/usage.md#printing" name="Printing" dynamic/>`

---
I suspect it's [`parser#L105`](https://github.com/MarkBind/markbind/blob/a2969d9c0e092aeecbe5cd6aeb2811a94353b3a8/lib/parser.js#L105) using `actualContent` directly without rebasing `{{baseUrl}}`.
I'll investigate further and work on a fix.

**Comment by acjh** [comment]
Hmm, `actualContent` is handled similarly regardless whether there's an `includeSrc.hash`.
The difference is that [`htmlContent`](https://github.com/MarkBind/markbind/blob/a2969d9c0e092aeecbe5cd6aeb2811a94353b3a8/lib/parser.js#L97) is no longer in a `div` after extracting `.html()` of target.

Still looking...

**Comment by acjh** [comment]
Regardless whether there's an `includeSrc.hash`,
both cases give `{{baseUrl}}/common/print.html` in `result` on [Page.js#L139](https://github.com/MarkBind/markbind-cli/blob/3d6c6ca693ed881170fd62717143cd48686e3c76/lib/Page.js#L139),
but without hash gives `{{baseUrl}}/book/common/print.html` on [Page.js#L147](https://github.com/MarkBind/markbind-cli/blob/3d6c6ca693ed881170fd62717143cd48686e3c76/lib/Page.js#L147).

So it's handled differently in `Parser.prototype.resolveBaseUrl` on [parser.js#L382-L419](https://github.com/MarkBind/markbind/blob/a2969d9c0e092aeecbe5cd6aeb2811a94353b3a8/lib/parser.js#L382-L419).

**Comment by acjh** [comment]
> The difference is that [`htmlContent`](https://github.com/MarkBind/markbind/blob/a2969d9c0e092aeecbe5cd6aeb2811a94353b3a8/lib/parser.js#L97) is no longer in a `div` after extracting `.html()` of target.

Following from the above observation,
I used [`$.html(includeSrc.hash)`](https://github.com/cheeriojs/cheerio#rendering) to get the outerHTML instead of `$(includeSrc.hash).html()`.
This works and is functionally similar, but includes the container element in the resulting HTML.

I consider this a workaround rather than a solution (assuming the expected behaviour is innerHTML).

---
> So it's handled differently in `Parser.prototype.resolveBaseUrl` on [parser.js#L382-L419](https://github.com/MarkBind/markbind/blob/a2969d9c0e092aeecbe5cd6aeb2811a94353b3a8/lib/parser.js#L382-L419).

`resolveBaseUrl` calls `_rebaseReference` on [parser.js#L421-L467](https://github.com/MarkBind/markbind/blob/a2969d9c0e092aeecbe5cd6aeb2811a94353b3a8/lib/parser.js#L421-L467) (back to my [initial guess](https://github.com/MarkBind/markbind/issues/94#issuecomment-322054345)).

I think the innerHTML may be treated like a [text node](https://github.com/MarkBind/markbind/blob/a2969d9c0e092aeecbe5cd6aeb2811a94353b3a8/lib/parser.js#L428) if it doesn't have any containing `div`.
However, the text nodes seem to contain only `data='\n'` whenever I try to `console.log` it.

**Comment by Gisonrg** [comment]
> I think the innerHTML may be treated like a text node if it doesn't have any containing div

I agree on this. As rebasing url is a non-trivial issue, it is not tested through-fully during the implementation (as that time the priority is to allow website include se-book without changing base).

Because for static rebasing, it is happened before the markdown content getting rendered ([here](https://github.com/MarkBind/markbind-cli/blob/90d0fbaac73b457dda44e51cb496657ab73efb72/lib/Page.js#L44)), the link using MD format is not considered a valid html node for the parser. A [parsing test](https://astexplorer.net/#/gist/76c06ab29f4c2ac050374aa6025a88fe/980d7d061e3669b49351a0900a08adc33295a944) also confirmed on this.

As for dynamically loaded content, it will be parsed into HTML before it is retrieved and rebased to be used by the host page, that's why it should work properly.

If we want to resolve this, we may need to do something to the test node...

> I used $.html(includeSrc.hash) to get the outerHTML instead of $(includeSrc.hash).html().

We better not use outerHTML just to handle this case. It may break other working links.

**Comment by acjh** [comment]
> We better not use outerHTML just to handle this case. It may break other working links.

Agreed.

**Comment by acjh** [comment]
Revisiting this issue.

> I think the innerHTML may be treated like a text node if it doesn't have any containing `div`.

I skipped the check for this case, then realised that `path` on [parser.js#L440](https://github.com/MarkBind/markbind/blob/d0a849622643bf25a778287c9584223df57ddd04/lib/parser.js#L440) does not contain **book**.
So I backtracked and found that *static includes* already assign `actualContent` before rebase occurs:

https://github.com/MarkBind/markbind/blob/d0a849622643bf25a778287c9584223df57ddd04/lib/parser.js#L105

I'll work on this angle.
