### ISSUE TITLE
Unexpected behaviour of components when immediately prepended by GFMD

### ISSUE THREAD

**Issue by ang-zeyu** [MarkBind/markbind#958]
**Tell us about your environment**

* **MarkBind Version:** 2.70
* also tested on the latest master, briefly

**What did you do? Please include the actual source code causing the issue.**

In general, any markdown + html with the following format causes the issue
```html
markdown pre text **immediately** prepending a component, without an empty line after
<box or panel>
line 1 which behaves as per normal ( empty line still counts )
--empty line--
lines 3 onward are 'placed' outside of the component
...
...
</box or panel>
```
Only tested with box and panels, since that is likely the only places multiple paragraphs would be used.

Exceptions for the markdown pre text ( as far as I have found, exhaustively tested from this list https://markbind.org/userGuide/formattingContents.html ):
- markdown headings ( # ... )
- code blocks ( ``` ... ``` )
- markdown tables
- video embeds ( but the video disappears, leaving the link remaining instead )
- lists / blockquotes without content ( e.g. `>` does not produce the issue but `> some text` does. )

_Example 1 (boxes):_

![example1](https://user-images.githubusercontent.com/3306138/71280734-0a6a6480-2397-11ea-86cc-01dbdb2b5d56.png)

_Example 2 (panels):_

![example2](https://user-images.githubusercontent.com/3306138/71280982-bca22c00-2397-11ea-9620-b5cfa0f971bd.png)

**What did you expect to happen?**

The multiple paragraphs should be chucked into the component itself, like so

_Example 2:_ ( result achieved by leaving an empty line between the pre text and component )
![expected2](https://user-images.githubusercontent.com/3306138/71281068-fbd07d00-2397-11ea-9df0-ce8035d9da7d.png)

**What actually happened? Please include the actual, raw output.**

The subsequent paragraphs after the first are appended after the component

_Example 1:_
![result1](https://user-images.githubusercontent.com/3306138/71280741-0e968200-2397-11ea-916b-f87941598ed5.png)

_Example 2:_
![result2](https://user-images.githubusercontent.com/3306138/71280995-c0ce4980-2397-11ea-824f-d8f1f7684478.png)

**Comment by wxwxwxwx9** [comment]
@ang-zeyu I've looked into this issue and here's what I discovered so far. 

From my investigation, the problem stems from `markdown-it` parsing. 

Using your example, refer to [here](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22pre-text%5Cn%3Cpanel%3E%5CnNote%20that%20%60Layout%60%20instances%20do%20not%20generate%20any%20output%20files%20directly%2C%20but%20rather%2C%20they%20store%20intermediate%20processing%20results%20to%20be%20used%20in%20a%20%60Page%60.%5CnNote%20that%20%60Layout%60%20instances%20do%20not%20generate%20any%20output%20files%20directly%2C%20but%20rather%2C%20they%20store%20intermediate%20processing%20results%20to%20be%20used%20in%20a%20%60Page%60.%5Cn%5CnNote%20that%20%60Layout%60%20instances%20do%20not%20generate%20any%20output%20files%20directly%2C%20but%20rather%2C%20they%20store%20intermediate%20processing%20results%20to%20be%20used%20in%20a%20%60Page%60.%5Cn%3C%2Fpanel%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D) to see how it is parsed by `markdown-it` in MarkBind currently. Note that the `html` checkbox on the website is ticked because that's the setting we are using in MarkBind currently (as shown below). 

![Screen Shot 2021-04-16 at 4 19 30 PM](https://user-images.githubusercontent.com/37920115/114994614-87e0af00-9ecf-11eb-8671-1b30ec731947.png)

Due to the way `markdown-it` parses that block of code, you can see `lines 3 onward are 'placed' outside of the component` occurs. You can throw the markdown parsing output into a html beautifier to see the outcome more clearly. 

Now, if we were to change `panel` in the source code to `div`, we would see that we achieve the html structure outcome that we would expect for `panel`, that would not lead to the `lines 3 onward are 'placed' outside of the component` problem. And that is because `markdown-it` automatically closes the first `<p>` tag as [`<div>` tag cannot be nested within `<p>` tag](https://www.google.com/search?q=nesting+div+in+p&oq=nesting+div+in+p&aqs=chrome..69i57j33i22i29i30l6.3714j1j7&sourceid=chrome&ie=UTF-8). Since `<panel>` would not get the same treatment as `<div>` (as `<panel>` is a custom element), the problem of `lines 3 onward are 'placed' outside of the component` then occurs.

It seems like we will have to patch `markdown-it` somehow to get it to recognize some of our custom tags (e.g. box) as a block-level element so that this can be resolved. 

Just wanted to share my findings with you before I go ahead with a patch, in case you have any ideas / advice.

What do you think? :-)

**Comment by ang-zeyu** [comment]
yup, we might also reference vuepress' solution for this. (though, be careful with `<panel>`s in particular as mentioned https://github.com/MarkBind/markbind/pull/1534#pullrequestreview-637316649)
