### ISSUE TITLE
Adding a file is shown as 'assets removed' in the console

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#970]
v2.8.0
When a file is added/removed while the author is in live-preview mode, MarkBind does a full rebuild of the previewed site, while showing a warning to the user.
![image](https://user-images.githubusercontent.com/1673303/71761084-dd26c600-2f01-11ea-9cd0-9dc655bf7762.png)

In the warning message, `assets removed` is shown even when a file is added. Rephrase as `assets removed or added`?

Furthermore, the `assets removed` should appear above the `warn` rather than the below (because effect should follow the cause)?

**Comment by yamgent** [comment]
The log `Assets removed` happens when files inside the `_site/` folder is being deleted, it wasn't meant to mean that the author has deleted a particular file in their website. (An example of an asset would be images generated by PUML, such as `docs/userGuide/diagrams/usecase.png`).

However, I do realise that the method for deleting assets will always print `Assets removed`, even if `filePaths` ends up to be empty. Perhaps the method can be improved to avoid printing the log if there's no assets to delete:

https://github.com/MarkBind/markbind/blob/2ebee6390b88a819604b4e5ff2ee44ee26f7b25d/src/Site.js#L622-L631

**Comment by damithc** [comment]
Seems like that particular message is an internal detail not relevant to authors. In that case, not show it at all?

**Comment by yamgent** [comment]
> Seems like that particular message is an internal detail not relevant to authors. In that case, not show it at all?

Yeah that's true, it can be relegated to a "DEBUG" category.

**Comment by nbriannl** [comment]
If it's relegated to a DEBUG category, is there an existing way to start `markbind` with DEBUG logs printed?

**Comment by yamgent** [comment]
> If it's relegated to a DEBUG category, is there an existing way to start `markbind` with DEBUG logs printed?

No existing way (although `_markbind/logs/*.log` logs should already show categories by default).
