### ISSUE TITLE
Footnotes inside panels don't work

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#972]
Example (see the footnote inside the _tutorials_ panel) https://nus-cs2113-ay1920s2.github.io/website/admin/weeklySchedule.html

![image](https://user-images.githubusercontent.com/1673303/72126620-c1ab3780-33a7-11ea-8d78-6808cbb7d862.png)

**Comment by openorclose** [comment]
This occurs as the panel is a dynamic panel, so the footnotes are not generated in the "main" html.

We could alternatively put footnotes at the bottom referencing stuff in unloaded panels. Of course, the downside would be that the reader might see a sudden jump in footnote numbering due to unloaded panels.

Implementation wise, we would have to loop through all nested panels to exhaustively find all footnotes.

**Comment by damithc** [comment]
If we assume that panels are typically used to embed content taken from elsewhere, it makes more sense if the footnote is contained inside the panel rather than at the bottom of the host page. Is that feasible?

**Comment by openorclose** [comment]
Yeah, that would be feasible

**Comment by damithc** [comment]
> Yeah, that would be feasible

Great. Let's give that a try then.

**Comment by openorclose** [comment]
@openorclose I remember the reason we removed the "linkbacks" from the footnotes was because sometimes the panel containing the reference wouldn't be open, so it would be confusing if the linkback took you nowhere.

Since now each panel has its own footnote, would it be good to add the linkbacks back?

![image](https://user-images.githubusercontent.com/3646725/73606966-20e91a00-45eb-11ea-99cb-ce8ce93df30b.png)

referring to the arrow beside "Math".

**Comment by damithc** [comment]
> Since now each panel has its own footnote, would it be good to add the linkbacks back?

Sure 👍

**Comment by ang-zeyu** [comment]
> > Since now each panel has its own footnote, would it be good to add the linkbacks back?
> 
> Sure 👍

Since we show the footnotes in popovers, the backreference would also appear in the popover though.
I think the popover implementation is sufficient to warrant not adding a backreference, since you can directly see the footnote. The bottom footnote area then just serves as a "footnote consolidation area".

The back button in browsers should also be able to take you back to where you were before clicking the footnote and is also more accurate if you have multiple references to the same footnote (otherwise it always takes you back to the *topmost* footnote reference)

**Comment by ang-zeyu** [comment]
Since footnotes for includes from panels are now "sealed" as well, should we also clarify how they should behave in the case of static `<include>`s?
- should definitions from `<include>`s be allowed to leak into the content
- should the content definitions be allowed to leak into the `<include>`
- footnotes from static includes should display *together* with the main content's footnotes, unlike panels

**Comment by damithc** [comment]
@openorclose any thoughts?

**Comment by ang-zeyu** [comment]
I'm going to encapsulate (1) and (2) for the v3 'rewrite' for now, it may lead to easier-to-predict behaviour

Footnote definitions can still be reused via nunjucks' `{% include %}` which is preprocessed.
It'll be a long way to a proper v3 release so we can change things as needed as well 🙂 

(3) should definitely be a thing though
