### ISSUE TITLE
Support search bar in siteNav

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#973]
v2.9.0
Current: the search bar is in the topNav
Problem: user needs to scroll to top before searching
Suggestion: provide a way to insert a search bar into the siteNav (which has a sticky behavior compared to topNav)

**Comment by yash-chowdhary** [comment]
I'm not sure, but can this issue be resolved by just hardcoding the search bar into the template `site-nav.md` file? This way every website created would have it if initialized with the `default` template.
The change I made to `site-nav.md` is reflected here - 

<img width="400" alt="Screenshot 2020-01-15 at 1 42 43 PM" src="https://user-images.githubusercontent.com/21968718/72408146-ea16a580-379c-11ea-9b8b-e1b96db78e96.png">

Does this meet the requirement, or is there something else that this issue was targetting?

**Comment by le0tan** [comment]
We can provide an option to stick the navbar on the screen so that the search bar is always accessible, reference design is described in #980

**Comment by damithc** [comment]
Being able to add a search box to the siteNav is good enough me. I tried adding the one and here are the problems I encountered:

Search results get clipped.
![image](https://user-images.githubusercontent.com/1673303/72420159-2e17a380-37b9-11ea-822f-598d11732d84.png)

Doesn't seem to work with Algolia search.
```html
<form class="navbar-form">
  <searchbar placeholder="Search" algolia menu-align-left></searchbar>
</form>
```

![image](https://user-images.githubusercontent.com/1673303/72420566-f2c9a480-37b9-11ea-8baf-900c28e64cb3.png)

**Comment by ang-zeyu** [comment]
this is tricky https://stackoverflow.com/questions/11520728/overflow-yvisible-not-working-when-overflow-xhidden-is-present

**Comment by damithc** [comment]
I see. May be not a big issue if the TopNav can be reliably fixed to the stop as users can easily access the search bar through the TopNav.

**Comment by ang-zeyu** [comment]
now possible with the new layouts system #1403, as overflow can be set just on the `<site-nav>` component itself

I've ensured this works with the user guide and `markbind init` templates, but left the search bar on the top right
